packages/Pagination/src/Resolvers/StartSizeAsArrayInQueryResolver.php
packages/Pagination/src/Resolvers/StartSizeInQueryResolver.php
packages/Pagination/src/Traits/DataResolverTrait.php
packages/Pagination/src/Traits/PagePaginationDataResolverTrait.php
packages/Pagination/tests/Resolvers/StartSizeAsArrayInQueryResolverTest.php
packages/Pagination/tests/Resolvers/StartSizeInQueryResolverTest.php

- Parameter $data[] can be a request payload which allows string values that should be parsed as integer as an argument.

[Pagination] Refactor PagePaginationDataResolverTrait according to new StartSizeData.

---

packages/EasyApiToken/src/Exceptions/AbstractEasyApiTokenFactoryException.php
packages/EasyApiToken/src/Exceptions/InvalidConfigurationException.php
packages/EasyApiToken/src/Factories/EasyApiDecoderFactory.php
packages/EasyApiToken/src/Factories/EasyApiTokenDecoderFactory.php
packages/EasyApiToken/tests/Factories/EasyApiDecoderFactoryTest.php

This adds a factory to build EasyApiToken decoder based on a configuration array.

[EasyApiToken]: Add factory for EasyApiTokenDecoder objects

---

packages/EasyDocker/templates/docker/nginx/default.conf.twig

[EasyDocker] Fix nginx conf to listen to port 80 instead of 8080

---

packages/EasyApiToken/src/External/Auth0JwtDriver.php
packages/EasyApiToken/src/Helpers/Jwt/TokenGenerator.php
packages/EasyApiToken/src/Interfaces/Helpers/Jwt/TokenGeneratorInterface.php

There is a possible bug in Auth0 `TokenGenerator` where it does not allow us to add
`sub` (subject) claim.

Use custom token generator for auth0 jwt token creation

---

packages/EasyDecision/readme.md
packages/EasyDecision/src/Decisions/AbstractDecision.php
packages/EasyDecision/tests/Decisions/AffirmativeDecisionTest.php

[EasyDecision] Reverse priority order for decision rules (0 is now higher than 100)

[EasyDecision] Reverse priority order for decision rules

---

.github/PULL_REQUEST_TEMPLATE.md

The template for submitting a new PR mentioned the CHANGELOG should be updated, however this is not the case, as it is handled automatically

Updated GitHub PR Template to denote CHANGELOG does not actually require

---

packages/EasyDocker/src/Console/Commands/AbstractTemplatesCommand.php
packages/EasyDocker/src/Parameters/ParameterResolver.php
packages/EasyDocker/tests/AbstractTestCase.php
packages/EasyDocker/tests/Console/Commands/DockerFilesGeneratorCommandTest.php

By default, a `.easy` directory will be assumed for parameter and manifest files generated by this tool
Backwards compatibility is present, this will only affect new projects using the tool, when a manifest/params file does not already exist

[EasyDocker] Use .easy directory for easy-docker generated parameter & manifest files

---

packages/EasyCfhighlander/src/Console/Commands/AbstractTemplatesCommand.php
packages/EasyCfhighlander/src/Parameters/ParameterResolver.php
packages/EasyCfhighlander/tests/Console/Commands/CloudFormationCommandTest.php
packages/EasyCfhighlander/tests/Console/Commands/CodeCommandTest.php

Same as https://github.com/loyaltycorp/easy-monorepo/pull/68 but for EasyCfhighlander
> By default, a `.easy` directory will be assumed for parameter and manifest files generated by this tool
> Backwards compatibility is present, this will only affect new projects using the tool, when a manifest/params file does not already exist

[EasyCfhighlander] Use .easy directory for easy-docker generated parameter & manifest files

---

packages/EasyEntityChange/src/Doctrine/EntityChangeSubscriber.php

- [EasyEntityChange] Preserving entity id for use at postFlush by using entity clone

[EasyEntityChange] Preserving entity id for use at postFlush

---

packages/EasyLogging/src/Bugsnag/BugsnagHandler.php

| Tests pass?   | there are no tests
Null checks dont work very well when you dont control what might be in $context['exception']. Check if it is actually throwable.

[EasyLogging] Check shouldReport if the exception is throwable

---

packages/EasyDecision/src/Interfaces/ExpressionLanguageRuleFactoryInterface.php
packages/EasyDecision/src/Rules/ExpressionLanguageRule.php
packages/EasyDecision/src/Rules/ExpressionLanguageRuleFactory.php
packages/EasyDecision/tests/AbstractTestCase.php
packages/EasyDecision/tests/Decisions/DecisionWithExpressionLanguageTest.php

[EasyDecision] Implement optional name on expression language rule

---

packages/EasyAsync/src/Bridge/WithProcessJobLogTrait.php
packages/EasyAsync/src/Implementations/Doctrine/DBAL/JobLogPersister.php
packages/EasyAsync/tests/Implementations/Doctrine/DBAL/JobLogPersisterTest.php

| Bug fix?      |no
| New feature?  |yes 

[EasyAsync] Persist jobLog when status is in progress

---

packages/EasyStandard/src/Sniffs/Classes/AvoidPublicPropertiesSniff.php
packages/EasyStandard/tests/Sniffs/Classes/AvoidPublicPropertiesSniffTest.php
packages/EasyStandard/tests/fixtures/Sniffs/Classes/AvoidPublicPropertiesSniffTest.php.inc

[EasyStandards] Implement sniff to avoid public properties in classes

---

packages/EasyCore/src/Bridge/Symfony/ApiPlatform/DataPersister/ChainSimpleDataPersister.php

- ChainSimpleDataPersister to decorate ContextAwareDataPersisterInterface instead of DataPersisterInterface
- Because **easy_core.api_platform.simple_data_persister_enabled** when set to true will give an empty $context

[EasyCore] ChainSimpleDataPersister decorates ContextAwareDataPersisterInterface

---

packages/EasyPagination/src/Bridge/Laravel/Providers/AbstractStartSizeEasyPaginationProvider.php
packages/EasyPagination/tests/AbstractTestCase.php
packages/EasyPagination/tests/Bridge/Laravel/ServiceProvidersTest.php

Can't use alias since it resulted to recursive circular call for `app->getAlias(...)` for `request` and `Illuminate\Http\Request` during tests.
Instead, update the retrieval of request from the application using `request` for console and `Illuminate\Http\Request` if not console.
| New feature?  |no 

[EasyPagination] Fix request for Laravel in console

---

packages/EasyCore/src/Bridge/Laravel/Listeners/DoctrineRestartQueueOnEmCloseListener.php
packages/EasyCore/src/Bridge/Laravel/Providers/EasyCoreServiceProvider.php
packages/EasyCore/src/Bridge/Laravel/config/easy-core.php
packages/EasyCore/tests/Bridge/Laravel/Listeners/DoctrineRestartQueueOnEmCloseListenerTest.php

- added listener for worker restarting
| Fixed tickets | #PTS-962

[EasyCore] Added listener for worker restart on EM close

---

packages/EasyAsync/src/Interfaces/JobLogInterface.php
packages/EasyAsync/src/Updaters/JobLogUpdater.php
packages/EasyAsync/tests/Updaters/JobLogUpdaterTest.php

…mplement generic failure reason

[EasyAsync] Add throwable message to debug info when joblog fails

---

packages/EasyErrorHandler/src/Bridge/Laravel/Handler/Handler.php
packages/EasyErrorHandler/src/Bridge/Laravel/config/easy-error-handler.php

- added type casting in config (allows to pass the env variable value from `phpunit.xml`)

[EasyErrorHandler] Added type casting in config

---

packages/EasyCore/composer.json

- Require elasticsearch package in easy-core search to fix error in SearchService

[EasyCore] Require elasticsearch package for easy-search

---

packages/EasySchedule/composer.json
packages/EasySchedule/src/Interfaces/ScheduleRunnerInterface.php
packages/EasySchedule/src/ScheduleRunner.php

[EasySchedule] Use eonx-com/easy-lock instead of easy-core

---

packages/EasyStandard/src/Sniffs/ControlStructures/ArrangeActAssertSniff.php
packages/EasyStandard/tests/Sniffs/ControlStructures/ArrangeActAssertSniff/ArrangeActAssertSniffTest.php
packages/EasyStandard/tests/Sniffs/ControlStructures/ArrangeActAssertSniff/Fixture/Correct/EmptyLinesInClosure.php.inc
packages/EasyStandard/tests/Sniffs/ControlStructures/ArrangeActAssertSniff/Fixture/Correct/innerCurlyBrackets.php.inc

- Improve ArrangeActAssertSniff to ignore empty line in closure

[EasyStandard] Improve ArrangeActAssertSniff to ignore empty lines inside closures

---

packages/EasyLogging/src/Bridge/BridgeConstantsInterface.php
packages/EasyLogging/src/Bridge/Laravel/EasyLoggingServiceProvider.php
packages/EasyLogging/src/Bridge/Laravel/config/easy-logging.php
packages/EasyLogging/src/Bridge/Symfony/DependencyInjection/Configuration.php
packages/EasyLogging/src/Bridge/Symfony/DependencyInjection/EasyLoggingExtension.php
packages/EasyLogging/src/Bridge/Symfony/Resources/config/default_stream_handler.php
packages/EasyLogging/src/Config/StreamHandlerConfigProvider.php

[EasyLogging] Allow to specify stream handler level in config

---

packages/EasyStandard/src/Rector/ExplicitBoolCompareRector.php
packages/EasyStandard/tests/Rector/ExplicitBoolCompareRector/Fixture/FuncCallWithShortTrueComparison.php.inc
packages/EasyStandard/tests/Rector/ExplicitBoolCompareRector/Fixture/MethodCallWithShortTrueComparison.php.inc

Fixed ExplicitBoolCompareRector notices on short true comparisons.

[EasyStandard] Fix ExplicitBoolCompareRector

---

packages/EasySsm/src/Console/Commands/ApplyCommand.php
packages/EasySsm/src/Console/Commands/DiffCommand.php
packages/EasySsm/src/Console/Commands/DumpEnvCommand.php
packages/EasySsm/src/Console/Commands/ExportEnvsCommand.php
packages/EasySsm/src/Console/Commands/InitCommand.php
packages/EasySsm/src/Console/Commands/LocalApplyCommand.php
packages/EasySsm/src/Console/Commands/LocalDiffCommand.php
packages/EasySsm/src/Console/Commands/PullCommand.php
packages/EasyTest/src/Console/Commands/CheckCoverageCommand.php

| Fixed tickets | -  
This PR is about of a little optimisation to avoid initialisation of all command services on each executing `bin/console` command.
Since Symfony 3.4 console commands can be lazy thanks to [a static name property](https://github.com/symfony/symfony/pull/23887).
This change does not break BC because the BC layer is already [in the base command's constructor](https://github.com/symfony/symfony/pull/23887/files#diff-8e80595663798837db1b033187835535R75).

[EasySsm][EasyTest] Make console commands lazy.

---

packages/EasyCore/src/Http/Middleware/SetContentLength.php

[EasyCore] Mark SetContentLength as deprecated

---

packages/EasyBankFiles/src/Parsers/Bpay/Batch/Parser.php
packages/EasyBankFiles/src/Parsers/Bpay/Brf/Parser.php
packages/EasyBankFiles/src/Parsers/DirectEntry/Parser.php
packages/EasyBankFiles/src/Parsers/DirectEntry/Results/Error.php
packages/EasyBankFiles/src/Parsers/DirectEntry/Results/Header.php

| Tests pass?   | no    
Refactored DirectLink BankFiles parser a bit:
- Added errors array.
- Added one more check to getProcessedDate() method, to prevent throwing exception on `new DateTime()` with incorrect data.
- Make line code comparisons in the parser more strictly, to prevent a bug, e.g. `'w' == 0`.
- Added additional validation of the lines by its minimal valid length, otherwise one of our `substr()` can result a `false` value and we could have a TypeError exception in the application.
No tests implemented at this moment, seems it is messed up a bit in this package, - got a lot of errors:
```
Error: Class …
```

[EasyBankFiles] Refactor DirectLink files parser.

---

packages/EasySecurity/composer.json
packages/EasyTest/composer.json
packages/EasyTest/config/services.yaml
packages/EasyTest/src/InvalidDataMaker/AbstractInvalidDataMaker.php
packages/EasyTest/src/InvalidDataMaker/InvalidDataMaker.php
phpstan.neon

Introducing a new util class helpful in functional tests of ApiResource validation.
| Fixed tickets | ...
`InvalidDataMaker` can be extended in an application to add new yield methods.
When custom validation messages are used in an application, a translation file path should be added either by overriding the `InvalidDataMaker::$translations` property or by calling the `InvalidDataMaker::addTranslations()` method from a `setUp` method.
All the yield methods generate an array with the following items: `data` (an array containing invalid data that can be passed to an API endpoint), `message`, and `propertyPath` (a translated message and a …

[EasyTest] Created InvalidDataMaker

---

packages/EasyErrorHandler/src/Bridge/Laravel/config/easy-error-handler.php
packages/EasyErrorHandler/src/Traits/DealsWithErrorLogLevelTrait.php
packages/EasyUtils/readme.md
packages/EasyUtils/src/CollectorHelper.php
packages/EasyUtils/src/Exceptions/InvalidArgumentException.php
packages/EasyUtils/src/Interfaces/EasyUtilsExceptionInterface.php
packages/EasyUtils/tests/CollectorHelperTest.php

[EasyUtils] Improve CollectorHelper

---

packages/EasyWebhook/src/AbstractWebhook.php
packages/EasyWebhook/src/Interfaces/WebhookInterface.php
packages/EasyWebhook/src/Middleware/SendAfterMiddleware.php
packages/EasyWebhook/tests/Middleware/SendAfterMiddlewareTest.php
packages/EasyWebhook/tests/WebhookTest.php

[EasyWebhook] Implement sendAfter logic

---

packages/EasyWebhook/src/Bridge/Laravel/EasyWebhookServiceProvider.php
packages/EasyWebhook/src/Bridge/Symfony/Resources/config/core_middleware.php

[EasyWebhook] Add missing SendAfterMiddleware to config in bridges

---

packages/EasyWebhook/composer.json
packages/EasyWebhook/src/Bridge/Laravel/EasyWebhookServiceProvider.php
packages/EasyWebhook/src/Bridge/Symfony/Resources/config/services.php
packages/EasyWebhook/src/Stores/AbstractDoctrineDbalStore.php
packages/EasyWebhook/src/Stores/DoctrineDbalStore.php

[EasyWebhook] Clean up

---

packages/EasyWebhook/src/Bridge/Symfony/DependencyInjection/EasyWebhookExtension.php
packages/EasyWebhook/src/Middleware/AsyncMiddleware.php

[EasyWebhook] Disable async properly if Messenger not installed

---

packages/EasyWebhook/src/Interfaces/Stores/StoreInterface.php
packages/EasyWebhook/src/Middleware/IdHeaderMiddleware.php
packages/EasyWebhook/src/Stores/NullStore.php
packages/EasyWebhook/tests/Middleware/IdHeaderMiddlewareTest.php

[EasyWebhook] Don't send webhook-id header if default id

---

packages/EasyStandard/src/Sniffs/ControlStructures/LinebreakAfterEqualsSignSniff.php
packages/EasyStandard/tests/Sniffs/ControlStructures/LinebreakAfterEqualsSignSniff/Fixture/LinebreakAfterEqualsSignSniffTest.php.inc
packages/EasyStandard/tests/Sniffs/ControlStructures/LinebreakAfterEqualsSignSniff/LinebreakAfterEqualsSignSniffTest.php

- Add LinebreakAfterEqualsSignSniff.

[EasyStandard] Implement LinebreakAfterEqualsSignSniff

---

packages/EasyApiToken/src/Decoders/ChainDecoder.php

[EasyApiToken] Fix ChainDecoder to use CollectorHelper::filterByClassArray

---

packages/EasyAsync/src/Doctrine/ManagersSanityChecker.php
packages/EasyAsync/tests/Doctrine/ManagersSanityCheckerTest.php
packages/EasyAsync/tests/Doctrine/Stubs/ManagerRegistryStub.php

| New feature?  | yno 
| Fixed tickets | #554

[EasyAsync] ManagersSanityChecker - fetchAllAssociative instead of executeStatement

---

packages/EasyWebhook/docs/middleware.md
packages/EasyWebhook/src/Bridge/Laravel/EasyWebhookServiceProvider.php
packages/EasyWebhook/src/Bridge/Symfony/Resources/config/core_middleware.php
phpstan.neon

[EasyWebhook] Move SendAfterMiddleware to core after middleware so http client options are populated

---

packages/EasyPagination/src/Traits/DoctrinePaginatorTrait.php

[EasyPaginator] Fix getTotalItems for Doctrine paginator when no fromAlias

---

packages/EasyLock/src/Bridge/BridgeConstantsInterface.php
packages/EasyLock/src/Bridge/Symfony/Resources/config/services.php

[EasyLock] Add monolog.logger tag to lock service for symfony for dedicated channel

---

packages/EasyWebhook/src/HttpClientFactory.php

[EasyWebhook] Explicitly use http 1.1 in default http client

---

packages/EasyCore/src/Bridge/Symfony/Resources/config/services.php
packages/EasyCore/src/Doctrine/Subscribers/EntityEventSubscriber.php
packages/EasyCore/tests/Doctrine/Subscribers/EntityEventSubscriberTest.php

| Fixed tickets | PLU-3387   
- Register `DeferredEntityEventDispatcher` service
- return filtering logic to the `\EonX\EasyCore\Doctrine\Subscribers\EntityEventSubscriber`

[EasyCore] DeferredEntityEventDispatcher service

---

packages/EasyBugsnag/src/Bridge/Symfony/Resources/config/sessions.php

[EasyBugsnag] Use cache channel for bugsnag session cache

---

packages/EasyHttpClient/src/Bridge/BridgeConstantsInterface.php
packages/EasyHttpClient/src/Bridge/Symfony/DependencyInjection/Compiler/DecorateDefaultClientPass.php
packages/EasyHttpClient/src/Bridge/Symfony/DependencyInjection/Configuration.php
packages/EasyHttpClient/src/Bridge/Symfony/DependencyInjection/EasyHttpClientExtension.php
packages/EasyHttpClient/src/Bridge/Symfony/EasyHttpClientSymfonyBundle.php

[EasyHttpClient] Add Symfony config to decorate default http client

---

packages/EasyLogging/src/Formatters/JsonFormatter.php
packages/EasyLogging/src/Formatters/SumoJsonFormatter.php
packages/EasyLogging/tests/Formatters/JsonFormatterTest.php

[EasyLogging] JsonFormatter which explicitly formats DateTimes

---

packages/EasyLogging/src/Formatters/JsonFormatter.php

Fixed the JsonFormatter parent call to be compatible with Monolog v2.

[EasyLogging] Fixed the JsonFormatter parent call

---

packages/EasyAsync/src/Bridge/Laravel/Providers/EasyAsyncServiceProvider.php

Fixed the `DoctrineManagersSanityCheckListener` definition in the EasyAsyncServiceProvider.

[EasyAsync] Fixed the DoctrineManagersSanityCheckListener definition

---

packages/EasySecurity/src/Bridge/Symfony/Resources/config/services.php
packages/EasySecurity/src/Bridge/Symfony/Security/ContextAuthenticator.php
packages/EasySecurity/src/Bridge/Symfony/Security/SecurityContextAuthenticator.php

[EasySecurity] Make sure configurator listener runs before Symfony listener

---

packages/EasyAsync/src/Bridge/Laravel/Providers/EasyAsyncServiceProvider.php
packages/EasyAsync/src/Bridge/Laravel/Queue/QueueWorkerStoppingListener.php
packages/EasyCore/src/Bridge/Laravel/Listeners/DoctrineClearEmBeforeJobListener.php

[EasyAsync] Move Laravel queue listeners from easy-core to easy-async

---

packages/EasyDecision/src/Configurators/AddRulesDecisionConfigurator.php

**Context**
When creating multiple decisions using `DecisionFactory`, we're getting `Cannot traverse an already closed generator`
**Solution**
Use `filterByClassAsArray` in `AddRulesDecisionConfigurator` to allow multiple calls in `DecisionFactory::createXXX` to create multiple decisions to make and execute.

[EasyDecision] Fix filter rules in AddRulesDecisionConfigurator

---

packages/EasyCore/src/Doctrine/Dispatchers/DeferredEntityEventDispatcher.php
packages/EasyCore/tests/Doctrine/Dispatchers/DeferredEntityEventDispatcherTest.php

In the easy-core package we have the `\EonX\EasyCore\Doctrine\Dispatchers\DeferredEntityEventDispatcher` event dispatcher that allows us to dispatch the `\EonX\EasyCore\Doctrine\Events\EntityCreatedEvent` and `\EonX\EasyCore\Doctrine\Events\EntityUpdatedEvent` events when an entity really saved in a database. But we have found a problem with this dispatcher.
Let’s imagine the following flow:
* Begin a transaction.
* Create an entity and flush it.
* Update the entity and flush.
* Update the entity again and flush.
* Commit the transaction.
When the transaction will be committed our dispatcher will dispatch 3 events: one `EntityCreatedEvent` and two `EntityUpdatedEvent`. It’s wrong because in terms of the database we have created the entity and that's all. The same for the regular updates. …

[EasyCore] Make sure DeferredEntityEventDispatcher dispatches one event per entity

---

packages/EasyCore/src/Bridge/Symfony/ApiPlatform/Filter/VirtualSearchFilter.php

If we allow square brackets in filter property it will look great in docs and will be consistent with DateFilter.

[EasyCore] Allow square brackets in VirtualSearchFilter

---

packages/EasyActivity/src/Bridge/EasyDoctrine/EasyDoctrineEntityEventsSubscriber.php
packages/EasyActivity/tests/Bridge/EasyDoctrine/EasyDoctrineEntityEventsSubscriberTest.php
packages/EasyDoctrine/src/Dispatchers/DeferredEntityEventDispatcher.php
packages/EasyDoctrine/src/Dispatchers/DeferredEntityEventDispatcherInterface.php
packages/EasyDoctrine/src/Events/EntityActionEventInterface.php
packages/EasyDoctrine/src/Events/EntityCreatedEvent.php
packages/EasyDoctrine/src/Events/EntityDeletedEvent.php
packages/EasyDoctrine/src/Events/EntityUpdatedEvent.php
packages/EasyDoctrine/src/Subscribers/EntityEventSubscriber.php
packages/EasyDoctrine/tests/Events/EntityDeletedEventTest.php
packages/EasyDoctrine/tests/Fixtures/Product.php
packages/EasyDoctrine/tests/Subscribers/EntityEventSubscriberTest.php

We have the `EonX\EasyDoctrine\Events\EntityCreatedEvent` and `EonX\EasyDoctrine\Events\EntityUpdatedEvent` events. Now we also need to know about deleted entities.

[EasyDoctrine] Add EntityDeletedEvent

---

packages/EasyActivity/src/Bridge/Symfony/Resources/config/services.php

Now an application must register `easy_activity.serializer` service. Otherwise, the error `Cannot instantiate interface Symfony\Component\Serializer\SerializerInterface` occurs.
The package should provide a default implementation for `easy_activity.serializer`.

[EasyActivity] Fix 'easy_activity.serializer' service registration

---

packages/EasyActivity/src/ActivitySubject.php
packages/EasyActivity/src/Resolvers/DefaultActivitySubjectResolver.php
packages/EasyActivity/tests/Bridge/Symfony/Serializers/SymfonyActivitySubjectDataSerializerTest.php

As we have a convention to use default `null` value for optional arguments and place them at the end of the arguments list it was decided to change the signature of the `ActivitySubject` constructor

[EasyActivity] Codestyle fix

---

packages/EasyDoctrine/composer.json
packages/EasyDoctrine/src/DBAL/Types/JsonbType.php
packages/EasyDoctrine/tests/DBAL/Types/JsonbTypeTest.php

PostgreSQL doesn't guaranty that keys in DB will keep the order as they presented in an array during the saving.
Sometimes it's really true and causes some troubles.
That's why I've decided to sort an array right after fetching it from a database.

[EasyDoctrine] Sort an array (decoded JSON data) by keys in the JsonbType DBAL type.

---

packages/EasyCore/src/Bridge/Symfony/ApiPlatform/Command/ApiResourceAndSimpleDataPersisterMaker.php
packages/EasyCore/src/Bridge/Symfony/ApiPlatform/Listeners/ResolveRequestAttributesListener.php
packages/EasyDoctrine/src/ORM/Decorators/EntityManagerDecorator.php
packages/EasyRequestId/src/Bridge/Symfony/Listeners/RequestListener.php
packages/EasySecurity/src/Bridge/Symfony/Security/ContextAuthenticator.php

Fixed several deprecations:
- [EasyCore] Added the `getCommandDescription` method to the `ApiResourceAndSimpleDataPersisterMaker` console command.
- [EasyCore] Started to use the `getMainRequest` method of the `RequestStack` class if possible.
- [EasyDoctrine] Improved type hinting in the `EntityManagerDecorator` class.
- [EasyRequestId] Started to use the `getMainRequest` method of the `RequestEvent` class if possible.
- [EasySecurity] Stopped using the `DeferredSecurityContextProviderInterface` deprecated class.

Fixed several deprecations

---

composer.json
packages/EasyUtils/src/Interfaces/MathComparisonInterface.php
packages/EasyUtils/src/Interfaces/MathInterface.php
packages/EasyUtils/src/Math.php
packages/EasyUtils/src/MathComparison.php
packages/EasyUtils/tests/AbstractMathTestCase.php

| Fixed tickets |    
- Add comparing methods to Math to simplify comparisons:
```
$math->compareThat($leftOperand)
->equalTo($rightOperand)
->greaterOrEqualTo($rightOperand)
->greaterThan($rightOperand)
->lessOrEqualTo($rightOperand)
->lessThan($rightOperand)
```
- ~~`comp()` method marked as `@deprecated` to avoid BC break - it should be deleted then~~
- ~~what do you think about naming of the class, comparisons a bit not a math operations. In EWMP we named this class as `BcMathDecorator`~~

[EasyUtils] Add sugar comparing methods to Math

---

packages/EasyActivity/composer.json
symfony-recipes/eonx-com/easy-activity/3.4/config/packages/easy_activity.yaml
symfony-recipes/eonx-com/easy-activity/3.4/manifest.json
symfony-recipes/eonx-com/easy-doctrine/3.4/config/packages/easy_doctrine.yaml
symfony-recipes/eonx-com/easy-doctrine/3.4/manifest.json

The `eonx-com/easy-activity` package doesn't depend on `eonx-com/easy-doctrine`. But the flex recipe adds `EonX\EasyDoctrine\Bridge\Symfony\EasyDoctrineSymfonyBundle` to the `bundles.php`. 
It leads to an error in `composer require eonx-com/easy-activity`.
Also, I've added a few changes to make it easier to install EasyActivity:
1. Added a `suggest` section to the `composer.json`
2. Added a flex recipe for `eonx-com/easy-doctrine`

[EasyActivity] [EasyDoctrine] Change flex recipes to make it easier to install EasyActivity

---

packages/EasySecurity/src/Bridge/Symfony/Factories/AuthenticationFailureResponseFactory.php

[EasySecurity] Rename `sub_code` to `subCode` in the authentication failure response

---

packages/EasyWebhook/src/Middleware/SendWebhookMiddleware.php

[EasyWebhook] Make sure failing webhook response is not set on result

---

packages/EasySecurity/src/Bridge/Symfony/Interfaces/AuthenticationExceptionInterface.php
packages/EasySecurity/src/Bridge/Symfony/Security/SecurityContextAuthenticator.php
packages/EasySecurity/tests/Bridge/Symfony/Security/SecurityContextAuthenticatorTest.php
packages/EasySecurity/tests/Bridge/Symfony/Stubs/CustomAuthenticationException.php

Currently, all exceptions in the `SecurityContextConfigurator` are caught and there is no way to define a specific error code for the client. The client always gets:
```
{"message":"Unauthorized","code":401,"subCode":0}
```
This PR adds support for exceptions with a specific error code.

[EasySecurity] Allow custom authentication exceptions

---

packages/EasyDoctrine/src/Interfaces/TimestampableInterface.php
packages/EasyDoctrine/src/Subscribers/TimestampableEventSubscriber.php
packages/EasyDoctrine/src/Traits/TimestampableTrait.php
packages/EasyDoctrine/tests/Subscribers/TimestampableEventSubscriberTest.php
packages/EasyDoctrine/tests/Traits/TimestampableTraitTest.php

Backward compatibility changes:
- Renamed the `TimestampableImmutableTrait` trait to `TimestampableTrait`.

[EasyDoctrine] Added types to `TimestampableTrait`

---

packages/EasyApiToken/src/Bridge/Symfony/Providers/AbstractFirewallAwareDecoderProvider.php

I tried to use this brand new class with Symfony 6 and got this error:
> Cannot autowire service “App\Infrastructure\EasySecurity\Provider\ApiTokenDecoderProvider”: argument “$firewallMap” of method “EonX\EasyApiToken\Bridge\Symfony\Providers\AbstractFirewallAwareDecoderProvider::setFirewallMap()” references class “Symfony\Bundle\SecurityBundle\Security\FirewallMap” but no such service exists. Try changing the type-hint to “Symfony\Component\Security\Http\FirewallMapInterface” instead.

[EasyApiToken] Fixed dependency injection in AbstractFirewallAwareDecoderProvider

---

packages/EasyBatch/src/Bridge/Symfony/Messenger/ProcessBatchItemMiddleware.php

- Update ProcessBatchItemMiddleware to fix handling EasyBatchExceptionInterface and include previous exception in new "wrapping" exception

[EasyBatch] Fix error handling on EasyBatchExceptionInterface to include previous exception

---

packages/EasyLogging/src/Bridge/Symfony/DependencyInjection/Compiler/ReplaceChannelsDefinitionPass.php
packages/EasyLogging/src/Bridge/Symfony/Resources/config/services.php
packages/EasyUtils/src/Math.php
phpstan.neon

If `MonologBundle` is registered after `EasyLoggingBundle` it replaces our aliases.
In this PR we add aliases in the compiler pass - at this step, all bundles are already loaded.

[EasyLogging] Add aliases after all bundles loaded

---

packages/EasyErrorHandler/src/ErrorHandler.php

- Add logic to handle Symfony Messenger UnrecoverableMessageHandlingException

[EasyErrorHandler] Add logic to handle Symfony Messenger UnrecoverableMessageHandlingException

---

packages/EasyBugsnag/src/Bridge/Laravel/EasyBugsnagServiceProvider.php
packages/EasyBugsnag/src/Bridge/Laravel/config/easy-bugsnag.php
packages/EasyBugsnag/src/Bridge/Symfony/DependencyInjection/Configuration.php
packages/EasyBugsnag/src/Bridge/Symfony/DependencyInjection/EasyBugsnagExtension.php
packages/EasyBugsnag/tests/Bridge/Laravel/AbstractLaravelTestCase.php
packages/EasyUtils/src/Bridge/BridgeConstantsInterface.php
packages/EasyUtils/src/Bridge/Laravel/EasyUtilsServiceProvider.php
packages/EasyUtils/src/Bridge/Laravel/config/easy-utils.php
packages/EasyUtils/src/Bridge/Symfony/DependencyInjection/Configuration.php
packages/EasyUtils/src/Bridge/Symfony/Resources/config/sensitive_data.php
packages/EasyUtils/src/SensitiveData/SensitiveDataSanitizer.php
packages/EasyUtils/src/SensitiveData/SensitiveDataSanitizerInterface.php
packages/EasyUtils/tests/SensitiveData/SensitiveDataSanitizerTest.php

[EasyUtils] Enable sensitive data sanitizer by default + implement default keys to mask

---

packages/EasyBankFiles/src/Generators/Aba/Generator.php

According to NAB and Cuscal docs, this field must be unsigned.

[EasyBankFiles] Make fileUserNetTotalAmount absolute

---

packages/EasyWebhook/src/Interfaces/Stores/StoreInterface.php
packages/EasyWebhook/src/Stores/DoctrineDbalResultStore.php
packages/EasyWebhook/src/Stores/DoctrineDbalStore.php
packages/EasyWebhook/tests/Stores/DoctrineDbalResultStoreTest.php
packages/EasyWebhook/tests/Stores/DoctrineDbalStoreFromIlluminateDatabaseTest.php
packages/EasyWebhook/tests/Stores/DoctrineDbalStoreTest.php

- Added timezone on DoctrineDbalStore DoctrineDbalResult as optional parameter for timestamps.
---

[EasyWebhook] feature/easy-webhooks-add-config-for-timestamps-timezone

---

packages/EasyHttpClient/src/Bridge/BridgeConstantsInterface.php

The `http_client` log channel [is used for symfony/http-client](https://github.com/symfony/symfony/blob/123b1651c4a7e219ba59074441badfac65525efe/src/Symfony/Bundle/FrameworkBundle/Resources/config/http_client.php#L32).
This causes a problem: when we log messages from the `http_channel` we have duplicated messages from `eonx-com/easy-http-client` and `symfony/http-client`.
In EonX projects we use the `EasyHttpClientBridgeConstantsInterface::LOG_CHANNEL` constant. So, renaming should not break our projects.

[EasyHttpClient] Rename log channel for HTTP requests

---

packages/EasyErrorHandler/src/Bridge/Symfony/DependencyInjection/Configuration.php

Using `messages` as default translation domain will make it easier for applications to translate their own messages.

[EasyErrorHandler] Update default translation domain for Symfony bridge

---

packages/EasyCore/src/Bridge/Symfony/DependencyInjection/Compiler/ApiPlatformDataPersistersPass.php

[EasyCore] Allow to reset simple data persister services

---

packages/EasyUtils/src/SensitiveData/SensitiveDataSanitizerInterface.php

[EasyUtils] Added the `auth_bearer` key to `SensitiveDataSanitizerInterface::DEFAULT_KEYS_TO_MASK`

---

packages/EasyCore/src/Bridge/Symfony/ApiPlatform/DataTransformer/AbstractInputDataTransformer.php

The API Platform Docs recommend checking if `$data` is an instance of an object to which we want to transform.
[https://api-platform.com/docs/core/dto/#initialize-the-input-dto-for-partial-update](https://api-platform.com/docs/core/dto/#initialize-the-input-dto-for-partial-update)
We already do this in Payments. I have checked in AVC - all tests passed.
In some cases, for example, if we transform an API Resource object, we don't want to do validation.

[EasyCore] Improve AbstractInputDataTransformer

---

packages/EasySwoole/src/Runtime/EasySwooleRunner.php
phpstan.neon

When app state is compromised we stop a worker immediately. It leads to 502 error from ELB.
This PR adds an argument to stop a worker [safely](https://openswoole.com/docs/modules/swoole-server-stop#stopping-a-worker-safely).

[EasySwoole] Stopping a worker safely when app state is compromised

---

packages/EasyDoctrine/src/DBAL/Types/CarbonImmutableDateTimeMicrosecondsType.php
packages/EasyDoctrine/src/DBAL/Types/DateTimeImmutableMicrosecondsType.php
packages/EasyDoctrine/tests/DBAL/Types/CarbonImmutableDateTimeMicrosecondsTypeTest.php
packages/EasyDoctrine/tests/DBAL/Types/DateTimeImmutableMicrosecondsTypeTest.php

Currently out DBAL Type for `DateTime`'s doesn't take into account `TimeZone`'s.
As a result, `2022-01-01T10:00:00+09:00` will be processed in DB as `2022-01-01T10:00:00+00:00`. It affects `WHERE` conditions and stored values. 
New implementation is based on advice from [doctrine documentation](https://www.doctrine-project.org/projects/doctrine-orm/en/2.11/cookbook/working-with-datetime.html#:~:text=By%20default%20Doctrine%20assumes%20that,or%20by%20calling%20date_default_timezone_set()%20.). 
Changes may break BC in theory.  But in practice everything should be fine because we use UTC in our projects.

[EasyDoctrine] Fix timezone issue in CarbonImmutableDateTime

---

packages/EasySecurity/src/Bridge/Symfony/DependencyInjection/Compiler/RegisterSecurityContextPass.php

- Add deprecation for SecurityContextInterface autowiring usage

[EasySecurity] Add deprecation for SecurityContextInterface autowiring usage

---

packages/EasyHttpClient/composer.json
packages/EasyHttpClient/src/Bridge/EasyBugsnag/HttpRequestSentBreadcrumbListener.php
packages/EasyHttpClient/tests/AbstractTestCase.php
packages/EasyHttpClient/tests/Bridge/EasyBugsnag/HttpRequestSentBreadcrumbListenerTest.php
phpstan.neon

[EasyHttpClient] Limit the metadata size in the `HttpRequestSentBreadcrumbListener` listener

---

packages/EasyBugsnag/src/Bridge/Symfony/Worker/WorkerMessageReceivedListener.php

- Fixed datetime format for `Received At` on the Worker tab in BS

[EasyBugsnag] Fixed datetime format for `Received At` on the Worker tab in BS

---

packages/EasyCore/src/Bridge/Symfony/ApiPlatform/DataTransformer/AbstractInputDataTransformer.php

In some cases, we need to transform the API resource object.
This PR make a method and a variable name more generic.
This PR introduce BC, but it can be easy refactored.

[EasyCore] Make AbstractInputDataTransformer more generic

---

packages/EasyActivity/tests/Stubs/EntityManagerStub.php
packages/EasyDoctrine/tests/Stubs/EntityManagerStub.php
packages/EasyLock/src/Bridge/Symfony/Resources/config/services.php
packages/EasyLock/src/Bridge/Symfony/SchemaListener/EasyLockDoctrineSchemaSubscriber.php
packages/EasyLock/src/Bridge/Symfony/Subscribers/EasyLockDoctrineSchemaSubscriber.php
phpstan.neon

This PR adds the `lock_keys` table to schema configuration.
In this case, Doctrine automatically generates migration and tracks this table.

[EasyLock] Add schema configuration

---

packages/EasyUtils/src/Helpers/EnvVarSubstitutionHelper.php

[EasyUtils] Support non-string env vars in substitution helper

---

packages/EasyUtils/src/SensitiveData/StringSanitizers/JsonStringSanitizer.php
packages/EasyUtils/src/SensitiveData/StringSanitizers/UrlStringSanitizer.php
packages/EasyUtils/tests/AbstractSensitiveDataSanitizerTestCase.php

The `easy_utils.keys_to_mask` parameters contains keys in lower case. Therefore, parameters in mixed case are not masked in URL and JSON. 
For example, when we log an HTTP query with body `Action=Publish&Version=2010-03-31&PhoneNumber=%2B6100000000&Message=Your+code+to+change+the+email+address+is+567376.`, the `PhoneNumber` parameter is not masked.

[EasyUtils] `UrlStringSanitizer` and `JsonStringSanitizer` are sensitive to case

---

packages/EasyTest/src/Stub/HttpClient/HttpClientStub.php

Currently `\EonX\EasyTest\Stub\HttpClient\HttpClientStub` is a final class. So we can't extend it and create a custom Stub for some clients.

[EasyTest] Allow to extend `HttpClientStub`

---

packages/EasyTest/src/Stub/HttpClient/HttpClientAssertionTrait.php
packages/EasyTest/src/Traits/HttpClientAssertionTrait.php

* trait moved
HttpClientAssertionTrait moved to Traits folder

[EasyTest] hotfix/http-client-assertion-trait

---

packages/EasyDoctrine/src/Dispatchers/DeferredEntityEventDispatcher.php
packages/EasyDoctrine/tests/Stubs/EventDispatcherStub.php
packages/EasyDoctrine/tests/Subscribers/EntityEventSubscriberTest.php

When we call `EntityManager::flush` in a listener for `EntityActionEventInterface` infinite recursion occurs. 
We are trying to process the same `$this->entityChangeSets` each time.

[EasyDoctrine] Fix infinite recursion in the `DeferredEntityEventDispatcher`

---

packages/EasyTest/src/Traits/MessengerAssertionsTrait.php

Currently `MessengerAssertionsTrait::assertMessageSentToTransport` doesn't work correctly when a message contains value objects like `CarbonImmutable`.

[EasyTest] Fix `MessengerAssertionsTrait::assertMessageSentToTransport`

---

packages/EasyDoctrine/src/ORM/Decorators/EntityManagerDecorator.php

- Add wrapInTransaction method to EntityManagerDecorator.
- Deprecate `EntityManagerDecorator::transactional()`

[EasyDoctrine] ad wrapInTransaction method to EntityManagerDecorator

---

packages/EasyAsync/src/Bridge/Symfony/DependencyInjection/Compiler/RegisterMessengerMiddlewareCompilerPass.php
packages/EasyAsync/src/Bridge/Symfony/Messenger/DoctrineManagersCloseConnectionMiddleware.php
packages/EasyAsync/src/Doctrine/ManagersCloser.php
packages/EasyAsync/tests/Doctrine/ManagersCloserTest.php

Add DoctrineManagersCloseConnectionMiddleware to close entity manager connections every after a message is processed to save number of connections.
| Fixed tickets | -

[EasyAsync] Add DoctrineManagersCloseConnectionMiddleware

---

packages/EasyBatch/src/Bridge/Symfony/Messenger/Emergency/ProcessBatchForBatchItemHandler.php

[EasyBatch] Prevent running emergency logic on already completed batch

---

packages/EasyTest/src/Stub/HttpClient/HttpClientStub.php

In this PR we make `$baseUri` optional, so we don't need to provide Base URI in tests service configuration and can use relative URLs in tests.

[EasyTest ] Make baseUri optional

---

packages/EasySecurity/src/Bridge/EasyBugsnag/SecurityContextClientConfigurator.php
packages/EasySecurity/src/Bridge/Symfony/Security/FakeUser.php
packages/EasySecurity/src/Bridge/Symfony/Security/SecurityContextAuthenticator.php
packages/EasySecurity/src/Interfaces/UserInterface.php
packages/EasySecurity/tests/Bridge/Symfony/Security/FakeUserTest.php
packages/EasySecurity/tests/Stubs/UserInterfaceStub.php

Method `\EonX\EasySecurity\Interfaces\UserInterface::getUniqueId` looks confusing
- Symfony 6.0 uses only `\Symfony\Component\Security\Core\User\UserInterface::getUserIdentifier`.
- we duplicate `getUserIdentifier` and `getUniqueId` in apps.

[EasySecurity] Introduce getUserIdentifier and deprecate getUniqueId methods 

---

packages/EasyDoctrine/src/Subscribers/EntityEventSubscriber.php

Fix typehint in EntityEventSubscriber
In case the deferred dispatcher entity has a `OneToMany` `\Doctrine\Common\Collections\Collection` field and `cascade: ['persist']`, the argument can be `\Doctrine\ORM\PersistentCollection`.

[EasyDoctrine] Fix typehint in EntityEventSubscriber

---

packages/EasyDoctrine/src/Bridge/Symfony/Aws/Rds/AuthTokenConnectionFactory.php

Fixed the `getGeneratePasswordClosure` method in the `AuthTokenConnectionFactory` factory.

[EasyDoctrine] Fixed the `getGeneratePasswordClosure` method

---

packages/EasyErrorHandler/src/Bridge/Symfony/Listener/ExceptionEventListener.php

Without this call we get the 500 http status code in some conditions (`\Symfony\Component\HttpKernel\HttpKernel::handleThrowable`):

[EasyErrorHandler] Allowed custom response codes.

---

packages/EasySwoole/src/Bridge/BridgeConstantsInterface.php
packages/EasySwoole/src/Bridge/Symfony/DependencyInjection/Configuration.php
packages/EasySwoole/src/Bridge/Symfony/DependencyInjection/EasySwooleExtension.php
packages/EasySwoole/src/Bridge/Symfony/Listeners/AccessLogListener.php
packages/EasySwoole/src/Bridge/Symfony/Resources/config/access_log.php
packages/EasySwoole/tests/Bridge/Symfony/ConfigurationTest.php

This PR bring the ability to exclude specific paths from the access log.

[EasySwoole] Added the `do_not_log_paths` option to the configuration

---

packages/EasySecurity/src/Bridge/Symfony/Listeners/FromRequestSecurityContextConfiguratorListener.php

We should reset the security context and setup configurators only for the main request.

[EasySecurity] Add check isMainRequest

---

packages/EasyTest/src/Traits/ExceptionTrait.php
packages/EasyTest/src/Traits/MessengerAssertionsTrait.php

* error code is optional
Exception error code is optional. 
Two options to use in test:
Current:
`self::consumeAsyncMessages([[FilesystemException::class => 0]]);`
New one:
`self::consumeAsyncMessages([FilesystemException::class]);`
And we can check exceptions without code: 
`$this->assertThrownException(FileParsingException::class);`

[EasyTest] Make exception error code optional

---

packages/EasyDoctrine/src/Bridge/AwsRds/Iam/AuthTokenProvider.php

The OpenSwoole Table feature support keys up to 64 characters: https://github.com/search?q=repo%3Aopenswoole%2Fext-openswoole+SW_TABLE_KEY_SIZE&type=code.
Our current cache key in the `AuthTokenProvider` service looks like this `easy_doctrine.aws_rds.iam_auth_token.43dd0f66d9bb080c97698593e0cc3fde` (69 characters). Because of this we are getting the following error:
```
Warning: OpenSwoole\Table::set(): key[easy_doctrine.aws_rds.iam_auth_token.43dd0f66d9bb080c97698593e0cc3fde] is too long
```

[EasyDoctrine] Fix AuthTokenProvider.

---

packages/EasyErrorHandler/src/Bridge/Symfony/Builder/ApiPlatformValidationErrorResponseBuilder.php

- improved easy error handler
| Fixed tickets | #

[EasyErrorHandler] Validation exception instead of 500 when input data is misformatted

---

packages/EasyUtils/src/SensitiveData/StringSanitizers/JsonStringSanitizer.php
packages/EasyUtils/tests/AbstractSensitiveDataSanitizerTestCase.php

Sometimes we need to sanitize keys like `..."key":["foo", "bar"]...`  => `..."key":[*REDACTED*]...`
This PR makes it possible.

[EasyUtils] Improve JsonSanitizer: make it possible to sanitize array-type keys

---

packages/EasyErrorHandler/src/Bridge/Symfony/Builder/ApiPlatformValidationErrorResponseBuilder.php

Since version 6.3 Symfony is throwing MissingConstructorArgumentsException with its own message that a bit different from api-platform's message. 
So this PR fixes it.

[ErrorHandler] Add MissingConstructorArgumentsException Symfony's 6.3 exception message support

---

packages/EasyErrorHandler/src/Bridge/Symfony/Builder/ApiPlatformValidationErrorResponseBuilder.php

Huh,
`\explode('", "', $matches[2] ?? '')` can return an array with the empty line inside.

[ErrorHandler] hotfix for ApiPlatformValidationErrorResponseBuilder

---

packages/EasyActivity/tests/Fixtures/Article.php
packages/EasyActivity/tests/Fixtures/Comment.php
packages/EasyCore/src/Bridge/Symfony/ApiPlatform/Pagination/CustomPaginatorInterface.php
packages/EasyDoctrine/src/Subscribers/EntityEventSubscriber.php
packages/EasyDoctrine/tests/Fixtures/Price.php
packages/EasyDoctrine/tests/Fixtures/PriceType.php
packages/EasyDoctrine/tests/Fixtures/Product.php
packages/EasyDoctrine/tests/Stubs/EntityManagerStub.php
packages/EasyDoctrine/tests/Subscribers/EntityEventSubscriberTest.php

We need a way to compare objects when computing changesets

[Easy Doctrine] Use stringable interface to compare objects

---

packages/EasyActivity/tests/ActivityLogEntryFactoryResolversTest.php
packages/EasyActivity/tests/ActivityLogEntryFactoryTest.php
packages/EasyActivity/tests/Bridge/EasyDoctrine/EasyDoctrineEntityEventsSubscriberTest.php
packages/EasyActivity/tests/Bridge/Symfony/Serializers/CircularReferenceHandlerTest.php
packages/EasyActivity/tests/Bridge/Symfony/Serializers/SymfonyActivitySubjectDataSerializerTest.php
packages/EasyActivity/tests/Fixtures/Article.php
packages/EasyActivity/tests/Fixtures/Author.php
packages/EasyActivity/tests/Fixtures/Comment.php
packages/EasyDoctrine/src/Subscribers/EntityEventSubscriber.php

| Bug fix?      |no
The same https://github.com/eonx-com/easy-monorepo/pull/1178 but for 5.x branch

[EasyActivity] Compute changesets of collections

---

packages/EasyPagination/src/Traits/EloquentPaginatorTrait.php

- v3's fetching of results works `\iterator_to_array($queryBuilder->get()->getIterator());`
- v4's `\array_values($queryBuilder->get()->getDictionary());` returns incorrect result since in `getDictionary`, `$values->getKey()` is null thus returning a single value array[null] = last value of the result (older rows replaced).
| New feature?  |no 

[EasyPagination] Fix EloquentPaginatorTrait::fetchResult to use v3's way of fetching result

---

packages/EasySwoole/src/Helpers/OptionHelper.php

| Tests pass?   | yes   
- fix getOption() method
- add default value for `env_var_output_enabled` option

[EasySwoole] Fix getOption() method, add default value for `env_var_output_enabled` option

---

packages/EasySwoole/src/Helpers/OptionHelper.php

| Tests pass?   | yes   
- fix getOption() method
- add default value for `env_var_output_enabled` option

[EasySwoole] Fix getOption() method, add default value for env_var_output_enabled option

---

packages/EasySwoole/src/Bridge/Symfony/AppStateResetters/SymfonyServicesAppStateResetter.php

We have the following bug when we use the latest version of EasySwoole with EasyAdmin:
This bug was introduced in v4.3.21 (+4.3.22). To fix it we must reset the `form.choice_list_factory.cached` service at the end of each request.

[EasySwoole] Fixed "SymfonyServicesAppStateResetter"

---

packages/EasyErrorHandler/src/Builders/CodeErrorResponseBuilder.php

Unexpectedly some exceptions keep the error code as string. For example, `\PDOException` (https://www.php.net/manual/en/class.pdoexception.php#95812). Because of this we have to update the `CodeErrorResponseBuilder::doBuildValue` method to allow return `int` or `string`.

[EasyErrorHandler] Fixed `CodeErrorResponseBuilder`

---

packages/EasyApiPlatform/src/Normalizers/CarbonImmutableNormalizer.php

When denormalizing Api Resource Symfony guess type by Doctrine type, but when denormalizing DTO type guessed by field type.

[EasyApiPlatform] Fix `CarbonImmutableNormalizer` type detection issue

---

packages/EasyErrorHandler/src/Bridge/Symfony/Builder/ApiPlatformValidationErrorResponseBuilder.php

- Add `NotNormalizableValueException` exception support with the message pattern - `/The type of the "(\w+)" attribute must be "(\w+)", "(\w+)" given/`

[ErrorHanlder] Add additional exception to support validation error building

---

packages/EasyErrorHandler/src/Bridge/Symfony/Builder/ApiPlatformValidationErrorResponseBuilder.php

- Add `NotNormalizableValueException` exception support with the message pattern - `/The type of the "(\w+)" attribute must be "(\w+)", "(\w+)" given/`

[EasyErrorHandler] Add additional exception to support validation error building

---

packages/EasyTest/src/Traits/MessengerAssertionsTrait.php

[EasyTest] Updated `MessengerAssertionsTrait` to allow delays between worker runs

---

packages/EasyErrorHandler/src/Bridge/Symfony/Builder/ApiPlatformValidationErrorResponseBuilder.php

- added 500 error transformation when an ineligible entity iri passed

[EasyErrorHandler] Add TypeError case to ApiPlatformValidationErrorResponseBuilder

---

composer.json
packages/EasyApiPlatform/composer.json

[EasyApiPlatform] Limited the `api-platform/core` version to `3.1.x`

---

packages/EasyPagination/src/Traits/DoctrineCommonPaginatorTrait.php
packages/EasyPagination/src/Traits/EloquentPaginatorTrait.php

[EasyPagination] Do not apply GetItemsCriteria to primaryKey QueryBuilder

---

packages/EasySwoole/src/Bridge/Doctrine/Coroutine/PDO/PDOClientPool.php

[EasySwoole] Fix PDOClientPool::make() when exception triggered

---

packages/EasySwoole/src/Helpers/OptionHelper.php
packages/EasySwoole/tests/Helpers/OptionHelperTest.php

[EasySwoole] Fix OptionHelper::getArray()

---

packages/EasyTest/src/Stub/HttpClient/HttpClientStub.php

Implementation of the `willThrowException` method of the `HttpClientStub` stub is bad. By using the `willThrowException` method the stub throws an exception while we instantiate a response object. It's wrong because at this point there is no actual request is made. To emulate an exception we have to use the `forRequest` - `addResponse` methods call chain. For example:
```php
...
->forRequest(Request::METHOD_GET, 'http://example.test/users')
->addResponse([], ['http_code' => 500]);
```

[EasyTest] Deprecate the "willThrowException" method of the "HttpClientStub" stub

---

packages/EasyErrorHandler/src/Bridge/Bugsnag/Resolvers/DefaultBugsnagIgnoreExceptionsResolver.php
packages/EasyErrorHandler/src/ErrorLogLevelResolver.php
packages/EasyErrorHandler/tests/ErrorLogLevelResolverTest.php

Updates the `ErrorLogLevelResolver` resolver by adding the `RequestExceptionInterface` interface to the `exceptionLogLevels` list.

[EasyErrorHandler] Updates the `ErrorLogLevelResolver` resolver

---

packages/EasyActivity/src/Bridge/Symfony/Messenger/ActivityLogEntryMessageHandler.php
packages/EasyBatch/src/Bridge/Symfony/Messenger/Emergency/ProcessBatchForBatchItemHandler.php
packages/EasyBatch/src/Bridge/Symfony/Messenger/Emergency/UpdateBatchItemHandler.php
packages/EasyWebhook/src/Bridge/Symfony/Messenger/SendWebhookHandler.php

Use AsMessageHandler attribute instead of implementing the deprecated MessageHandlerInterface

[Monorepo] Use AsMessageHandler attribute

---

packages/EasyUtils/src/Bridge/Symfony/Normalizers/IntegerNumberNormalizer.php
packages/EasyUtils/src/Bridge/Symfony/Normalizers/TrimStringsNormalizer.php

Update TrimStringsNormalizer and IntegerNumberNormalizer to implement getSupportedTypes method

[Monorepo] Fix normalizers deprecations

---

packages/EasyUtils/src/CreditCard/CreditCardNumberValidator.php
packages/EasyUtils/tests/AbstractSensitiveDataSanitizerTestCase.php

| New feature?  | kind of
Sometimes in the \EonX\EasyUtils\SensitiveData\StringSanitizers\CreditCardNumberStringSanitizer::sanitizeString method, the pan validator can decide that some sequence of digits is a valid pan. To avoid this let's check it by the Luhn  algorithm

[EasyUtils] Add Luhn validation to CreditCardNumberValidator

---

packages/EasyEncryption/src/AwsPkcs11Encryptor.php
packages/EasyEncryption/src/Interfaces/AwsPkcs11EncryptorInterface.php

[EasyEncryption] Fixes some bugs in `AwsPkcs11Encryptor`

---

composer.json
packages/EasyEncryption/src/AwsPkcs11Encryptor.php
packages/EasyEncryption/src/Interfaces/AwsPkcs11EncryptorInterface.php

[EasyEncryption] Added the `sign` method to the `AwsPkcs11Encryptor` encryptor.

[EasyEncryption] Added the `sign` method to AwsPkcs11Encryptor

---

packages/EasyLogging/src/Bridge/BridgeConstantsInterface.php
packages/EasyLogging/src/Bridge/Symfony/EasyLoggingSymfonyBundle.php
packages/EasyLogging/src/Bridge/Symfony/Resources/config/services.php
packages/EasyLogging/src/LoggerFactory.php

Using logger class parameter in the LoggerFactory make configuring LoggerStub much more easier

[EasyLogging] Return parametrised loggerClass argument in the LoggerFactory

---

packages/EasyErrorHandler/src/Bridge/BridgeConstantsInterface.php
packages/EasyErrorHandler/src/Bridge/Laravel/Provider/EasyErrorHandlerServiceProvider.php
packages/EasyErrorHandler/src/Bridge/Laravel/config/easy-error-handler.php
packages/EasyErrorHandler/src/Bridge/Symfony/EasyErrorHandlerSymfonyBundle.php
packages/EasyErrorHandler/src/Bridge/Symfony/Resources/config/definition.php
packages/EasyErrorHandler/src/Bridge/Symfony/Resources/config/services.php
packages/EasyErrorHandler/src/ErrorHandler.php
packages/EasyErrorHandler/tests/ErrorHandlerTest.php

Sometimes the exception may be reported twice. This PR is a solution for this case.

[EasyErrorHandler] Skip already reported exceptions

---

composer.json

It is better to have red CI than abandoned deps.

[Monorepo] Fail security check if package abandoned

---

packages/EasySwoole/src/Bridge/Doctrine/Coroutine/PDO/CoroutineConnectionFactory.php

This fixes excessive DB migrations creation when using swoole coroutines and our custom `\EonX\EasyDoctrine\DBAL\Types\JsonbType` for some entities columns.
When coroutines are enabled, mapped types are not injected into the connection.

[EasySwoole] fixed mapping types initialization

---

packages/EasyEncryption/src/Configurator/AwsCloudHsmSdkConfigurator.php

[EasyEncryption] Make the `--server-client-cert-file` and the `--server-client-key-file` options optional in the `AwsCloudHsmSdkConfigurator` service.

[EasyEncryption] Fix an issue in the `AwsCloudHsmSdkConfigurator` service

---

packages/EasyWebhook/src/Common/Exception/WebhookRequestFailedException.php
packages/EasyWebhook/src/Common/Middleware/SendWebhookMiddleware.php

We can add this exception to ignored exceptions list for the Bugsnag then in example

[EasyWebhook] Add WebhookRequestFailedException

---

packages/EasyErrorHandler/src/ApiPlatform/Builder/ApiPlatformValidationErrorResponseBuilder.php
packages/EasyErrorHandler/src/ApiPlatform/Builder/ApiPlatformValidationExceptionErrorResponseBuilder.php
packages/EasyErrorHandler/src/Common/Builder/AbstractErrorResponseBuilder.php
packages/EasyErrorHandler/src/Common/Builder/ErrorResponseBuilderInterface.php
packages/EasyErrorHandler/src/Common/Builder/HttpExceptionErrorResponseBuilder.php
packages/EasyErrorHandler/src/Common/Builder/StatusCodeErrorResponseBuilder.php
packages/EasyErrorHandler/src/Common/Exception/BadRequestException.php
packages/EasyErrorHandler/src/Common/Exception/BaseException.php
packages/EasyErrorHandler/src/Common/Exception/ConflictException.php
packages/EasyErrorHandler/src/Common/Exception/ForbiddenException.php
packages/EasyErrorHandler/src/Common/Exception/NotFoundException.php
packages/EasyErrorHandler/src/Common/Exception/StatusCodeAwareExceptionInterface.php
packages/EasyErrorHandler/src/Common/Exception/StatusCodeAwareExceptionTrait.php
packages/EasyErrorHandler/src/Common/Exception/SubCodeAwareExceptionTrait.php
packages/EasyErrorHandler/src/Common/Exception/UnauthorizedException.php
packages/EasyErrorHandler/src/Common/Factory/ErrorResponseFactory.php
packages/EasyErrorHandler/src/Common/Factory/SymfonySerializerErrorResponseFactory.php
packages/EasyErrorHandler/src/Common/Resolver/ErrorDetailsResolver.php
packages/EasyErrorHandler/src/Common/ValueObject/ErrorResponseData.php
packages/EasyErrorHandler/src/Common/ValueObject/ErrorResponseDataInterface.php
packages/EasyErrorHandler/tests/Fixture/app/src/Enum/ErrorCode.php
packages/EasyErrorHandler/tests/Unit/src/Common/Builder/TestRenderWithDefaultBuildersDataProvider.php
packages/EasyErrorHandler/tests/Unit/src/Common/Exception/BaseExceptionTest.php
packages/EasyUtils/src/Common/Enum/HttpStatusCode.php

| Fixed tickets | https://eonx.atlassian.net/browse/MTCE-251

[EasyErrorHandler] Use enums as exception's `code`, `subCode` and `statusCode`

---

packages/EasyApiToken/src/Auth0/Driver/Auth0JwtDriver.php
packages/EasyApiToken/src/AwsCognito/Driver/AwsCognitoJwtDriver.php
packages/EasyApiToken/src/AwsCognito/Provider/AwsCognitoJwkProvider.php
packages/EasyApiToken/src/AwsCognito/ValueObject/UserPoolConfig.php
packages/EasyApiToken/src/Common/Decoder/AbstractDecoder.php
packages/EasyApiToken/src/Common/Decoder/BearerTokenDecoder.php
packages/EasyApiToken/src/Common/Decoder/ChainDecoder.php
packages/EasyApiToken/src/Common/Driver/HashedApiKeyDriver.php
packages/EasyApiToken/src/Common/Factory/ApiTokenDecoderFactory.php
packages/EasyApiToken/src/Common/Generator/TokenGenerator.php
packages/EasyApiToken/src/Common/ValueObject/ApiKey.php
packages/EasyApiToken/src/Common/ValueObject/BasicAuth.php
packages/EasyApiToken/src/Common/ValueObject/HashedApiKey.php
packages/EasyApiToken/src/Common/ValueObject/HashedApiKeyInterface.php
packages/EasyApiToken/src/Common/ValueObject/Jwt.php

[EasyApiToken] Modernize the code

---

packages/EasyRequestId/bundle/config/definition.php
packages/EasyRequestId/laravel/EasyRequestIdServiceProvider.php
packages/EasyRequestId/laravel/config/easy-request-id.php
packages/EasyRequestId/src/Common/Provider/RequestIdProvider.php
packages/EasyRequestId/src/Common/Provider/RequestIdProviderInterface.php
packages/EasyRequestId/src/Common/Resolver/FromArrayResolver.php
packages/EasyRequestId/src/Common/Resolver/HttpFoundationRequestResolver.php
packages/EasyRequestId/src/Common/Resolver/ResolverInterface.php
packages/EasyRequestId/src/Common/ValueObject/RequestIdInfo.php
packages/EasyRequestId/src/Messenger/Resolver/MessengerMessageResolver.php
packages/EasyRequestId/tests/Unit/src/Common/Provider/RequestIdProviderTest.php

[EasyRequestId] Monorepo v6: modernize the code by using latest PHP features

---

packages/EasyTest/src/Stub/HttpClient/HttpClientStub.php

[EasyTest] Make HttpClientStub::forRequest(queryParams) work correctly with an array type of value

---

packages/EasyTest/src/Traits/MessengerAssertionsTrait.php

[EasyTest] Fix MessengerAssertionsTrait::consumeAsyncMessages() annotation

---

packages/EasyTest/src/Traits/MessengerAssertionsTrait.php

[EasyTest] Allow to use multiple transports in the consumeAsyncMessages call

---

packages/EasyTest/composer.json
packages/EasyTest/src/HttpClient/Response/StrictTestResponse.php
packages/EasyTest/tests/Unit/src/HttpClient/Response/StrictTestResponseTest.php

[EasyTest] Fix an infinite loop in StrictTestResponse

---

packages/EasyErrorHandler/bundle/CompilerPass/RegisterTraceableErrorHandlerCompilerPass.php
packages/EasyErrorHandler/src/Common/ErrorHandler/TraceableErrorHandlerInterface.php
packages/EasyTest/docs/arrange_http_client.md
packages/EasyTest/src/EasyErrorHandler/Common/Trait/EasyErrorHandlerAssertionTrait.php
packages/EasyTest/src/EasyErrorHandler/ErrorHandler/TraceableErrorHandlerStub.php
packages/EasyTest/src/EasyErrorHandler/Trait/EasyErrorHandlerAssertionTrait.php
packages/EasyTest/src/PHPUnit/Extension/EasyTestExtension.php
packages/EasyTest/src/PHPUnit/Subscriber/EasyErrorHandlerTestFailedSubscriber.php
packages/EasyTest/src/PHPUnit/Subscriber/EasyErrorHandlerTestFinishedSubscriber.php
packages/EasyTest/src/PHPUnit/Subscriber/HttpClientTestFailedSubscriber.php
quality/tests/Architecture/Common/NoForbiddenDirNameTest.php

[Monorepo] Improve EasyErrorHandler testing tools

---

packages/EasyErrorHandler/src/Bugsnag/Provider/BugsnagErrorReporterProvider.php
packages/EasyErrorHandler/tests/Fixture/app/config/bundles.php
packages/EasyErrorHandler/tests/Fixture/app/config/packages/with_easy_bugsnag/easy_bugsnag.php
packages/EasyErrorHandler/tests/Fixture/app/config/packages/with_easy_bugsnag/easy_error_handler.php
packages/EasyErrorHandler/tests/Unit/bundle/EasyErrorHandlerBundleTest.php

| Fixed tickets | https://eonx.atlassian.net/browse/MTCE-321

[EasyErrorHandler] Type mismatch in EasyErrorHandler config and BugsnagErrorReporterProvider

---

packages/EasyApiPlatform/src/Common/SerializerContextBuilder/SerializerContextBuilder.php

Fix `lint:container` error:
```
Invalid alias definition: alias "ApiPlatform\Serializer\SerializerContextBu  
ilderInterface" is referencing class "EonX\EasyApiPlatform\Common\Serialize  
rContextBuilder\SerializerContextBuilder" but this class does not implement  
"ApiPlatform\Serializer\SerializerContextBuilderInterface". Because this a  
lias is an interface, "EonX\EasyApiPlatform\Common\SerializerContextBuilder  
\SerializerContextBuilder" must implement "ApiPlatform\Serializer\Serialize  
rContextBuilderInterface".   
```
https://github.com/api-platform/core/issues/6411
https://github.com/api-platform/core/pull/6412/files

[EasyApiPlatform] Fix serializer context builder interface usage

---

packages/EasyTest/src/HttpClient/Response/AbstractTestResponse.php
packages/EasyTest/tests/Unit/src/HttpClient/Response/StrictTestResponseTest.php

To fix warnings in tests, array to string converstion.

[EasyTest] Fix AbstactTestResponse data normalization

---

packages/EasyDoctrine/bundle/config/deferred_dispatcher.php

[EasyDoctrine] Do not decorate WithEventsEntityManager when default EM not exists

---

packages/EasyTest/src/PHPUnit/Subscriber/HttpClientTestFailedSubscriber.php

It was found out that PHPUnit catches all exceptions thrown in subscribers.

[EasyTest] Fix http client stub debug output

---

packages/EasyErrorHandler/src/Common/ErrorHandler/ErrorHandler.php
packages/EasyErrorHandler/tests/Stub/Client/BugsnagClientStub.php
packages/EasyErrorHandler/tests/Unit/src/Common/ErrorHandler/ErrorHandlerTest.php
quality/phpstan.neon

Rollback changes from monorepo 5.x

[EasyErrorHandler] Rollback error-handler UnrecoverableMessageInterface check

---

packages/EasyNotification/composer.json
packages/EasyNotification/src/Queue/SqsQueueTransport.php
packages/EasyNotification/tests/NotificationClientTest.php
packages/EasyNotification/tests/Queue/SqsQueueTransportTest.php

| Fixed tickets | [PNM-685](https://eonx.atlassian.net/browse/PNM-685)  
[PNM-685]: https://eonx.atlassian.net/browse/PNM-685?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[EasyNotification] Update SqsQueueTransport.php to handle FIFO queues

---

packages/EasyUtils/src/Common/Normalizer/CarbonImmutableNormalizer.php
packages/EasyUtils/tests/Unit/src/Common/Normalizer/CarbonImmutableNormalizerTest.php

Change type to `DateTimeInterface` to instantiate objects using `DateTimeImmutable` class

[EasyUtils] Change type for carbon immutable denormalization.

---

composer.json
packages/EasyErrorHandler/bundle/CompilerPass/RegisterTraceableErrorHandlerCompilerPass.php
packages/EasyTest/bundle/CompilerPass/RegisterTraceableErrorHandlerStubCompilerPass.php
packages/EasyTest/bundle/EasyTestBundle.php
packages/EasyTest/composer.json
packages/EasyTest/src/EasyErrorHandler/Trait/EasyErrorHandlerAssertionTrait.php

We use `\PHPUnit\Framework\Attributes\After` to automatically check reported errors.
With `After `, our methods called after test `tearDown`, which always resets the container.
We need to use `TraceableErrorHandlerStub` as it stores reported errors in static property to not depend on the container.

[EasyTest] Create EasyTestBundle

---

packages/EasyServerless/bundle/CompilerPass/SymfonyServicesResetCompilerPass.php

[EasyServerless] Make SymfonyServicesAppStateResetter to be public

---

composer.json
packages/EasyApiPlatform/composer.json
packages/EasyApiPlatform/tests/Application/src/EasyErrorHandler/Provider/ApiPlatformErrorResponseBuilderProviderTest.php
packages/EasyApiPlatform/tests/Fixture/app/src/EasyErrorHandler/ApiResource/Payment.php
packages/EasyApiPlatform/tests/Fixture/app/src/EasyErrorHandler/StateProvider/PaymentStateProvider.php

[EasyApiPlatform] EasyErrorHandler now cares about the IRI with an invalid UUID passed in the request payload
