eonx-com/easy-monorepo

composer.json
packages/EasyRepository/composer.json
packages/EasyRepository/src/Implementations/Illuminate/AbstractEloquentRepository.php
packages/EasyRepository/tests/Implementation/Illuminate/AbstractEloquentRepositoryTest.php
packages/EasyRepository/tests/Implementation/Illuminate/EloquentRepositoryStub.php

Add Illuminate Eloquent abstract repository

[EasyRepository] Add Illuminate Eloquent abstract repository.

---

packages/EasyPipeline/src/Bridge/Laravel/EasyIlluminatePipelineServiceProvider.php
packages/EasyPipeline/tests/Bridge/Laravel/EasyPipelineProviderTest.php

[EasyPipeline] Update service provider to publish and merge config

---

packages/EasyRepository/src/Implementations/Illuminate/AbstractEloquentRepository.php
packages/EasyRepository/tests/Implementation/Illuminate/AbstractEloquentRepositoryTest.php
packages/EasyRepository/tests/Implementation/Illuminate/EloquentRepositoryStub.php

EloquentRepository returns a collection and was throwing a type error.

Return an array from EloquentRepository

---

packages/EasyDecision/tests/Decisions/DecisionWithExpressionLanguageTest.php
packages/EasyRepository/src/Implementations/Doctrine/ORM/AbstractDoctrineOrmRepository.php
packages/EasyRepository/src/Implementations/Doctrine/ORM/DoctrineOrmRepositoryTrait.php

Creating this trait will allow people using the DoctrineBundle ServiceEntityRepository to enjoy the built-in implementation.

[EasyRepository] Trait for DoctrineOrmRepository

---

composer.json
packages/EasyApiToken/composer.json

Bump eoneopay/utils to 0.2

---

packages/EasyIdentity/src/Traits/IdentityUserTrait.php

Create a trait to allow quick implementation of identity user.

[EasyIdentity] Make simple implementation easier

---

composer.json
packages/EasyPsr7Factory/.gitignore
packages/EasyPsr7Factory/composer.json
packages/EasyPsr7Factory/src/Bridge/Laravel/EasyPsr7FactoryServiceProvider.php
packages/EasyPsr7Factory/src/Bridge/Symfony/DependencyInjection/EasyPsr7FactoryExtension.php
packages/EasyPsr7Factory/src/Bridge/Symfony/EasyPsr7FactoryBundle.php
packages/EasyPsr7Factory/src/Bridge/Symfony/Resources/config/services.xml
packages/EasyPsr7Factory/tests/AbstractTestCase.php
packages/EasyPsr7Factory/tests/Bridge/Laravel/EasyPsr7FactoryServiceProviderTest.php
packages/EasyPsr7Factory/tests/Bridge/Symfony/EasyPsr7FactoryBundleTest.php
packages/EasyPsr7Factory/tests/Bridge/Symfony/Stubs/KernelStub.php
packages/EasyPsr7Factory/tests/Bridge/Symfony/Stubs/ServiceStub.php

[EasyPsr7Factory] Create Symfony bundle

---

packages/EasyApiToken/.gitignore
packages/EasyApiToken/src/Bridge/Symfony/DependencyInjection/EasyApiTokenExtension.php
packages/EasyApiToken/src/Bridge/Symfony/EasyApiTokenBundle.php
packages/EasyApiToken/src/Bridge/Symfony/Resources/config/services.xml
packages/EasyApiToken/tests/Bridge/Symfony/EasyApiTokenBundleTest.php
packages/EasyApiToken/tests/Bridge/Symfony/Stubs/KernelStub.php
packages/EasyApiToken/tests/Bridge/Symfony/Stubs/ServiceStub.php
packages/EasyApiToken/tests/Bridge/Symfony/Stubs/config.yaml

[EasyApiToken] Create Symfony bundle

---

packages/EasyCfhighlander/tests/Console/Commands/CloudFormationCommandTest.php
packages/EasyDecision/src/Decisions/AbstractDecision.php
packages/EasyDecision/src/Decisions/ValueDecision.php
packages/EasyDecision/src/Expressions/ExpressionFunction.php
packages/EasyDecision/src/Expressions/ExpressionFunctionFactory.php
packages/EasyDecision/src/Expressions/ExpressionLanguage.php
packages/EasyDecision/src/Helpers/FromPhpExpressionFunctionProvider.php
packages/EasyDecision/src/Helpers/IfConditionForValue.php
packages/EasyDecision/src/Helpers/ValueExpressionFunctionProvider.php
packages/EasyDecision/src/Interfaces/Expressions/ExpressionFunctionInterface.php
packages/EasyDecision/src/Interfaces/Expressions/ExpressionLanguageInterface.php
packages/EasyDecision/src/Middleware/ValueMiddleware.php
packages/EasyDecision/src/Rules/ExpressionLanguageRule.php
packages/EasyDecision/tests/Decisions/DecisionWithExpressionLanguageTest.php
packages/EasyDecision/tests/Decisions/ValueDecisionTest.php
packages/EasyDecision/tests/Expressions/ExpressionLanguageTest.php

[EasyDecision] Improve expression language implementation

---

packages/EasyDecision/src/Decisions/AbstractDecision.php
packages/EasyDecision/src/Decisions/AffirmativeDecision.php
packages/EasyDecision/src/Decisions/ConsensusDecision.php
packages/EasyDecision/src/Decisions/UnanimousDecision.php
packages/EasyDecision/src/Decisions/ValueDecision.php

[EasyDecision] Delegate middleware class definition to concrete decision

---

packages/EasyCfhighlander/config/services.yaml
packages/EasyCfhighlander/src/Console/Commands/AbstractTemplatesCommand.php
packages/EasyCfhighlander/src/File/FileGenerator.php
packages/EasyCfhighlander/src/File/FileStatus.php
packages/EasyCfhighlander/src/File/FileToGenerate.php
packages/EasyCfhighlander/src/File/ManifestGenerator.php
packages/EasyCfhighlander/src/Interfaces/FileGeneratorInterface.php
packages/EasyCfhighlander/src/Interfaces/ManifestGeneratorInterface.php
packages/EasyCfhighlander/src/Interfaces/ParameterResolverInterface.php
packages/EasyCfhighlander/src/Parameters/ParameterResolver.php
packages/EasyCfhighlander/tests/Console/Commands/CodeCommandTest.php

[EasyCfhighlander] Implement status and manifest concept

---

packages/EasyDocker/docs/index.md
packages/EasyDocker/readme.md

[EasyDocker] Add simple documentation

---

packages/EasyCfhighlander/docs/index.md
packages/EasyCfhighlander/readme.md

[EasyCfhighlander] Add simple documentation

---

packages/EasyDocker/templates/docker-compose.yml.twig
packages/EasyDocker/templates/docker/api/Dockerfile.twig
packages/EasyDocker/templates/docker/api/fpm.conf.twig
packages/EasyDocker/tests/Console/Commands/DockerFilesGeneratorCommandTest.php

[EasyDocker] Improve docker files templates

---

packages/EasyDocker/templates/docker-compose.dev.yml.twig
packages/EasyDocker/templates/docker/nginx/Dockerfile.twig

[EasyDocker] Nginx conf file and migrate container dependencies

---

packages/EasyDocker/config/parameters.yaml
packages/EasyDocker/src/Console/Commands/AbstractTemplatesCommand.php
packages/EasyDocker/src/Console/EasyDockerApplication.php
packages/EasyDocker/templates/docker-compose.yml.twig
packages/EasyDocker/templates/docker/api/Dockerfile.twig
packages/EasyDocker/templates/docker/api/cron.sh.twig
packages/EasyDocker/templates/docker/api/cron/crontab.twig
packages/EasyDocker/templates/docker/api/migrate.sh.twig
packages/EasyDocker/templates/docker/api/startup.sh.twig
packages/EasyDocker/templates/docker/nginx/Dockerfile.twig

add parameter for soap
add parameter for newrelic
update cron user permissions

[EasyDocker] Update cron user permissions to fix logging

---

packages/EasyDocker/templates/docker/api/Dockerfile.twig

[Easy-Docker] fix bug with newrelic skip

---

packages/EasyCfhighlander/src/Parameters/ParameterResolver.php
packages/EasyDocker/src/Parameters/ParameterResolver.php

Improve CLIs params cache

---

packages/EasyCfhighlander/src/File/FileGenerator.php
packages/EasyCfhighlander/src/Parameters/ParameterResolver.php

[EasyCfhighlander]Fix files permissions and cached params

---

packages/EasyDocker/src/Console/Commands/AbstractTemplatesCommand.php
packages/EasyDocker/src/File/FileGenerator.php
packages/EasyDocker/src/Parameters/ParameterResolver.php

[EasyDocker] Fix generated files permissions + cached params

---

packages/EasyDocker/src/File/ManifestGenerator.php

[EasyDocker] Remove cwd from filename in manifest

---

packages/EasyDocker/src/Console/EasyDockerApplication.php
packages/EasyDocker/templates/docker-compose.yml.twig

[EasyDocker] Fix cron permissions + query string in nginx + queue driver to redis

---

packages/EasyCfhighlander/templates/code/Jenkinsfile.twig
packages/EasyCfhighlander/templates/code/project-schema.cfhighlander.rb.twig
packages/EasyCfhighlander/templates/code/project-schema.config.yaml.twig
packages/EasyCfhighlander/templates/code/project.cfhighlander.rb.twig
packages/EasyCfhighlander/templates/code/project.config.yaml.twig

[EasyCfhighlander] Update code templates to latest (Fargate, ecs, ...)

---

packages/EasyCfhighlander/src/Console/Commands/AbstractTemplatesCommand.php
packages/EasyCfhighlander/src/Interfaces/ParameterResolverInterface.php
packages/EasyCfhighlander/src/Parameters/ParameterResolver.php
packages/EasyCfhighlander/tests/Console/Commands/CloudFormationCommandTest.php
packages/EasyCfhighlander/tests/Console/Commands/CodeCommandTest.php
packages/EasyDocker/config/parameters.yaml
packages/EasyDocker/src/Console/Commands/AbstractTemplatesCommand.php
packages/EasyDocker/templates/docker/api/migrate.sh.twig

[EasyCfhighlander] Better parameters resolvers

---

packages/EasyDocker/templates/docker-compose.dev.yml.twig
packages/EasyDocker/templates/docker-compose.local.yml.twig
packages/EasyDocker/templates/docker-compose.yml.twig
packages/EasyDocker/templates/docker/d.sh.twig
packages/EasyDocker/templates/docker/da.sh.twig
packages/EasyDocker/templates/docker/dc.sh.twig
packages/EasyDocker/templates/docker/dm.sh.twig
packages/EasyDocker/templates/docker/nginx/default.conf.twig

| Tests pass?   | no
| Fixed tickets | no
Sup pagey

[EasyDocker] nginx improvements

---

packages/EasyDocker/src/Console/Commands/AbstractTemplatesCommand.php
packages/EasyDocker/src/Interfaces/ParameterResolverInterface.php
packages/EasyDocker/src/Parameters/ParameterResolver.php

[EasyDocker] Better parameter resolvers

---

packages/EasyDecision/src/Bridge/Laravel/DecisionFactoryInterface.php
packages/EasyDecision/src/Bridge/Laravel/LaravelDecisionFactory.php
packages/EasyDecision/src/Decisions/DecisionFactory.php
packages/EasyDecision/src/Interfaces/DecisionFactoryInterface.php
packages/EasyDecision/src/Interfaces/RuleProviderInterface.php
packages/EasyDecision/tests/Stubs/RuleProviderStub.php

[EasyDecision] Allow additional parameters when creating decision

---

packages/EasyDocker/templates/docker-compose.local.yml.twig
packages/EasyDocker/templates/docker/api/cron-entrypoint.sh.twig
packages/EasyDocker/templates/docker/nginx/default-local.conf.twig
packages/EasyDocker/templates/docker/nginx/default.conf.twig

[EasyDocker] Update templates to work with FARGATE

---

packages/EasyCfhighlander/templates/cloudformation/Jenkinsfile.twig
packages/EasyCfhighlander/templates/cloudformation/project.cfhighlander.rb.twig
packages/EasyCfhighlander/templates/cloudformation/project.mappings.yaml.twig
packages/EasyCfhighlander/templates/cloudformation/redis.config.yaml.twig
packages/EasyCfhighlander/templates/cloudformation/sqs.config.yaml.twig
packages/EasyCfhighlander/templates/code/project.cfhighlander.rb.twig
packages/EasyCfhighlander/templates/code/project.config.yaml.twig

[EasyCfhighlander] Update templates to work with FARGATE

---

packages/EasyDocker/templates/docker/api/migrate.sh.twig
packages/EasyDocker/templates/docker/api/startup.sh.twig

[EasyDocker] Change sh to bash

---

packages/EasyDocker/templates/docker/api/migrate.sh.twig

[EasyDocker] Remove double brackets in migrate.sh

---

packages/EasyCfhighlander/templates/code/project.cfhighlander.rb.twig
packages/EasyCfhighlander/templates/code/project.config.yaml.twig

[EasyCfhighlander] Fix templates whitespace + nginx ports for FARGATE

---

packages/EasyCfhighlander/templates/code/project-schema.cfhighlander.rb.twig
packages/EasyCfhighlander/templates/code/project-schema.config.yaml.twig
packages/EasyCfhighlander/templates/code/project.cfhighlander.rb.twig
packages/EasyCfhighlander/templates/code/project.config.yaml.twig

[EasyCfhighlander] Added comments to template cfhighlander files to explain file purpose

---

packages/EasyDocker/src/Console/Commands/AbstractTemplatesCommand.php
packages/EasyDocker/templates/docker/api/Dockerfile.twig
packages/EasyDocker/tests/Console/Commands/DockerFilesGeneratorCommandTest.php

Optional support for https://github.com/hirak/prestissimo in api Dockerfile
Useful for speeding up application composer install
Disabled interactions, showing progress & suggestions for composer install
Tests to ensure prestissimo is used appropiately in Dockerfile

[EasyDocker] Support for hirak/prestissimo in api Dockerfile

---

packages/EasyCfhighlander/templates/code/project.config.yaml.twig

[EasyCfhighlander] Update ELASTICSEARCH_HOST to append https:// to $ElasticSearchHost

---

packages/EasyIdentity/src/Implementations/Auth0/Auth0IdentityServiceFactory.php
packages/EasyIdentity/tests/Implementations/Auth0/Auth0IdentityServiceFactoryTest.php

Ticket https://loyaltycorp.atlassian.net/browse/PYMT-1020

[EasyIdentity] Avoid exceptions when empty URL for Auth0

---

packages/EasyDocker/templates/docker/api/Dockerfile.twig
packages/EasyDocker/templates/docker/api/composer-installer.sh.twig

[EasyDocker] Check composer install with official signature

---

packages/EasyCfhighlander/bin/autoload.php

[EasyCfhighlander] Fix autoload paths issue

---

packages/EasyDocker/bin/autoload.php

[EasyDocker] Fix autoload paths issue

---

packages/EasyDocker/src/File/FileGenerator.php

[EasyDocker] Fix file overwrite issue

---

packages/EasyCfhighlander/src/File/FileGenerator.php

[EasyCfhighlander] Fix file overwrite issue

---

packages/EasyCfhighlander/src/Parameters/ParameterResolver.php
packages/EasyDocker/src/Parameters/ParameterResolver.php

[EasyDocker] Fix CLI params missing

---

packages/EasyRepository/src/Implementations/Doctrine/ORM/AbstractDoctrineOrmRepository.php
packages/EasyRepository/src/Implementations/Doctrine/ORM/DoctrineOrmRepositoryTrait.php
packages/EasyRepository/src/Implementations/Illuminate/AbstractEloquentRepository.php
packages/EasyRepository/src/Interfaces/DatabaseRepositoryInterface.php

[EasyRepository] Database repository interface

---

packages/EasyCfhighlander/config/parameters.yaml
packages/EasyCfhighlander/src/Console/Commands/AbstractTemplatesCommand.php
packages/EasyCfhighlander/src/Parameters/ParameterResolver.php
packages/EasyCfhighlander/templates/cloudformation/Jenkinsfile.twig
packages/EasyCfhighlander/templates/cloudformation/ecs.config.yaml.twig
packages/EasyCfhighlander/templates/cloudformation/project.cfhighlander.rb.twig
packages/EasyCfhighlander/templates/cloudformation/project.mappings.yaml.twig
packages/EasyCfhighlander/templates/code/Jenkinsfile.twig
packages/EasyCfhighlander/templates/code/project.cfhighlander.rb.twig
packages/EasyCfhighlander/templates/code/project.config.yaml.twig

[EasyCfhighlander] Sync template + CLI service

---

packages/EasyDocker/src/Parameters/ParameterResolver.php

[EasyDocker] Make sure to use cached params first

---

packages/EasyCfhighlander/templates/cloudformation/Jenkinsfile.twig

[EasyCfhighlander] Pass ecs params to cloudformation only when cli enabled

---

packages/EasyCfhighlander/templates/cloudformation/project.cfhighlander.rb.twig

[EasyCfhighlander] Use aurora 2.0.4 because the semver syntax is broken

---

packages/EasyCfhighlander/templates/code/project.config.yaml.twig

[EasyCfhighlander] Fix indent in project.config.yaml for code templates

---

packages/EasyApiToken/src/External/Auth0/Interfaces/TokenGeneratorInterface.php
packages/EasyApiToken/src/External/Auth0/TokenGenerator.php
packages/EasyApiToken/src/External/Auth0JwtDriver.php
packages/EasyApiToken/tests/Encoders/Auth0JwtTokenEncoderTest.php

| Fixed tickets | [PYMT-1157](https://loyaltycorp.atlassian.net/browse/PYMT-1157)
This PR allows the token to be generated with a custom claim for roles.

[EasyApiToken] Update Auth0JwtDriver to accept roles custom claim

---

packages/EasyDecision/src/Decisions/AbstractDecision.php
packages/EasyDecision/src/Interfaces/NonBlockingRuleErrorInterface.php
packages/EasyDecision/tests/Decisions/ValueDecisionTest.php
packages/EasyDecision/tests/Stubs/RuleWithNonBlockingErrorStub.php

[EasyDecision] Add non blocking error handling

---

packages/EasyDecision/src/Decisions/ValueDecision.php
packages/EasyDecision/tests/Decisions/ValueDecisionTest.php

[EasyDecision] Make sure value decision always return at least the input value

---

packages/EasyDocker/config/parameters.yaml
packages/EasyDocker/src/Console/Commands/AbstractTemplatesCommand.php
packages/EasyDocker/templates/docker-compose.yml.twig
packages/EasyDocker/templates/docker/elasticsearch/Dockerfile.twig
packages/EasyDocker/tests/Console/Commands/DockerFilesGeneratorCommandTest.php

[EasyDocker] Implement elasticsearch in docker templates

---

composer.json
monorepo-builder.yml
packages/EasyEntityChange/.gitignore
packages/EasyEntityChange/composer.json
packages/EasyEntityChange/docs/laravel_install.md
packages/EasyEntityChange/license
packages/EasyEntityChange/phpunit.xml
packages/EasyEntityChange/readme.md
packages/EasyEntityChange/src/Doctrine/EntityChangeSubscriber.php
packages/EasyEntityChange/src/Events/EntityChangeEvent.php
packages/EasyEntityChange/src/Events/EntityDeleteDataEvent.php
packages/EasyEntityChange/src/Exceptions/InvalidDispatcherException.php
packages/EasyEntityChange/src/Interfaces/EasyEntityChangeEventInterface.php
packages/EasyEntityChange/src/Interfaces/EasyEntityChangeExceptionInterface.php
packages/EasyEntityChange/tests/AbstractTestCase.php
packages/EasyEntityChange/tests/Doctrine/EntityChangeSubscriberTest.php
packages/EasyEntityChange/tests/Events/EntityChangeEventTest.php
packages/EasyEntityChange/tests/Events/EntityDeleteDataEventTest.php
packages/EasyEntityChange/tests/Exceptions/InvalidDispatcherExceptionTest.php
packages/EasyEntityChange/tests/Stubs/EventDispatcherStub.php
readme.md

[EasyEntityChange] Create package

---

packages/EasyDocker/templates/docker-compose.yml.twig

[EasyDocker] Fix elasticsearch config in docker-compose.yml.twig

---

packages/EasyCfhighlander/templates/cloudformation/Jenkinsfile.twig
packages/EasyCfhighlander/templates/cloudformation/project.cfhighlander.rb.twig

[EasyCfhighlander] Update cfhighlander versions in cloudformation templates

---

composer.json
packages/EasyLogging/.gitignore
packages/EasyLogging/composer.json
packages/EasyLogging/license
packages/EasyLogging/phpunit.xml
packages/EasyLogging/readme.md
packages/EasyLogging/src/Bridge/Laravel/BugsnagLoggingServiceProvider.php
packages/EasyLogging/src/Bugsnag/BugsnagHandler.php
packages/EasyLogging/src/Bugsnag/BugsnagLogClient.php
packages/EasyLogging/src/ContextModifiers/EntityValidationFailedExceptionContextModifier.php
packages/EasyLogging/src/Doctrine/ExternalLogger.php
packages/EasyLogging/src/Doctrine/ExternalSqlLogger.php
packages/EasyLogging/src/Formatters/SumoJsonFormatter.php
packages/EasyLogging/src/Interfaces/ExceptionContextModifierInterface.php
packages/EasyLogging/src/Interfaces/ExternalLogClientInterface.php
packages/EasyLogging/src/Interfaces/LoggerInterface.php
packages/EasyLogging/src/Interfaces/SqlLoggerInterface.php
packages/EasyLogging/src/Logger.php

[EasyLogging] Create package to centralise common logging logic

---

packages/EasyLogging/composer.json

[EasyLogging] Fix autoload for easy-logging in composer.json

---

packages/EasyLogging/composer.json

Replace eoneopay/externals with eonx-com/externals

---

packages/EasyEntityChange/src/Doctrine/EntityChangeSubscriber.php
packages/EasyEntityChange/tests/Doctrine/EntityChangeSubscriberTest.php

[EasyEntityChange] Skip job dispatches for empty jobs

---

composer.json
packages/EasyApiToken/composer.json
packages/EasyCfhighlander/composer.json
packages/EasyDocker/composer.json
packages/EasyEntityChange/composer.json

Package fixes

---

packages/EasyEntityChange/src/Doctrine/EntityChangeSubscriber.php
packages/EasyEntityChange/tests/Doctrine/EntityChangeSubscriberTest.php

[EasyEntityChange] Add a watchlist to EntityChangeSubscriber

---

packages/EasyLogging/src/Formatters/SumoJsonFormatter.php

[EasyLogging] Fix signature for JsonFormatter::format()

---

packages/EasyDecision/src/Helpers/ValueExpressionFunctionProvider.php

- updated expressions spelling
| Fixed tickets | #POIN-426

[EasyDecision] POIN-426-update-available-expressions-spelling

---

packages/EasyApiToken/src/Decoders/BasicAuthDecoder.php
packages/EasyApiToken/src/Interfaces/EasyApiTokenInterface.php
packages/EasyApiToken/src/Tokens/ApiKeyEasyApiToken.php
packages/EasyApiToken/src/Tokens/BasicAuthEasyApiToken.php
packages/EasyApiToken/src/Tokens/Factories/JwtEasyApiTokenFactory.php
packages/EasyApiToken/src/Tokens/JwtEasyApiToken.php
packages/EasyApiToken/tests/Encoders/ApiKeyAsBasicAuthUsernameEncoderTest.php
packages/EasyApiToken/tests/Encoders/Auth0JwtTokenEncoderTest.php
packages/EasyApiToken/tests/Encoders/BasicAuthEncoderTest.php
packages/EasyApiToken/tests/Encoders/FirebaseJwtTokenEncoderTest.php
packages/EasyApiToken/tests/Tokens/ApiKeyEasyApiTokenTest.php
packages/EasyApiToken/tests/Tokens/BasicAuthEasyApiTokenTest.php
packages/EasyApiToken/tests/Tokens/JwtEasyApiTokenTest.php

[EasyApiToken] Allow to retrieve original token

---

.github/workflows/php-ci.yml
composer.json
ecs.yaml
packages/EasyApiToken/composer.json
packages/EasyApiToken/src/External/Auth0JwtDriver.php
packages/EasyApiToken/tests/AbstractFirebaseJwtTokenTestCase.php
packages/EasyApiToken/tests/AbstractJwtTokenTestCase.php
packages/EasyCfhighlander/composer.json
packages/EasyCore/composer.json
packages/EasyDecision/composer.json
packages/EasyDocker/composer.json
packages/EasyEntityChange/composer.json
packages/EasyIdentity/composer.json
packages/EasyLogging/composer.json
packages/EasyLogging/src/Logger.php
packages/EasyPagination/composer.json
packages/EasyPipeline/composer.json
packages/EasyPsr7Factory/composer.json
packages/EasyRepository/composer.json
packages/EasyRepository/src/Implementations/Doctrine/ORM/LengthAwareDoctrineOrmPaginator.php
packages/EasyRepository/tests/Implementation/Doctrine/ORM/LengthAwareDoctrineOrmPaginatorTest.php
phpstan.neon

Clean-up dependencies versions

---

composer.json
monorepo-builder.yml
packages/EasySecurity/.gitignore
packages/EasySecurity/composer.json
packages/EasySecurity/license
packages/EasySecurity/phpunit.xml
packages/EasySecurity/readme.md
packages/EasySecurity/src/Context.php
packages/EasySecurity/src/Interfaces/ContextInterface.php
packages/EasySecurity/src/Interfaces/PermissionInterface.php
packages/EasySecurity/src/Interfaces/RoleInterface.php
packages/EasySecurity/src/Interfaces/RolesProviderInterface.php
packages/EasySecurity/src/Permission.php
packages/EasySecurity/src/Role.php
packages/EasySecurity/src/RolesProviders/InMemoryRolesProvider.php
packages/EasySecurity/tests/AbstractTestCase.php
packages/EasySecurity/tests/ContextTest.php
packages/EasySecurity/tests/PermissionTest.php
packages/EasySecurity/tests/RoleTest.php
packages/EasySecurity/tests/RolesProviders/InMemoryRolesProviderTest.php
phpstan.neon
readme.md

[EasySecurity] Create package

---

packages/EasySecurity/src/AbstractContext.php
packages/EasySecurity/tests/ContextStub.php
packages/EasySecurity/tests/ContextTest.php

[EasySecurity] Make context abstract as each app must define their own context

---

packages/EasyDecision/src/Bridge/Common/DecisionFactory.php
packages/EasyDecision/src/Bridge/Common/Interfaces/DecisionConfigProviderInterface.php
packages/EasyDecision/src/Bridge/Laravel/config/easy-decision.php
packages/EasyDecision/src/Decisions/AbstractDecision.php
packages/EasyDecision/src/Decisions/AffirmativeDecision.php
packages/EasyDecision/src/Decisions/ConsensusDecision.php
packages/EasyDecision/src/Decisions/DecisionConfig.php
packages/EasyDecision/src/Decisions/DecisionFactory.php
packages/EasyDecision/src/Decisions/UnanimousDecision.php
packages/EasyDecision/src/Decisions/ValueDecision.php
packages/EasyDecision/src/Interfaces/DecisionConfigInterface.php
packages/EasyDecision/src/Interfaces/DecisionInterface.php
packages/EasyDecision/tests/Decisions/ConsensusDecisionTest.php
packages/EasyDecision/tests/Stubs/DecisionConfigProviderStub.php

[EasyDecision] Implement default output when no rules provided

---

packages/EasyDecision/src/Decisions/AbstractDecision.php
packages/EasyDecision/tests/Decisions/ValueDecisionTest.php

[EasyDecision] Fix context exception when decision with no rules

---

packages/EasyDecision/src/Bridge/Common/DecisionFactory.php
packages/EasyDecision/tests/Bridge/Laravel/LaravelDecisionFactoryTest.php

[EasyDecision] Do not cache decision in factory

---

packages/EasyLogging/src/Logger.php

[EasyLogging] Skip easy-logging package itself in introspection

---

packages/EasyCore/src/Bridge/Laravel/Listeners/DoctrineClearEmBeforeJobListener.php
packages/EasyCore/src/Bridge/Laravel/Listeners/QueueWorkerStoppingListener.php
packages/EasyCore/src/Bridge/Laravel/Providers/DoctrineClearEmBeforeJobServiceProvider.php
packages/EasyCore/src/Bridge/Laravel/Providers/QueueWorkerStoppingServiceProvider.php

[EasyCore]Improve laravel jobs with listeners

---

packages/EasyLogging/src/Logger.php

[EasyLogging] Logger also replace Psr LoggerInterface in app

---

packages/EasyCore/src/Bridge/Laravel/config/easy-core.php

[EasyCore] Use env method in config

---

phpstan.neon

Organise phpstan.neon by packages

---

packages/EasyPagination/src/Paginators/AbstractLengthAwarePaginator.php
packages/EasyPagination/src/Paginators/ArrayPaginator.php
packages/EasyPagination/src/Paginators/EmptyPaginator.php
packages/EasyRepository/src/Implementations/Doctrine/ORM/AbstractPaginatedDoctrineOrmRepository.php
packages/EasyRepository/src/Implementations/Doctrine/ORM/LengthAwareDoctrineOrmPaginator.php

[EasyPagination] Improvements for apps to allow "manual" pagination

---

packages/EasyPagination/src/Paginators/AbstractLengthAwarePaginator.php
packages/EasyPagination/src/Paginators/ArrayPaginator.php
packages/EasyRepository/src/Implementations/Doctrine/ORM/AbstractPaginatedDoctrineOrmRepository.php
packages/EasyRepository/src/Implementations/Doctrine/ORM/LengthAwareDoctrineOrmPaginator.php
packages/EasyRepository/src/Implementations/Doctrine/ORM/Paginators/LengthAwarePaginator.php
packages/EasyRepository/tests/AbstractTestCase.php
packages/EasyRepository/tests/Implementation/Doctrine/ORM/AbstractPaginatedDoctrineOrmRepositoryTest.php

[EasyRepository] Implement better length aware paginator for doctrine orm

---

.github/workflows/split_tests.yml
packages/EasyTest/bin/easy-test
packages/EasyTest/composer.json
packages/EasyTest/config/services.yaml
packages/EasyTest/src/Console/Commands/CheckCoverageCommand.php
packages/EasyTest/src/Console/EasyTestApplication.php
packages/EasyTest/src/Coverage/Loaders/FilesystemCoverageLoader.php
packages/EasyTest/src/Coverage/Resolvers/TextCoverageResolver.php
packages/EasyTest/src/Exceptions/AbstractEasyTestException.php
packages/EasyTest/src/Exceptions/UnableToLoadCoverageException.php
packages/EasyTest/src/Exceptions/UnableToResolveCoverageException.php
packages/EasyTest/src/HttpKernel/EasyTestKernel.php
packages/EasyTest/src/Interfaces/CoverageLoaderInterface.php
packages/EasyTest/src/Interfaces/CoverageResolverInterface.php
packages/EasyTest/src/Interfaces/EasyTestExceptionInterface.php
packages/EasyTest/tests/AbstractTestCase.php
packages/EasyTest/tests/CheckCoverageCommandTest.php
packages/EasyTest/tests/fixtures/lines-but-no-coverage.txt

[EasyTest] Prepare for multi coverage formats

---

packages/EasyDecision/src/Decisions/AbstractDecision.php
packages/EasyDecision/src/Decisions/AffirmativeDecision.php
packages/EasyDecision/src/Decisions/ConsensusDecision.php
packages/EasyDecision/src/Decisions/UnanimousDecision.php
packages/EasyDecision/src/Decisions/ValueDecision.php
packages/EasyDecision/src/Interfaces/DecisionOutputForRuleAwareInterface.php
packages/EasyDecision/src/Rules/ExpressionLanguageRule.php
packages/EasyDecision/tests/Decisions/DecisionsTest.php
packages/EasyDecision/tests/Stubs/RuleStub.php
packages/EasyDecision/tests/Stubs/RuleWithExtraOutputStub.php

[EasyDecision] Make adding extra in output consistent

---

packages/EasyAsync/src/Bridge/Symfony/DependencyInjection/EasyAsyncExtension.php
packages/EasyAsync/src/Bridge/Symfony/Messenger/ProcessJobLogMiddleware.php
packages/EasyAsync/src/Bridge/WithProcessJobLogTrait.php
packages/EasyAsync/tests/Bridge/Symfony/Messenger/ProcessJobLogMiddlewareTest.php
packages/EasyAsync/tests/Stubs/MessengerMiddlewareStub.php

[EasyAsync] Implement messenger middleware for process job log

---

composer.json
packages/EasyPsr7Factory/composer.json
packages/EasyPsr7Factory/src/EasyPsr7Factory.php

[EasyPsr7Factory] Remove deprecated code

---

packages/EasyApiToken/tests/AbstractTestCase.php
packages/EasyCore/tests/AbstractTestCase.php
packages/EasyPsr7Factory/tests/AbstractTestCase.php
packages/EasySecurity/tests/AbstractTestCase.php

Remove var directory created by Symfony during tests

---

packages/EasyApiToken/composer.json
packages/EasyApiToken/tests/AbstractTestCase.php
packages/EasyPsr7Factory/tests/EasyPsr7FactoryTest.php
packages/EasySecurity/tests/Modifiers/ContextResolverTest.php

[EasyApiToken] Remove deprecated code

---

packages/EasyApiToken/src/Interfaces/Tokens/JwtEasyApiTokenInterface.php
packages/EasyApiToken/src/Tokens/JwtEasyApiToken.php
packages/EasyApiToken/tests/Tokens/JwtEasyApiTokenTest.php

[EasyApiToken] Implement getClaimForceArray on JwtEasyApiToken

---

packages/EasySecurity/src/Interfaces/ContextInterface.php
packages/EasySecurity/src/Interfaces/JwtClaimFetcherInterface.php
packages/EasySecurity/src/JwtClaimFetcher.php
packages/EasySecurity/src/Modifiers/AbstractContextModifier.php
packages/EasySecurity/src/Modifiers/AbstractFromJwtContextModifier.php
packages/EasySecurity/src/Modifiers/ProviderFromJwtModifier.php
packages/EasySecurity/src/Modifiers/RolesFromJwtModifier.php
packages/EasySecurity/src/Modifiers/UserFromJwtModifier.php
packages/EasySecurity/tests/AbstractTestCase.php
packages/EasySecurity/tests/JwtClaimFetcherTest.php
packages/EasySecurity/tests/Modifiers/ContextResolverTest.php
packages/EasySecurity/tests/Modifiers/ProviderFromJwtModifierTest.php
packages/EasySecurity/tests/Modifiers/RolesFromJwtModifierTest.php
packages/EasySecurity/tests/Modifiers/UserFromJwtModifierTest.php

[EasySecurity] Make claim a config instead of constant

---

packages/EasyPagination/composer.json
packages/EasyPagination/src/Bridge/Symfony/DependencyInjection/Configuration.php
packages/EasyPagination/src/Bridge/Symfony/DependencyInjection/EasyPaginationExtension.php
packages/EasyPagination/src/Bridge/Symfony/EasyPaginationBundle.php
packages/EasyPagination/src/Bridge/Symfony/Factories/ServerRequestFactory.php
packages/EasyPagination/src/Bridge/Symfony/Factories/StartSizeConfigFactory.php
packages/EasyPagination/src/Bridge/Symfony/Factories/StartSizeDataFactory.php
packages/EasyPagination/src/Bridge/Symfony/Resources/config/services.yaml
packages/EasyPagination/tests/AbstractTestCase.php
packages/EasyPagination/tests/Bridge/Symfony/EasyPaginationBundleTest.php
packages/EasyPagination/tests/Bridge/Symfony/Stubs/KernelStub.php
packages/EasyPagination/tests/Bridge/Symfony/fixtures/array_in_query.yaml
packages/EasyPagination/tests/Bridge/Symfony/fixtures/data/in_query_page_perPage_1_15.yaml
packages/EasyPagination/tests/Bridge/Symfony/fixtures/in_query.yaml
packages/EasyPagination/tests/Bridge/Symfony/fixtures/invalid.yaml
packages/EasyPagination/tests/Paginators/ArrayPaginatorTest.php
packages/EasyPagination/tests/Paginators/EmptyPaginatorTest.php
phpstan.neon

[EasyPagination] Create Symfony bridge

---

ecs.yaml
packages/EasyCore/src/Bridge/Symfony/ApiPlatform/Interfaces/NoIriItemInterface.php
packages/EasyCore/src/Bridge/Symfony/ApiPlatform/Routing/IriConverter.php
packages/EasyCore/src/Bridge/Symfony/DependencyInjection/EasyCoreExtension.php
packages/EasyCore/src/Bridge/Symfony/Resources/config/iri_converter.yaml

[EasyCore] No IRI item for api platform

---

packages/EasyCore/src/Bridge/Symfony/DependencyInjection/EasyCoreExtension.php
packages/EasyCore/src/Bridge/Symfony/Interfaces/EventListenerInterface.php

[EasyCore] Symfony bridge auto configure listeners

---

packages/EasyDecision/src/Bridge/Symfony/Resources/config/use_expression_language.yaml
packages/EasyDecision/src/Configurators/AbstractNameRestrictedConfigurator.php
packages/EasyDecision/src/Configurators/AbstractTypeRestrictedConfigurator.php
packages/EasyDecision/src/Decisions/DecisionFactory.php
packages/EasyDecision/src/Interfaces/RestrictedDecisionConfiguratorInterface.php
packages/EasyDecision/tests/Bridge/Symfony/EasyDecisionBundleTest.php
packages/EasyDecision/tests/Bridge/Symfony/Fixtures/value_with_name_restricted_expression_function.yaml
packages/EasyDecision/tests/Bridge/Symfony/Fixtures/value_with_type_restricted_expression_function.yaml
packages/EasyDecision/tests/Bridge/Symfony/Stubs/Configurators/NameRestrictedExpressionFunctionConfigurator.php
packages/EasyDecision/tests/Bridge/Symfony/Stubs/Configurators/TypeRestrictedExpressionFunctionConfigurator.php
phpstan.neon

[EasyDecision] Implement restricted decision configurator

---

packages/EasyPagination/src/Bridge/Laravel/Providers/AbstractStartSizeEasyPaginationProvider.php
packages/EasyPagination/tests/AbstractTestCase.php
packages/EasyPagination/tests/Bridge/Laravel/ServiceProvidersTest.php

[EasyPagination] Use psr7factory to create server request in laravel

---

packages/EasyCore/src/Bridge/Symfony/DependencyInjection/EasyCoreExtension.php

[EasyCore] Sync DI\Configuration to DI\EasyCoreExtension api_platform configuration keys

---

packages/EasyCore/src/Bridge/Symfony/DependencyInjection/EasyCoreExtension.php
packages/EasyCore/src/Bridge/Symfony/Resources/config/api_platform/simple_data_persister.yaml

[EasyCore] Non-existent service "container" updated to "service_container" from simple_data_persister.yaml

---

packages/EasySsm/bin/test-dotenv.php
packages/EasySsm/src/Console/Commands/ExportEnvsCommand.php
packages/EasySsm/src/Dotenv/SsmDotenv.php
packages/EasySsm/src/Services/Dotenv/SsmDotenv.php
packages/EasySsm/src/Services/Dotenv/SsmDotenvInterface.php
packages/EasySsm/tests/Dotenv/SsmDotenvTest.php
packages/EasySsm/tests/Services/Dotenv/SsmDotenvTest.php
packages/EasySsm/tests/Stubs/SsmClientStub.php
phpstan.neon

[EasySsm] Add strict option and logging support

---

packages/EasySsm/src/Helpers/Parameters.php
packages/EasySsm/src/Services/Dotenv/Loaders/ConsoleOutputLoader.php
packages/EasySsm/tests/Services/Aws/CredentialsProviderTest.php
packages/EasySsm/tests/Services/Dotenv/Loaders/ConsoleOutputLoaderTest.php

[EasySsm] Handle incomplete SSM path, quote env export and add column

---

packages/EasyApiToken/docs/_package.yaml
packages/EasyCore/src/Bridge/Symfony/ApiPlatform/DataPersister/AbstractContextDataPersister.php
packages/EasyCore/src/Bridge/Symfony/ApiPlatform/DataPersister/AbstractDataPersister.php
packages/EasyCore/tests/Bridge/Symfony/ApiPlatform/DataPersister/AbstractContextDataPersisterTest.php
packages/EasyCore/tests/Bridge/Symfony/ApiPlatform/DataPersister/AbstractDataPersisterTest.php
packages/EasyCore/tests/Bridge/Symfony/Stubs/ContextDataPersisterStub.php
packages/EasyCore/tests/Bridge/Symfony/Stubs/DataPersisterStub.php
packages/EasyCore/tests/Bridge/Symfony/Stubs/EntityStub.php
packages/EasySsm/src/HttpKernel/EasySsmKernel.php
packages/EasySsm/tests/AbstractTestCase.php

[EasySsm] Fix kernel cache/logs dirs for docker

---

packages/EasyCore/src/Bridge/Symfony/ApiPlatform/DataPersister/AbstractSimpleDataPersister.php
packages/EasyCore/src/Bridge/Symfony/ApiPlatform/DataPersister/ChainSimpleDataPersister.php
packages/EasyCore/src/Bridge/Symfony/ApiPlatform/Interfaces/SelfProvidedIriItemInterface.php
packages/EasyCore/src/Bridge/Symfony/ApiPlatform/Routing/IriConverter.php
phpstan.neon

[EasyCore] Implement SelfProvidedIriItemInterface

---

composer.json
packages/EasyCore/composer.json
packages/EasyCore/src/Bridge/Symfony/ApiPlatform/Command/ApiResourceAndSimpleDataPersisterMaker.php
packages/EasyCore/src/Bridge/Symfony/DependencyInjection/EasyCoreExtension.php
packages/EasyCore/src/Bridge/Symfony/Resources/config/api_platform/maker_commands.yaml
packages/EasyCore/src/Bridge/Symfony/Resources/skeleton/api_resource.tpl.php
packages/EasyCore/src/Bridge/Symfony/Resources/skeleton/simple_data_persister.tpl.php
phpstan.neon
phpunit.xml

[EasyCore] Add maker command for simple ApiResource and DataPersister

---

packages/EasyStandard/src/Sniffs/Classes/AvoidPrivateConstructorSniff.php
packages/EasyStandard/tests/Sniffs/Classes/AvoidPrivateConstructorSniffTest.php
packages/EasyStandard/tests/fixtures/Sniffs/Classes/AvoidPrivateConstructorSniffTest.php.inc

[EasyStandard] Add AvoidPrivateConstructorSniff

---

packages/EasyCore/src/Bridge/Symfony/ApiPlatform/Listeners/ResolveRequestAttributesListener.php
packages/EasyCore/tests/Bridge/Symfony/Stubs/AbstractRequestAttributesAwareStub.php
packages/EasyCore/tests/Bridge/Symfony/Stubs/RequestAttributesAwareStub.php
phpstan.neon

[EasyCore] Allow setRequestAttributes to be set anywhere in the inheritance chain

---

packages/EasyRepository/src/Implementations/Doctrine/ORM/DoctrineOrmRepositoryTrait.php

- updated transactional method
| Fixed tickets | #PTS-962

[EasyRepository] Updated transactional method to close only on Doctrine exceptions

---

packages/EasySchedule/composer.json

[EasySchedule] Fix dependencies for eonx-com/easy-core

---

packages/EasyDecision/src/Configurators/AbstractNameRestrictedConfigurator.php
packages/EasyDecision/tests/Bridge/Symfony/Stubs/Configurators/NameRestrictedExpressionFunctionConfigurator.php

- updated EasyDecision package configurators

[EasyDecision] Update AbstractNameRestrictedConfigurator to use an array of names

---

ecs.yaml
packages/EasyStandard/src/Sniffs/Commenting/FunctionCommentSniff.php
packages/EasyStandard/tests/Sniffs/Commenting/FunctionCommentSniffTest.php
packages/EasyStandard/tests/fixtures/Sniffs/Commenting/FunctionCommentSniff/Correct/correct.php.inc
packages/EasyStandard/tests/fixtures/Sniffs/Commenting/FunctionCommentSniff/Wrong/blankLineAfterComment.php.inc
packages/EasyStandard/tests/fixtures/Sniffs/Commenting/FunctionCommentSniff/Wrong/incorrectCommentStyle.php.inc
packages/EasyStandard/tests/fixtures/Sniffs/Commenting/FunctionCommentSniff/Wrong/missingDocComment.php.inc
packages/EasyStandard/tests/fixtures/Sniffs/Commenting/FunctionCommentSniff/Wrong/missingParamDocComment.php.inc
phpstan.neon

- Add FunctionCommentSniff from NatePage\Sniffs package

[EasyStandard] Add FunctionCommentSniff from NatePage\Sniffs package 

---

packages/EasyCfhighlander/src/Console/CfhighlanderApplication.php
packages/EasyCfhighlander/src/Console/Commands/AbstractTemplatesCommand.php
packages/EasyCfhighlander/tests/AbstractTestCase.php
packages/EasyCore/src/Bridge/Laravel/Listeners/DoctrineRestartQueueOnEmCloseListener.php
packages/EasyCore/src/Bridge/Symfony/ApiPlatform/Pagination/CustomPaginatorInterface.php
packages/EasyCore/tests/Bridge/Laravel/Listeners/DoctrineRestartQueueOnEmCloseListenerTest.php
packages/EasyDocker/src/Console/EasyDockerApplication.php
packages/EasyPagination/src/Paginators/AbstractLengthAwarePaginator.php
phpstan.neon

Fix ecs and phpstan issues

---

packages/EasyApiToken/docs/laravel/config.md
packages/EasyApiToken/docs/symfony/config.md
packages/EasyApiToken/src/External/Auth0JwtDriver.php
packages/EasyApiToken/src/Factories/Decoders/AbstractJwtTokenDecoderFactory.php

[EasyApiToken] Nullable Auth0 private key

---

packages/EasySchedule/docs/symfony/install.md
packages/EasySchedule/docs/symfony/usage.md
packages/EasySchedule/readme.md
packages/EasySchedule/src/Bridge/Symfony/EasyScheduleBundle.php

[EasySchedule] Rename bundle + improve docs

---

packages/EasyPagination/src/Bridge/Symfony/Factories/ServerRequestFactory.php

[EasyPagination] Fake request in symfony console

---

packages/EasyStandard/src/Rector/ExplicitBoolCompareRector.php
packages/EasyStandard/tests/Rector/ExplicitBoolCompareRector/ExplicitBoolCompareRectorTest.php
packages/EasyStandard/tests/Rector/ExplicitBoolCompareRector/Fixture/FuncCallWithExplicitTrueComparison.php.inc
packages/EasyStandard/tests/Rector/ExplicitBoolCompareRector/Fixture/FuncCallWithNegate.php.inc
packages/EasyStandard/tests/Rector/ExplicitBoolCompareRector/Fixture/MethodCallWithExplicitTrueComparison.php.inc
packages/EasyStandard/tests/Rector/ExplicitBoolCompareRector/Fixture/MethodCallWithNegate.php.inc

[EasyStandard] Add ExplicitBoolCompareRector

---

packages/EasyDecision/src/Bridge/Laravel/EasyDecisionServiceProvider.php
packages/EasyDecision/src/Configurators/SetExpressionLanguageConfigurator.php
packages/EasyDecision/src/Decisions/DecisionFactory.php

- used ExpressionLanguageFactory in SetExpressionLanguageConfigurator

[EasyDecision] Use ExpressionLanguageFactory in SetExpressionLanguageConfigurator

---

packages/EasySchedule/src/Bridge/Symfony/Resources/config/services.yaml

[EasySchedule] Fix data collector template

---

packages/EasySchedule/src/Bridge/Symfony/Resources/config/services.yaml
packages/EasySchedule/src/Bridge/Symfony/Resources/views/Collector/schedule_collector.html.twig

[EasySchedule] Fix data collector templates for real

---

packages/EasyAwsCredentialsFinder/composer.json

[EasyAwsCredentialsFinder] Fix dependencies

---

packages/EasyAwsCredentialsFinder/src/AwsSsoAccessToken.php
packages/EasyAwsCredentialsFinder/src/AwsSsoAccessTokenProvider.php
packages/EasyAwsCredentialsFinder/src/Bridge/Symfony/Resources/config/services.yaml
packages/EasyAwsCredentialsFinder/src/Exceptions/AbstractEasyAwsCredentialsFinderException.php
packages/EasyAwsCredentialsFinder/src/Exceptions/InvalidCachedSsoAccessTokenContentsException.php
packages/EasyAwsCredentialsFinder/src/Exceptions/SsoAccessTokenNotFoundException.php
packages/EasyAwsCredentialsFinder/src/Finders/CliSsoCachedCredentialsFinder.php
packages/EasyAwsCredentialsFinder/src/Helpers/AwsConfigurationProvider.php
packages/EasyAwsCredentialsFinder/src/Interfaces/AwsSsoAccessTokenInterface.php
packages/EasyAwsCredentialsFinder/src/Interfaces/AwsSsoAccessTokenProviderInterface.php
packages/EasyAwsCredentialsFinder/src/Interfaces/EasyAwsCredentialsFinderExceptionInterface.php
packages/EasyAwsCredentialsFinder/src/Interfaces/Helpers/AwsConfigurationProviderInterface.php

[EasyAwsCredentialsFinder] Implement SSO access token provider

---

packages/EasySecurity/src/Bridge/Symfony/DependencyInjection/Compiler/RegisterPermissionExpressionFunctionPass.php
packages/EasySecurity/src/Bridge/Symfony/EasySecurityBundle.php

[EasySecurity] Fix Symfony bridge

---

packages/EasySecurity/src/Bridge/Symfony/DataCollector/SecurityContextDataCollector.php
packages/EasySecurity/src/Bridge/Symfony/Resources/views/Collector/security_context_collector.html.twig

[EasySecurity] Fix Symfony data collector

---

packages/EasyCore/src/Bridge/Symfony/DependencyInjection/Event/KernelEventTag.php

[EasyCore] Add dispatcher attribute to kernel event tag

---

packages/EasyPagination/src/Paginators/AbstractTransformableLengthAwarePaginator.php

[EasyPagination] Allow to reset transformer on paginator

---

packages/EasySsm/src/Console/Commands/ExportEnvsCommand.php

[EasySsm] Add way to skip export-env command

---

packages/EasySsm/src/Console/Commands/DumpEnvCommand.php
packages/EasySsm/tests/Console/Commands/DumpEnvCommandTest.php

[EasySsm] Make dump-env command easier to implement

---

packages/EasyApiToken/tests/Decoders/Auth0JwtTokenDecoderTest.php
packages/EasyCore/src/Bridge/Symfony/Validator/Constraints/Abn.php
packages/EasyCore/src/Bridge/Symfony/Validator/Constraints/AbnValidator.php
packages/EasyCore/tests/Bridge/Symfony/Valiator/Constraints/AbnValidatorTest.php

[EasyCore] Implement ABN validator in EasyCore package

---

packages/EasyApiToken/tests/Decoders/Auth0JwtTokenDecoderTest.php
packages/EasyCore/src/Doctrine/Type/DateTimeMicrosecondsType.php
packages/EasyCore/tests/Doctrine/Type/DateTimeMicrosecondsTypeTest.php

[EasyCore] Add DateTimeMicroseconds custom Doctrine type

---

packages/EasySsm/src/Helpers/Arr.php
packages/EasySsm/src/Services/Filesystem/SsmParametersDumper.php

[EasySsm] Handle parameters with namespace as name

---

packages/EasyDecision/src/Decisions/AbstractDecision.php
packages/EasyDecision/src/Interfaces/DecisionInterface.php
packages/EasyDecision/tests/Decisions/DecisionsTest.php
packages/EasyDecision/tests/Stubs/RuleStopPropagationStub.php

[EasyDecision] Allow decision to exit early when propagation stopped

---

packages/EasyCore/src/Doctrine/Type/DateTimeMicrosecondsType.php
packages/EasyCore/tests/Doctrine/Type/DateTimeMicrosecondsTypeTest.php

[EasyCore] Add DateTimeMicrosecondsType support for PostgreSQL

---

composer.json
packages/EasyErrorHandler/composer.json

Updated illuminate/support version in composer.json
| Tests pass?   | yes| Fixed tickets | #...

[EasyErrorHandler] Support illuminate support version to 6.0

---

packages/EasyLock/src/Bridge/Laravel/EasyLockServiceProvider.php
packages/EasyLock/src/Bridge/Laravel/config/easy-lock.php
packages/EasyLock/tests/Bridge/Laravel/AbstractLaravelTestCase.php

[EasyLock] Make laravel bridge consistent

---

packages/EasyWebhook/src/AbstractAsyncWebhookClient.php
packages/EasyWebhook/src/AbstractWebhook.php
packages/EasyWebhook/src/Interfaces/WebhookClientInterface.php
packages/EasyWebhook/src/Interfaces/WebhookInterface.php
packages/EasyWebhook/src/WebhookClient.php
packages/EasyWebhook/src/WithEventsWebhookClient.php
packages/EasyWebhook/tests/Bridge/Symfony/Stubs/KernelStub.php
packages/EasyWebhook/tests/Stubs/EventDispatcherStub.php

[EasyWebhook] Make sure webhook are always configured

---

packages/EasyErrorHandler/src/Bridge/Laravel/Handler/Handler.php

[EasyErrorHandler] Adapted ErrorHandler for using both contract versionss

---

packages/EasySsm/src/Console/Commands/DumpEnvCommand.php

[EasySsm] Sort alphabetically dumped env vars

---

packages/EasyLock/docs/symfony/install.md
packages/EasyLock/src/Bridge/Symfony/Messenger/ProcessWithLockMiddleware.php
packages/EasyLock/src/Bridge/Symfony/Messenger/WithLockDataStamp.php

[EasyLock] Allow to use stamp to lock in messenger

---

packages/EasySecurity/src/Bridge/Symfony/Security/FakeUser.php
packages/EasySecurity/tests/Bridge/Symfony/Security/FakeUserTest.php

[EasySecurity] Add symfony fake user

---

packages/EasyRepository/src/Implementations/Doctrine/ORM/DoctrineOrmRepositoryTrait.php

[EasyRepository] Add getClassMetadata to DoctrineOrmRepositoryTrait

---

packages/EasyLock/src/Bridge/Symfony/DependencyInjection/Configuration.php

[EasyLock] Fix default value for connection

---

packages/EasyCore/src/Bridge/Symfony/DependencyInjection/EasyCoreExtension.php

[EasyCore] Set alias to public for custom collection operations actions

---

packages/EasySecurity/src/AbstractSecurityContextFactory.php
packages/EasySecurity/src/SecurityContextFactory.php
packages/EasySecurity/src/SecurityContextResolver.php

[EasySecurity] Make sure authorization matrix is always set

---

packages/EasyNotification/docs/slack.md
packages/EasyNotification/src/Bridge/Laravel/EasyNotificationServiceProvider.php
packages/EasyNotification/src/Bridge/Symfony/Resources/config/services.php
packages/EasyNotification/src/Interfaces/MessageInterface.php
packages/EasyNotification/src/Messages/AbstractMessage.php
packages/EasyNotification/src/Messages/SlackMessage.php
packages/EasyNotification/src/Queue/Configurators/SlackBodyConfigurator.php
packages/EasyNotification/tests/Messages/SlackMessageTest.php
packages/EasyNotification/tests/Queue/ConfiguratorsTest.php

[EasyNotification] Support Slack messages

---

packages/EasyNotification/composer.json
packages/EasyNotification/src/Config/Config.php
packages/EasyNotification/src/Config/ConfigFinder.php
packages/EasyNotification/src/Helpers/StringHelper.php
packages/EasyNotification/src/Subscribe/SubscribeInfoFinder.php

[EasyNotification] Remove symfony/string because requires php72

---

packages/EasyNotification/src/NotificationClient.php
packages/EasyNotification/src/Subscribe/SubscribeInfoFinder.php

[EasyNotification] Fix API URLs + Handle empty responses

---

packages/EasyCore/src/Search/ElasticsearchSearchService.php
packages/EasyCore/src/Search/SearchServiceInterface.php

[EasyCore] Fix ElasticsearchSearchService to preserve search body

---

packages/EasyBugsnag/src/Bridge/Laravel/config/easy-bugsnag.php
packages/EasyBugsnag/src/Bridge/Symfony/DependencyInjection/Configuration.php
packages/EasyBugsnag/tests/Bridge/Symfony/Fixtures/default_config.yaml
packages/EasyBugsnag/tests/Bridge/Symfony/Stubs/KernelStub.php

[EasyBugsnag] Enable doctrine integration by default

---

packages/EasyCore/src/Bridge/Symfony/Messenger/ProcessWithLockMiddleware.php
packages/EasyCore/src/Doctrine/DBAL/Types/DateTimeMicrosecondsType.php
packages/EasyCore/src/Doctrine/DBAL/Types/JsonbType.php
packages/EasyCore/src/Doctrine/ORM/Query/AST/Functions/Contains.php
packages/EasyCore/tests/Doctrine/DBAL/Types/DateTimeMicrosecondsTypeTest.php
packages/EasyCore/tests/Doctrine/DBAL/Types/JsonbTypeTest.php
packages/EasyCore/tests/Doctrine/ORM/Query/AST/Functions/ContainsTest.php

| Fixed tickets | ...   
Add Jsonb type for Doctrine DBAL and CONTAINS function for ORM.
BC related to changed namespace for DBAL Types.

[EasyCore] Add JsonbType and Contains function support for PostgreSQL

---

packages/EasySecurity/composer.json
packages/EasySecurity/src/Bridge/EasyBugsnag/SecurityContextClientConfigurator.php
packages/EasySecurity/src/Bridge/Laravel/EasySecurityServiceProvider.php
packages/EasySecurity/src/Bridge/Laravel/config/easy-security.php
packages/EasySecurity/src/Bridge/Symfony/DependencyInjection/Configuration.php
packages/EasySecurity/src/Bridge/Symfony/DependencyInjection/EasySecurityExtension.php
packages/EasySecurity/src/Bridge/Symfony/Resources/config/easy_bugsnag.php
packages/EasySecurity/src/Interfaces/SecurityContextInterface.php
packages/EasySecurity/tests/Bridge/Symfony/EasySecurityBundleTest.php

[EasySecurity] Create eonx-com/easy-bugsnag bridge

---

composer.json
packages/EasyLogging/src/Bridge/BridgeConstantsInterface.php
packages/EasyLogging/src/Bridge/Symfony/DependencyInjection/Compiler/ReplaceChannelsDefinitionPass.php
packages/EasyLogging/src/Bridge/Symfony/DependencyInjection/EasyLoggingExtension.php
packages/EasyLogging/src/Bridge/Symfony/EasyLoggingBundle.php
packages/EasyLogging/src/Bridge/Symfony/Resources/config/services.php
packages/EasyLogging/src/Config/AbstractLoggingConfig.php
packages/EasyLogging/src/Config/HandlerConfig.php
packages/EasyLogging/src/Config/ProcessorConfig.php
packages/EasyLogging/src/Interfaces/Config/LoggingConfigInterface.php
packages/EasyLogging/src/LoggerFactory.php
packages/EasyLogging/tests/Bridge/Symfony/EasyLoggingBundleTest.php

[EasySecurity] Improve symfony bridge by using monolog bridge/bundle

---

packages/EasyCore/src/Search/ElasticsearchSearchService.php

[EasyCore] Support from and size options for elasticsearch

---

packages/EasyCore/src/Search/ElasticsearchSearchService.php
packages/EasyCore/tests/Search/ElasticsearchSearchServiceTest.php

Reason of the PR: https://eonx.atlassian.net/browse/MAN-738

[EasyCore] Fix `match_all` in query

---

packages/EasySecurity/src/Bridge/Symfony/DataCollector/SecurityContextDataCollector.php

[EasySecurity] Fix security context not configured in data collector

---

packages/EasyCore/src/Doctrine/DBAL/Types/JsonbType.php
packages/EasyCore/tests/Doctrine/DBAL/Types/JsonbTypeTest.php

Issue https://github.com/eonx-com/easy-monorepo/issues/360

[EasyCore] Make JsonbType type name value uppercase

---

packages/EasyCore/docs/doctrine/postgresql_migrations_fix.md
packages/EasyCore/src/Doctrine/Events/FixPostgreSqlDefaultSchemaListener.php

[EasyCore] Including FixPostgreSqlDefaultSchemaListener to package

---

packages/EasyErrorHandler/readme.md
packages/EasyErrorHandler/src/Bridge/Laravel/Provider/EasyErrorHandlerServiceProvider.php
packages/EasyErrorHandler/src/Bridge/Symfony/DependencyInjection/Configuration.php
packages/EasyErrorHandler/src/Bridge/Symfony/Resources/translations/EasyErrorHandlerBundle.en.php
packages/EasyErrorHandler/tests/Bridge/Symfony/Stubs/TranslatorStub.php

[EasyErrorHandler] Fix translations in Symfony bridge

---

packages/EasyErrorHandler/src/Builders/StatusCodeBuilder.php

[EasyErrorHandler] Handle exception to status code mapping

---

packages/EasyAsync/tests/Implementations/Doctrine/DBAL/JobLogPersisterTest.php
packages/EasyAsync/tests/Implementations/Doctrine/DBAL/JobPersisterTest.php
packages/EasyPagination/src/Exceptions/AbstractEasyPaginationException.php
packages/EasyPagination/src/Exceptions/InvalidPrimaryKeyIndexException.php
packages/EasyPagination/src/Paginators/DoctrineDbalLengthAwarePaginator.php
packages/EasyPagination/src/Paginators/DoctrineOrmLengthAwarePaginator.php
packages/EasyPagination/src/Traits/DoctrinePaginatorTrait.php
phpstan.neon

[EasyPagination] Add logic to deal better with joins in Doctrine paginators

---

packages/EasyCore/src/Bridge/Symfony/ApiPlatform/Pagination/SerializerContextBuilder.php
packages/EasyCore/tests/Bridge/Symfony/ApiPlatform/Pagination/SerializerContextBuilderTest.php

[EasyCore] Update SerializerContextBuilder to rely on request method

---

packages/EasyPagination/src/Traits/DoctrinePaginatorTrait.php

[EasyPagination] Handle pagination in Doctrine using primary keys

---

packages/EasyRequestId/src/Bridge/Laravel/EasyRequestIdServiceProvider.php

[EasyRequestId] Tag default resolver in Laravel bridge

---

packages/EasyLogging/src/Bridge/Laravel/EasyLoggingServiceProvider.php

[EasyLogging] Fix LoggerInterface service provider in Laravel

---

packages/EasyErrorHandler/src/Builders/ExtendedExceptionBuilder.php

[EasyErrorHandler] Fix exception data in ExtendedExceptionBuilder

---

packages/EasyErrorHandler/src/Builders/DefaultBuilderProvider.php
packages/EasyErrorHandler/src/Builders/HttpExceptionBuilder.php
packages/EasyErrorHandler/src/Builders/StatusCodeBuilder.php
packages/EasyErrorHandler/tests/AbstractTestCase.php

[EasyErrorHandler] HttpExceptionBuilder using Symfony Kernel Interfaces

---

packages/EasyRepository/src/Implementations/Doctrine/ORM/AbstractDoctrineOrmRepository.php
packages/EasyRepository/src/Implementations/Doctrine/ORM/AbstractPaginatedDoctrineOrmRepository.php
packages/EasyRepository/tests/AbstractTestCase.php
packages/EasyRepository/tests/Implementation/Doctrine/ORM/AbstractDoctrineOrmRepositoryTest.php
packages/EasyRepository/tests/Implementation/Doctrine/ORM/AbstractPaginatedDoctrineOrmRepositoryTest.php

[EasyRepository] Update doctrine classes to new ones

---

packages/EasyCore/src/Bridge/Symfony/Env/ForBuildEnvVarProcessor.php
packages/EasyCore/src/Bridge/Symfony/Resources/config/services.php
packages/EasyCore/tests/Bridge/Symfony/Validator/Constraints/AbnValidatorTest.php

[EasyCore] Add ForBuildEnvVarProcessor

---

packages/EasyErrorHandler/src/Bridge/Laravel/ExceptionHandler.php
packages/EasyErrorHandler/src/Bridge/Laravel/Translator.php
packages/EasyErrorHandler/src/Bridge/Symfony/Translator.php
packages/EasyErrorHandler/src/Builders/ExtendedExceptionBuilder.php
packages/EasyErrorHandler/src/Builders/UserMessageBuilder.php
packages/EasyErrorHandler/src/Exceptions/Traits/TranslatableExceptionTrait.php
packages/EasyErrorHandler/src/Interfaces/Exceptions/TranslatableExceptionInterface.php
packages/EasyErrorHandler/src/Interfaces/TranslatorInterface.php

[EasyErrorHandler] Allow translatable exception to define domain

---

packages/EasyErrorHandler/src/Exceptions/Traits/TranslatableExceptionTrait.php

[EasyErrorHandler] Add setter for TranslatableExceptionTrait domain

---

packages/EasySecurity/src/Authorization/CachedAuthorizationMatrixFactory.php
packages/EasySecurity/src/Bridge/BridgeConstantsInterface.php
packages/EasySecurity/src/Bridge/Laravel/EasySecurityServiceProvider.php
packages/EasySecurity/src/Bridge/Symfony/DataCollector/SecurityContextDataCollector.php
packages/EasySecurity/src/Bridge/Symfony/Resources/config/services.php
packages/EasySecurity/src/Bridge/Symfony/Resources/views/Collector/security_context_collector.html.twig
packages/EasySecurity/tests/Authorization/CachedAuthorizationMatrixFactoryTest.php
packages/EasySecurity/tests/Authorization/SymfonyCacheAuthorizationMatrixFactoryTest.php

[EasySecurity] Ease caching authorization matrix creation logic

---

composer.json
packages/EasyApiToken/src/Bridge/Laravel/EasyApiTokenServiceProvider.php
packages/EasyErrorHandler/src/Exceptions/Traits/TranslatableExceptionTrait.php
packages/EasySecurity/src/Bridge/Laravel/EasySecurityServiceProvider.php
packages/EasySsm/src/Console/Commands/ExportEnvsCommand.php
packages/EasyStandard/composer.json
rector-ci.php

https://github.com/rectorphp/rector/blob/master/docs/rector_rules_overview.md#deadcode

[Rector] enable full dead-code set

---

ecs.php
packages/EasyCore/src/Bridge/Symfony/Doctrine/EntityManagerResolver.php
packages/EasyCore/src/Bridge/Symfony/Resources/config/services.php
packages/EasyCore/src/Bridge/Symfony/Traits/EntityManagerAwareTrait.php
packages/EasyCore/src/Bridge/Symfony/Traits/TranslatorAwareTrait.php
packages/EasyCore/tests/AbstractTestCase.php
packages/EasyCore/tests/Bridge/Symfony/Doctrine/EntityManagerResolverTest.php
packages/EasyCore/tests/Bridge/Symfony/Traits/EntityManagerAwareTraitTest.php
packages/EasyCore/tests/Bridge/Symfony/Traits/TranslatorAwareTraitTest.php
phpstan.neon

[EasyCore] Add helper traits for Symfony projects

---

packages/EasyCore/src/Bridge/Symfony/Resources/config/services.php

[EasyCore] Remove entity manager resolver binding as it doesn't work

---

packages/EasyApiToken/src/Interfaces/ApiTokenDecoderInterface.php
packages/EasyNotification/src/Config/Config.php
packages/EasyNotification/src/Messages/RealTimeMessage.php
packages/EasyNotification/src/Messages/SlackMessage.php
packages/EasyNotification/src/Subscribe/SubscribeInfo.php
packages/EasySecurity/src/Bridge/Symfony/Resources/config/services.php

static fixes

---

.github/workflows/php-ci.yml
.github/workflows/split_tests.yml
packages/EasySecurity/src/Bridge/EasyBugsnag/SecurityContextClientConfigurator.php
packages/EasySecurity/src/Bridge/Laravel/EasySecurityServiceProvider.php
packages/EasySecurity/src/Bridge/Symfony/Resources/config/services.php

[EasySecurity] Prevent resolving security context when not needed

---

packages/EasyWebhook/readme.md
packages/EasyWebhook/src/Bridge/Laravel/Jobs/SendWebhookJob.php
packages/EasyWebhook/src/Bridge/Symfony/Messenger/SendWebhookHandler.php
packages/EasyWebhook/src/Stores/DoctrineDbalWebhookResultStore.php
packages/EasyWebhook/src/WebhookClient.php
packages/EasyWebhook/tests/WebhookClientTest.php

[EasyWebhook] Fix sending webhook async

---

packages/EasyWebhook/src/Stores/DoctrineDbalWebhookResultStore.php

[EasyWebhook] Make sure Http response getters don't throw exceptions

---

packages/EasyErrorHandler/readme.md
packages/EasyErrorHandler/src/Traits/ErrorHandlerAwareTrait.php
packages/EasyErrorHandler/tests/AbstractTestCase.php
packages/EasyErrorHandler/tests/Traits/ErrorHandlerAwareTraitTest.php

[EasyErrorHandler] Implement ErrorHandlerAwareTrait

---

packages/EasyLogging/readme.md
packages/EasyLogging/src/Bridge/Symfony/Traits/LoggerAwareTrait.php
packages/EasyLogging/tests/AbstractTestCase.php
packages/EasyLogging/tests/Bridge/Symfony/Traits/LoggerAwareTraitTest.php
phpstan.neon

[EasyLogging] Implement LoggerAwareTrait

---

packages/EasyLock/src/Exceptions/ShouldRetryException.php
packages/EasyLock/src/Interfaces/EasyLockExceptionInterface.php
packages/EasyLock/src/Interfaces/LockDataInterface.php
packages/EasyLock/src/LockData.php
packages/EasyLock/src/ProcessWithLockTrait.php

[EasyLock] Implement ShouldRetryException

---

packages/EasyErrorHandler/src/Bridge/Bugsnag/BugsnagReporter.php

[EasyErrorHandler] Ignore HttpExceptions for Bugsnag

---

.github/workflows/split_packages.yml

[Monorepo] Split packages in github actions

---

packages/EasySecurity/src/SecurityContext.php

[EasySecurity] Fix override permissions list

---

packages/EasyErrorHandler/src/Bridge/Bugsnag/BugsnagReporter.php
packages/EasyErrorHandler/src/Response/Data/ErrorResponseFormat.php
packages/EasyErrorHandler/src/Response/SymfonySerializerResponseFactory.php
packages/EasyErrorHandler/tests/Response/SymfonySerializerResponseFactoryTest.php
packages/EasyLock/src/Interfaces/EasyLockExceptionInterface.php

[EasyErrorHandler] Implement Symfony Serializer response factory

---

packages/EasyCore/src/HttpClient/Symfony/WithLoggingHttpClient.php
packages/EasyCore/tests/HttpClient/Symfony/WithLoggingHttpClientTest.php

[EasyCore] WithLogging Symfony HttpClient

---

packages/EasyErrorHandler/src/Bridge/Laravel/Provider/EasyErrorHandlerServiceProvider.php

- Bind the `ErrorHandlerInterface` as it requires some of the default builders in this package
- Use `ErrorHandlerInterface` instead of concrete class on the `ExceptionHandler`
Signed-off-by: Jay Are Galinada <jayare.galinada@flexisourceit.com.au>
| Fixed tickets | #429

[EasyErrorHandler] - Fixed binding of ErrorHandlerInterface

---

packages/EasyCore/src/Bridge/Laravel/ApiFormats/Interfaces/FormattedApiResponseInterface.php
packages/EasyCore/src/Bridge/Laravel/ApiFormats/Interfaces/SerializableInterface.php
packages/EasyCore/src/Bridge/Laravel/ApiFormats/Middleware/ReplaceApiFormatsMiddleware.php
packages/EasyCore/src/Bridge/Laravel/ApiFormats/Responses/FormattedApiResponse.php
packages/EasyCore/src/Bridge/Laravel/ApiFormats/Responses/NoContentApiResponse.php
packages/EasyCore/tests/Bridge/Laravel/ApiFormats/Middleware/ReplaceApiFormatsMiddlewareTest.php

[EasyCore] Implement replacement for api-formats

---

composer.json
packages/EasyUtils/.gitignore
packages/EasyUtils/composer.json
packages/EasyUtils/license
packages/EasyUtils/phpunit.xml
packages/EasyUtils/readme.md
packages/EasyUtils/src/CollectorHelper.php
packages/EasyUtils/src/Interfaces/HasPriorityInterface.php
packages/EasyUtils/src/Traits/HasPriorityTrait.php
packages/EasyUtils/tests/AbstractTestCase.php
packages/EasyUtils/tests/CollectorHelperTest.php
packages/EasyUtils/tests/Stubs/HasPriorityStub.php

[EasyUtils] Create package

---

packages/EasyErrorHandler/src/Helpers/ErrorDetailsHelper.php

[EasyErrorHandler] Allow to report details about previous exception

---

packages/EasyCore/src/Bridge/Laravel/Listeners/DoctrineRestartQueueOnConnectionFailedListener.php
packages/EasyCore/src/Bridge/Symfony/Messenger/CheckDoctrineDbConnectionMiddleware.php
packages/EasyCore/src/Doctrine/DBAL/ConnectionChecker.php

[EasyCore] Check if db connection is ok before processing job

---

packages/EasyBankFiles/src/Parsers/Nai/Results/ResultsContext.php

[EasyBankFiles] No fileControlTotalB for BAI files

---

packages/EasyWebhook/src/AbstractWebhook.php
packages/EasyWebhook/src/Interfaces/WebhookInterface.php

[EasyWebhook] Define constants for options

---

packages/EasyCore/src/Bridge/Symfony/Messenger/StopWorkerOnEmClosedEventListener.php
packages/EasyCore/src/Bridge/Symfony/Resources/config/services.php

[EasyCore] Stop messenger worker if em closed

---

packages/EasyErrorHandler/src/Bridge/Symfony/Messenger/ReportErrorEventListener.php
packages/EasyErrorHandler/src/Bridge/Symfony/Resources/config/services.php

[EasyErrorHandler] Report errors in messenger

---

packages/EasyErrorHandler/src/Bridge/Bugsnag/SeverityClientConfigurator.php
packages/EasyErrorHandler/src/Bridge/Laravel/Provider/EasyErrorHandlerServiceProvider.php
packages/EasyErrorHandler/src/Bridge/Laravel/config/easy-error-handler.php
packages/EasyErrorHandler/src/Bridge/Symfony/Resources/config/bugsnag_reporter.php
packages/EasyErrorHandler/src/Exceptions/Traits/SeverityAwareExceptionTrait.php
packages/EasyErrorHandler/src/Interfaces/Exceptions/SeverityAwareExceptionInterface.php

[EasyErrorHandler] Implement severity aware exception + bugsnag bridge

---

.gitignore
packages/EasyErrorHandler/src/Bridge/Bugsnag/SeverityClientConfigurator.php
packages/EasyErrorHandler/src/Reporters/AbstractErrorReporter.php
packages/EasyErrorHandler/src/Traits/DealsWithErrorLogLevelTrait.php

[EasyErrorHandler] Automatically set severity based on log level

---

packages/EasyUtils/readme.md

Reviewed and edited the EasyUtils readme. I tried to keep the light-hearted tone, and I moved what I felt was some introductory material to the top.

[EasyUtils] Review and edit readme

---

.github/workflows/php-ci.yml
.github/workflows/split_tests.yml
packages/EasyLock/src/Interfaces/LockServiceInterface.php
packages/EasyLock/src/LockService.php
packages/EasyLock/src/ProcessWithLockTrait.php
packages/EasyWebhook/src/Bridge/Laravel/EasyWebhookServiceProvider.php
packages/EasyWebhook/src/Bridge/Laravel/Jobs/SendWebhookJob.php
packages/EasyWebhook/src/Bridge/Symfony/Messenger/SendWebhookMessage.php
packages/EasyWebhook/src/Bridge/Symfony/Resources/config/core_middleware.php
packages/EasyWebhook/src/Middleware/LockMiddleware.php
packages/EasyWebhook/tests/Bridge/Symfony/Stubs/KernelStub.php
packages/EasyWebhook/tests/Middleware/LockMiddlewareTest.php
packages/EasyWebhook/tests/Stubs/LockServiceStub.php

[EasyWebhook] Implement lock as part of webhook middleware

---

packages/EasyWebhook/src/AbstractWebhook.php
packages/EasyWebhook/src/Bridge/Laravel/EasyWebhookServiceProvider.php
packages/EasyWebhook/src/Bridge/Symfony/Resources/config/core_middleware.php
packages/EasyWebhook/src/Exceptions/CannotRerunWebhookException.php
packages/EasyWebhook/src/Interfaces/WebhookInterface.php
packages/EasyWebhook/src/Middleware/RerunMiddleware.php
packages/EasyWebhook/tests/Middleware/RerunMiddlewareTest.php

[EasyWebhook] Handle rerun

---

packages/EasyWebhook/composer.json
packages/EasyWebhook/src/AbstractWebhook.php
packages/EasyWebhook/src/Bridge/Doctrine/Interfaces/StatementsProviderInterface.php
packages/EasyWebhook/src/Bridge/Doctrine/StatementProviders/SqlStatementProvider.php
packages/EasyWebhook/src/Bridge/Doctrine/StatementProviders/SqliteStatementProvider.php
packages/EasyWebhook/src/Bridge/Laravel/Commands/SendDueWebhooksCommand.php
packages/EasyWebhook/src/Bridge/Laravel/EasyWebhookServiceProvider.php
packages/EasyWebhook/src/Bridge/Symfony/Command/SendDueWebhooksCommand.php
packages/EasyWebhook/src/Bridge/Symfony/Resources/config/services.php
packages/EasyWebhook/src/Exceptions/InvalidDateTimeException.php
packages/EasyWebhook/src/Interfaces/SendAfterAwareWebhookResultStoreInterface.php
packages/EasyWebhook/src/Stores/DoctrineDbalWebhookResultStore.php
packages/EasyWebhook/tests/Stores/ArrayWebhookStoreTest.php
packages/EasyWebhook/tests/Stores/DoctrineDbalWebhookResultStoreTest.php
packages/EasyWebhook/tests/Stores/NullWebhookResultStoreTest.php

[EasyWebhook] Implement send after store + commands

---

packages/EasyWebhook/src/AbstractWebhook.php
packages/EasyWebhook/src/Interfaces/WebhookInterface.php
packages/EasyWebhook/src/Middleware/EventHeaderMiddleware.php
packages/EasyWebhook/src/Middleware/IdHeaderMiddleware.php
packages/EasyWebhook/src/Middleware/SignatureHeaderMiddleware.php
packages/EasyWebhook/tests/WebhookTest.php

[EasyWebhook] Add convenient methods on webhook

---

packages/EasyCore/src/Search/ElasticsearchSearchService.php

[EasyCore] Allow to set any ES option on search service

---

packages/EasySecurity/src/Bridge/Symfony/DependencyInjection/Compiler/RegisterSecurityContextPass.php
packages/EasySecurity/src/Bridge/Symfony/DependencyInjection/EasySecurityExtension.php

[EasySecurity] Fix symfony bridge for context service

---

packages/EasyWebhook/src/Interfaces/StackInterface.php
packages/EasyWebhook/src/Stack.php
packages/EasyWebhook/src/WebhookClient.php

[EasyWebhook] Implement rewind on stack

---

.github/workflows/php-ci.yml

[CI] Use symfonycorp security checker action

---

packages/EasyStandard/src/Rector/PhpDocCommentRector.php
packages/EasyStandard/tests/Rector/PhpDocCommentRector/Fixture/AssignmentHasCorrectPhpDoc.php.inc
packages/EasyStandard/tests/Rector/PhpDocCommentRector/Fixture/AssignmentHasInorrectPhpDoc.php.inc
packages/EasyStandard/tests/Rector/PhpDocCommentRector/Fixture/ClassHasCorrectPhpDoc.php.inc
packages/EasyStandard/tests/Rector/PhpDocCommentRector/Fixture/ClassHasIncorrectPhpDoc.php.inc

[EasyStandard] Hotfix/Fix PhpDocCommentRector

---

packages/EasyBugsnag/src/Bridge/Symfony/Resources/config/services.php

[EasyBugsnag] Use ShutdownStrategy on WorkerRunningEvent for Messenger

---

packages/EasyUtils/composer.json
packages/EasyUtils/readme.md
packages/EasyUtils/src/Bridge/BridgeConstantsInterface.php
packages/EasyUtils/src/Bridge/Laravel/EasyUtilsServiceProvider.php
packages/EasyUtils/src/Bridge/Laravel/config/easy-utils.php
packages/EasyUtils/src/Bridge/Symfony/DependencyInjection/Configuration.php
packages/EasyUtils/src/Bridge/Symfony/DependencyInjection/EasyUtilsExtension.php
packages/EasyUtils/src/Bridge/Symfony/EasyUtilsBundle.php
packages/EasyUtils/src/Bridge/Symfony/Resources/config/services.php
packages/EasyUtils/src/Exceptions/InvalidDivisionByZeroException.php
packages/EasyUtils/src/Interfaces/MathInterface.php
packages/EasyUtils/src/Math.php
packages/EasyUtils/tests/AbstractMathTestCase.php
packages/EasyUtils/tests/AbstractTestCase.php
packages/EasyUtils/tests/Bridge/Laravel/LaravelTestCaseTrait.php
packages/EasyUtils/tests/Bridge/Laravel/MathTest.php
packages/EasyUtils/tests/Bridge/Symfony/MathTest.php
packages/EasyUtils/tests/Bridge/Symfony/Stubs/KernelStub.php
packages/EasyUtils/tests/Bridge/Symfony/SymfonyTestCaseTrait.php
packages/EasyUtils/tests/MathTest.php

[EasyUtils] Add MathInterface

---

packages/EasyWebhook/src/Bridge/Symfony/EasyWebhookSymfonyBundle.php

[EasyWebhook] Override getContainerExtension for EasyWebhook bundle

---

packages/EasyLock/src/Bridge/BridgeConstantsInterface.php
packages/EasyLock/src/Bridge/Symfony/DependencyInjection/Compiler/RegisterLockStoreServicePass.php
packages/EasyLock/src/Bridge/Symfony/DependencyInjection/EasyLockExtension.php
packages/EasyLock/src/Bridge/Symfony/EasyLockSymfonyBundle.php
packages/EasyLock/src/Bridge/Symfony/Resources/config/services.php
packages/EasyLock/tests/Bridge/Symfony/EasyLockBundleTest.php
packages/EasyLock/tests/Bridge/Symfony/Fixtures/config/in_memory_connection.yaml
packages/EasyLock/tests/Bridge/Symfony/Stubs/KernelStub.php

[EasyLock] Default lock store connection to flock

---

packages/EasySecurity/src/Bridge/BridgeConstantsInterface.php
packages/EasySecurity/src/Bridge/Symfony/DependencyInjection/Configuration.php
packages/EasySecurity/src/Bridge/Symfony/DependencyInjection/EasySecurityExtension.php

[EasySecurity] Allow to control security voter priority

---

packages/EasyWebhook/docs/config.md
packages/EasyWebhook/docs/console.md
packages/EasyWebhook/docs/events.md
packages/EasyWebhook/docs/middleware.md
packages/EasyWebhook/docs/retry-strategies.md
packages/EasyWebhook/docs/stores.md
packages/EasyWebhook/docs/sync.md
packages/EasyWebhook/docs/webhook-client.md
packages/EasyWebhook/docs/webhook-result.md
packages/EasyWebhook/docs/webhook.md
packages/EasyWebhook/readme.md

Draft EasyWebhook docs. I tried to cover everything I could think of... Please let me know what I missed / overdid / got wrong!

[EasyWebhook] Improve docs

---

packages/EasyWebhook/src/Bridge/Laravel/EasyWebhookServiceProvider.php

[EasyWebhook] Fix method config in laravel

---

packages/EasyStandard/docs/ecs/sniffs.md

[EasyStandard] Fix title block for Sniffs

---

packages/EasyWebhook/docs/middleware.md
packages/EasyWebhook/src/Bridge/Laravel/EasyWebhookServiceProvider.php
packages/EasyWebhook/src/Bridge/Symfony/Resources/config/core_middleware.php
packages/EasyWebhook/src/Exceptions/InvalidStackIndexException.php
packages/EasyWebhook/src/Interfaces/StackInterface.php
packages/EasyWebhook/src/Middleware/AbstractMiddleware.php
packages/EasyWebhook/src/Middleware/SyncRetryMiddleware.php
packages/EasyWebhook/src/RetryStrategies/MultiplierWebhookRetryStrategy.php
packages/EasyWebhook/src/Stack.php
packages/EasyWebhook/tests/AbstractMiddlewareTestCase.php
packages/EasyWebhook/tests/Bridge/Symfony/Stubs/KernelStub.php
packages/EasyWebhook/tests/Middleware/SyncRetryMiddlewareTest.php
packages/EasyWebhook/tests/StackTest.php
packages/EasyWebhook/tests/Stubs/MiddlewareStub.php
packages/EasyWebhook/tests/Stubs/StackStub.php

[EasyWebhook] Implement synchronous retries

---

packages/EasyErrorHandler/src/Exceptions/Traits/LogLevelAwareExceptionTrait.php
packages/EasyErrorHandler/tests/Exceptions/BaseExceptionTest.php
phpstan.neon

[EasyErrorHandler] Add convenient methods to set log level on exception

---

packages/EasyWebhook/docs/stores.md
packages/EasyWebhook/src/Bridge/Laravel/EasyWebhookServiceProvider.php
packages/EasyWebhook/src/Bridge/Symfony/Resources/config/services.php
packages/EasyWebhook/src/Interfaces/Stores/DataCleanerInterface.php
packages/EasyWebhook/src/Stores/AbstractDoctrineDbalStore.php
packages/EasyWebhook/src/Stores/AbstractStore.php
packages/EasyWebhook/src/Stores/DoctrineDbalResultStore.php
packages/EasyWebhook/src/Stores/DoctrineDbalStore.php
packages/EasyWebhook/src/Stores/NullDataCleaner.php
packages/EasyWebhook/tests/AbstractTestCase.php
packages/EasyWebhook/tests/Middleware/ResetStoreMiddlewareTest.php
packages/EasyWebhook/tests/Middleware/SendAfterMiddlewareTest.php
packages/EasyWebhook/tests/Middleware/StoreMiddlewareTest.php
packages/EasyWebhook/tests/Middleware/SyncRetryMiddlewareTest.php
packages/EasyWebhook/tests/Stores/ArrayResultStoreTest.php
packages/EasyWebhook/tests/Stores/ArrayStoreTest.php
packages/EasyWebhook/tests/Stores/DoctrineDbalResultStoreTest.php
packages/EasyWebhook/tests/Stores/DoctrineDbalStoreFromIlluminateDatabaseTest.php
packages/EasyWebhook/tests/Stores/DoctrineDbalStoreTest.php
packages/EasyWebhook/tests/Stubs/ArrayStoreStub.php
packages/EasyWebhook/tests/WebhookClientTest.php

[EasyWebhook] Introduce DataCleanerInterface

---

packages/EasyErrorHandler/src/Bridge/EasyWebhook/WebhookFinalFailedListener.php
packages/EasyErrorHandler/src/Bridge/Laravel/Provider/EasyErrorHandlerServiceProvider.php
packages/EasyErrorHandler/src/Bridge/Symfony/DependencyInjection/EasyErrorHandlerExtension.php
packages/EasyErrorHandler/src/Bridge/Symfony/Resources/config/easy_webhook.php
packages/EasyErrorHandler/tests/AbstractTestCase.php

[EasyErrorHandler] EasyWehbook Bridge

---

composer.json
packages/EasyAsync/composer.json
packages/EasyAwsCredentialsFinder/composer.json
packages/EasyErrorHandler/composer.json
packages/EasySchedule/composer.json
packages/EasyTest/composer.json
packages/EasyWebhook/composer.json
packages/EasyWebhook/src/Stores/DoctrineDbalResultStore.php

Support Carbon V1

---

packages/EasyRandom/src/Bridge/Laravel/EasyRandomServiceProvider.php
packages/EasyRandom/src/Bridge/Laravel/config/easy-random.php
packages/EasyRandom/src/Bridge/Symfony/DependencyInjection/Configuration.php
packages/EasyRandom/src/Bridge/Symfony/DependencyInjection/EasyRandomExtension.php

[EasyRandom] Automatically resolve uuid v4 generator when possible

---

packages/EasyWebhook/src/Interfaces/Stores/StoreInterface.php
packages/EasyWebhook/src/Stores/DoctrineDbalStore.php
packages/EasyWebhook/tests/AbstractStoreTestCase.php
packages/EasyWebhook/tests/Stores/DoctrineDbalStoreTest.php

[EasyWebhook] Recover webhook extra from dbal store

---

packages/EasyDecision/src/Bridge/Symfony/Resources/views/Collector/decision_collector.html.twig
packages/EasySchedule/src/Bridge/Symfony/Resources/views/Collector/schedule_collector.html.twig
packages/EasySecurity/src/Bridge/Symfony/Resources/views/Collector/security_context_collector.html.twig
packages/EasyWebhook/src/Bridge/Symfony/Resources/views/Collector/webhook_collector.html.twig

Fix WebProfiler integration for new bundles names

---

packages/EasyApiToken/src/Bridge/Laravel/EasyApiTokenServiceProvider.php
packages/EasyAsync/src/Bridge/Laravel/Providers/EasyAsyncServiceProvider.php
packages/EasyBugsnag/src/Bridge/Laravel/EasyBugsnagServiceProvider.php
packages/EasyCore/src/Bridge/Laravel/Providers/EasyCoreServiceProvider.php
packages/EasyDecision/src/Bridge/Laravel/EasyDecisionServiceProvider.php
packages/EasyErrorHandler/src/Bridge/Laravel/Provider/EasyErrorHandlerServiceProvider.php
packages/EasyEventDispatcher/src/Bridge/Laravel/EasyEventDispatcherServiceProvider.php
packages/EasyLock/src/Bridge/Laravel/EasyLockServiceProvider.php
packages/EasyLogging/src/Bridge/Laravel/EasyLoggingServiceProvider.php
packages/EasyNotification/src/Bridge/Laravel/EasyNotificationServiceProvider.php
packages/EasyPagination/src/Bridge/Laravel/Providers/AbstractStartSizeEasyPaginationProvider.php
packages/EasyPagination/src/Bridge/Laravel/Providers/StartSizeAsArrayInQueryEasyPaginationProvider.php
packages/EasyPagination/src/Bridge/Laravel/Providers/StartSizeInQueryEasyPaginationProvider.php
packages/EasyPipeline/src/Bridge/Laravel/EasyIlluminatePipelineServiceProvider.php
packages/EasyPsr7Factory/src/Bridge/Laravel/EasyPsr7FactoryServiceProvider.php
packages/EasyRandom/src/Bridge/Laravel/EasyRandomServiceProvider.php
packages/EasyRequestId/src/Bridge/Laravel/EasyRequestIdServiceProvider.php
packages/EasySecurity/src/Bridge/Laravel/EasySecurityServiceProvider.php
packages/EasyUtils/src/Bridge/Laravel/EasyUtilsServiceProvider.php
packages/EasyWebhook/src/Bridge/Laravel/EasyWebhookServiceProvider.php

Refactor Laravel ServiceProviders Closures

---

packages/EasyLock/src/Bridge/Laravel/EasyLockServiceProvider.php
packages/EasyWebhook/src/Bridge/Laravel/EasyWebhookServiceProvider.php
packages/EasyWebhook/tests/Bridge/Laravel/AbstractLumenTestCase.php

[EasyWebhook] Fix core middleware not tagged in Laravel

---

packages/EasyAsync/composer.json
packages/EasyAsync/src/Bridge/Symfony/DependencyInjection/EasyAsyncExtension.php
packages/EasyAsync/src/Bridge/Symfony/Messenger/DoctrineManagersSanityCheckMiddleware.php
packages/EasyAsync/src/Bridge/Symfony/Messenger/ShouldKillWorkerSubscriber.php
packages/EasyAsync/src/Bridge/Symfony/Resources/config/messenger.php
packages/EasyAsync/src/Bridge/Symfony/Resources/config/messenger_doctrine.php
packages/EasyAsync/src/Doctrine/Exceptions/DoctrineConnectionNotOkException.php
packages/EasyAsync/src/Doctrine/Exceptions/DoctrineManagerClosedException.php
packages/EasyAsync/src/Doctrine/ManagersSanityChecker.php
packages/EasyAsync/src/Interfaces/ShouldKillWorkerExceptionInterface.php
packages/EasyAsync/tests/Bridge/Symfony/Stubs/KernelStub.php
packages/EasyAsync/tests/Doctrine/ManagersSanityCheckerTest.php
packages/EasyAsync/tests/Doctrine/Stubs/EntityManagerForSanityStub.php
packages/EasyAsync/tests/Doctrine/Stubs/ManagerRegistryStub.php
packages/EasyCore/src/Bridge/Symfony/Messenger/CheckDoctrineDbConnectionMiddleware.php
packages/EasyCore/src/Bridge/Symfony/Messenger/StopWorkerOnEmClosedEventListener.php
packages/EasyCore/src/Doctrine/DBAL/ConnectionChecker.php

[EasyAsync] Symfony Messenger DoctrineSanityCheck + ShouldKillWorker

---

packages/EasyAsync/src/Bridge/Laravel/Providers/EasyAsyncServiceProvider.php
packages/EasyAsync/src/Bridge/Laravel/Queue/AbstractQueueListener.php
packages/EasyAsync/src/Bridge/Laravel/Queue/DoctrineManagersSanityCheckListener.php
packages/EasyAsync/src/Bridge/Laravel/Queue/ShouldKillWorkerListener.php
packages/EasyCore/src/Bridge/Laravel/Listeners/DoctrineRestartQueueOnConnectionFailedListener.php
packages/EasyCore/src/Bridge/Laravel/Listeners/DoctrineRestartQueueOnEmCloseListener.php

[EasyAsync] ShouldKillWorker + DoctrineManagersSanityCheck in Laravel

---

packages/EasyAsync/src/Bridge/Laravel/Providers/EasyAsyncServiceProvider.php
packages/EasyAsync/src/Bridge/Laravel/Queue/DoctrineManagersClearListener.php
packages/EasyAsync/src/Bridge/Symfony/Messenger/DoctrineManagersClearMiddleware.php
packages/EasyAsync/src/Bridge/Symfony/Resources/config/messenger_doctrine.php
packages/EasyAsync/src/Doctrine/ManagersClearer.php

[EasyAsync] Doctrine Managers Clearer

---

packages/EasyBankFiles/composer.json
packages/EasyLogging/composer.json

[EasyLogging] Require monolog

---

packages/EasyAsync/composer.json

[EasyAsync] Fix composer autoload for Symfony bridge

---

packages/EasyAsync/src/Bridge/Symfony/Messenger/ShouldKillWorkerSubscriber.php
phpstan.neon

[EasyAsync] Improve ShouldKillWorkerSubscriber log

---

packages/EasyPagination/src/Traits/DoctrinePaginatorTrait.php

[EasyPagination] Fix doGetItemsUsingPrimaryKeys for doctrine/dbal

---

packages/EasyWebhook/docs/middleware.md
packages/EasyWebhook/src/Bridge/Laravel/EasyWebhookServiceProvider.php
packages/EasyWebhook/src/Bridge/Symfony/Resources/config/core_middleware.php
packages/EasyWebhook/src/Exceptions/AbstractDoNotHandleMeException.php
packages/EasyWebhook/src/Exceptions/CannotRerunWebhookException.php
packages/EasyWebhook/src/Exceptions/NoNextMiddlewareException.php
packages/EasyWebhook/src/Exceptions/WebhookIdRequiredForAsyncException.php
packages/EasyWebhook/src/Interfaces/DoNotHandleMeEasyWebhookExceptionInterface.php
packages/EasyWebhook/src/Middleware/HandleExceptionsMiddleware.php
packages/EasyWebhook/tests/AbstractMiddlewareTestCase.php
packages/EasyWebhook/tests/Middleware/HandleExceptionsMiddlewareTest.php
packages/EasyWebhook/tests/Stubs/StackThrowStub.php

[EasyWebhook] Implement HandleExceptionMiddleware

---

packages/EasyWebhook/composer.json

[EasyWebhook] Fix illuminate/database version for security

---

readme.md

Update release example in readme.md

---

packages/EasyBugsnag/src/Bridge/Laravel/EasyBugsnagServiceProvider.php
packages/EasyBugsnag/src/Bridge/Symfony/Resources/config/services.php
packages/EasyBugsnag/src/Bridge/Symfony/Shutdown/ShutdownStrategyListener.php
packages/EasyBugsnag/src/Shutdown/ShutdownStrategy.php

[EasyBugsnag] Make shutdown strategy consistent + fix notify in laravel queue

---

packages/EasyErrorHandler/src/Bridge/Bugsnag/SeverityClientConfigurator.php

[EasyErrorHandler] Map log level to bugsnag severity

---

composer.json
packages/EasyAsync/src/Bridge/Symfony/Messenger/Serializer/Interfaces/MessageBodyDecoderInterface.php
packages/EasyAsync/src/Bridge/Symfony/Messenger/Serializer/Interfaces/MessageObjectFactoryInterface.php
packages/EasyAsync/src/Bridge/Symfony/Messenger/Serializer/Interfaces/QueueEnvelopeInterface.php
packages/EasyAsync/src/Bridge/Symfony/Messenger/Serializer/JsonMessageBodyDecoder.php
packages/EasyAsync/src/Bridge/Symfony/Messenger/Serializer/MessageSerializer.php
packages/EasyAsync/src/Bridge/Symfony/Messenger/Serializer/NotSupportedMessage.php
packages/EasyAsync/src/Bridge/Symfony/Messenger/Serializer/NotSupportedMessageMiddleware.php
packages/EasyAsync/src/Bridge/Symfony/Messenger/Serializer/OriginalMessageStamp.php
packages/EasyAsync/src/Bridge/Symfony/Messenger/Serializer/QueueEnvelope.php
packages/EasyAsync/src/Bridge/Symfony/Resources/config/messenger.php

[EasyAsync] Implement custom Messenger Message Serializer

---

packages/EasyAsync/src/Batch/AbstractBatch.php
packages/EasyAsync/src/Batch/BatchUpdater.php
packages/EasyAsync/src/Interfaces/Batch/BatchInterface.php

[EasyAsync] Dispatch BatchCompletedEvent

---

packages/EasyWebhook/src/Bridge/Laravel/Commands/SendDueWebhooksCommand.php
packages/EasyWebhook/src/Stores/DoctrineDbalStore.php

[EasyWebhook] Fix SendDueWebhooksCommand logic

---

packages/EasyWebhook/src/Interfaces/WebhookInterface.php
packages/EasyWebhook/src/Middleware/SendAfterMiddleware.php
packages/EasyWebhook/src/Stores/DoctrineDbalStore.php

[EasyWebhook] Fix send after trigger logic

---

packages/EasyWebhook/src/AbstractWebhook.php
packages/EasyWebhook/src/Bridge/Laravel/Commands/SendDueWebhooksCommand.php
packages/EasyWebhook/src/Bridge/Symfony/Command/SendDueWebhooksCommand.php
packages/EasyWebhook/src/Interfaces/WebhookInterface.php
packages/EasyWebhook/src/Middleware/SendAfterMiddleware.php
packages/EasyWebhook/src/Stores/DoctrineDbalStore.php

[EasyWebhook] Fix send after trigger logic for real

---

packages/EasyWebhook/docs/middleware.md
packages/EasyWebhook/src/Bridge/Laravel/EasyWebhookServiceProvider.php
packages/EasyWebhook/src/Bridge/Symfony/Resources/config/core_middleware.php
packages/EasyWebhook/src/Middleware/AsyncMiddleware.php
packages/EasyWebhook/src/Middleware/EventsMiddleware.php
packages/EasyWebhook/src/Middleware/LockMiddleware.php
packages/EasyWebhook/src/Middleware/MethodMiddleware.php
packages/EasyWebhook/src/Middleware/RerunMiddleware.php
packages/EasyWebhook/src/Middleware/ResetStoreMiddleware.php
packages/EasyWebhook/src/Middleware/StatusAndAttemptMiddleware.php
packages/EasyWebhook/src/Middleware/StoreMiddleware.php
packages/EasyWebhook/src/Middleware/SyncRetryMiddleware.php
packages/EasyWebhook/tests/Middleware/SyncRetryMiddlewareTest.php

[EasyWebhook] Rework middleware order for consistent failure handling

---

packages/EasyAsync/src/Batch/BatchItem.php
packages/EasyAsync/src/Batch/BatchItemApprover.php
packages/EasyAsync/src/Batch/BatchItemProcessor.php
packages/EasyAsync/src/Batch/BatchItemRequiresApprovalDecorator.php
packages/EasyAsync/src/Batch/BatchUpdater.php
packages/EasyAsync/src/Bridge/Symfony/Messenger/BatchDispatcher.php
packages/EasyAsync/src/Bridge/Symfony/Messenger/BatchItemRequiresApprovalStamp.php
packages/EasyAsync/src/Bridge/Symfony/Messenger/ProcessBatchItemMiddleware.php
packages/EasyAsync/src/Exceptions/Batch/BatchItemStatusInvalidException.php
packages/EasyAsync/src/Interfaces/Batch/BatchItemApproverInterface.php
packages/EasyAsync/src/Interfaces/Batch/BatchItemInterface.php
packages/EasyAsync/src/Interfaces/Batch/BatchItemRequiresApprovalInterface.php
packages/EasyAsync/tests/Implementations/Doctrine/DBAL/JobLogPersisterTest.php
packages/EasyAsync/tests/Implementations/Doctrine/DBAL/JobPersisterTest.php

[EasyAsync] Implement approval for batch items

---

packages/EasyAsync/src/Batch/BatchUpdater.php

[EasyAsync] Fix batch status resolving for failed batch on its update.

---

packages/EasyBankFiles/src/Parsers/Nai/Parser.php

[EasyBankFiles] Fix BAI parsing for long text

---

packages/EasyBatch/src/Bridge/Symfony/DependencyInjection/EasyBatchExtension.php
packages/EasyBatch/src/Bridge/Symfony/Resources/config/services.php

[EasyBatch] Fix repositories service definitions + batch item per page config in extension

---

packages/EasyBatch/src/Repositories/BatchItemRepository.php

[EasyBatch] Remove fromAlias for batch items paginator

---

packages/EasyBatch/src/Repositories/BatchRepository.php

[EasyBatch] Fix BatchRepository select for update sql query

---

packages/EasyCore/src/Bridge/Symfony/ApiPlatform/DataCollector/RequestDataCollector.php

[EasyCore] Add getVersion to api-platform data collector decorator

---

packages/EasyBatch/src/Bridge/BridgeConstantsInterface.php
packages/EasyBatch/src/Bridge/Symfony/Resources/config/services.php
packages/EasyBatch/src/Factories/AbstractBatchObjectFactory.php
packages/EasyBatch/src/Factories/BatchFactory.php
packages/EasyBatch/src/Factories/BatchItemFactory.php
packages/EasyBatch/src/Interfaces/BatchObjectTransformerInterface.php
packages/EasyBatch/src/Objects/AbstractBatchItem.php
packages/EasyBatch/src/Transformers/AbstractBatchObjectTransformer.php
packages/EasyBatch/src/Transformers/BatchItemTransformer.php
packages/EasyBatch/src/Transformers/BatchTransformer.php
packages/EasyBatch/tests/AbstractTestCase.php

[EasyBatch] Fix BatchItem::$message serialization

---

packages/EasyBugsnag/src/Bridge/Laravel/EasyBugsnagServiceProvider.php
packages/EasyBugsnag/src/Bridge/Laravel/Session/SessionTrackingListener.php
packages/EasyBugsnag/src/Bridge/Laravel/config/easy-bugsnag.php
packages/EasyBugsnag/src/Bridge/Symfony/DependencyInjection/Configuration.php
packages/EasyBugsnag/src/Bridge/Symfony/DependencyInjection/EasyBugsnagExtension.php
packages/EasyBugsnag/src/Bridge/Symfony/Resources/config/sessions.php
packages/EasyBugsnag/src/Bridge/Symfony/Session/SessionTrackingSubscriber.php

[EasyBugsnag] Implement session tracking

---

packages/EasyErrorHandler/src/Bridge/Bugsnag/UnhandledClientConfigurator.php
packages/EasyErrorHandler/src/Bridge/Laravel/Provider/EasyErrorHandlerServiceProvider.php
packages/EasyErrorHandler/src/Bridge/Symfony/Resources/config/bugsnag_reporter.php

[EasyBugsnag] Improve handled/unhandled flag logic

---

packages/EasyWebhook/src/AbstractWebhookResult.php
packages/EasyWebhook/src/Interfaces/WebhookResultInterface.php
packages/EasyWebhook/src/Middleware/StatusAndAttemptMiddleware.php
packages/EasyWebhook/src/Middleware/StoreMiddleware.php
packages/EasyWebhook/tests/Middleware/StatusAndAttemptMiddlewareTest.php
packages/EasyWebhook/tests/Middleware/StoreMiddlewareTest.php
packages/EasyWebhook/tests/Stubs/AsyncDispatcherStub.php
packages/EasyWebhook/tests/WebhookClientTest.php

[EasyWebhook] Fix status when result not attempted

---

packages/EasyBatch/src/Bridge/Symfony/Resources/config/services.php

| Fixed tickets |   
- Fix the typo in the binded parameter.

[EasyBatch] Fix the typo in the binded parameter name

---

packages/EasyBugsnag/src/Bridge/Laravel/EasyBugsnagServiceProvider.php

[EasyBugsnag] Fix session_tracking enable in Laravel

---

packages/EasyBugsnag/src/Bridge/BridgeConstantsInterface.php
packages/EasyBugsnag/src/Bridge/Laravel/EasyBugsnagServiceProvider.php
packages/EasyBugsnag/src/Bridge/Laravel/Session/SessionTrackingListener.php
packages/EasyBugsnag/src/Bridge/Laravel/Session/SessionTrackingMiddleware.php
packages/EasyBugsnag/src/Bridge/Laravel/Session/TracksSessionTrait.php
packages/EasyBugsnag/src/Bridge/Laravel/config/easy-bugsnag.php
packages/EasyBugsnag/src/Bridge/Symfony/DependencyInjection/Configuration.php
packages/EasyBugsnag/src/Bridge/Symfony/DependencyInjection/EasyBugsnagExtension.php
packages/EasyBugsnag/src/Bridge/Symfony/Resources/config/sessions.php
packages/EasyBugsnag/src/Bridge/Symfony/Session/SessionTrackingSubscriber.php
packages/EasyBugsnag/src/Session/SessionTracker.php
packages/EasyBugsnag/tests/Bridge/Laravel/EasyBugsnagServiceProviderTest.php
packages/EasyBugsnag/tests/Bridge/Symfony/EasyBugsnagBundleTest.php
packages/EasyBugsnag/tests/Bridge/Symfony/Fixtures/default_config.yaml
packages/EasyBugsnag/tests/Session/SessionTrackerTest.php
phpstan.neon

[EasyBugsnag] Improve session tracking

---

packages/EasyBugsnag/composer.json
packages/EasyBugsnag/src/Bridge/Symfony/DependencyInjection/Configuration.php
packages/EasyBugsnag/src/Bridge/Symfony/DependencyInjection/EasyBugsnagExtension.php
packages/EasyBugsnag/src/Bridge/Symfony/Resources/config/worker.php
packages/EasyBugsnag/src/Bridge/Symfony/Worker/WorkerMessageReceivedListener.php

[EasyBugsnag] Support Symfony Messenger Message info

---

packages/EasyBugsnag/composer.json
packages/EasyBugsnag/src/Bridge/BridgeConstantsInterface.php
packages/EasyBugsnag/src/Bridge/Laravel/EasyBugsnagServiceProvider.php
packages/EasyBugsnag/src/Bridge/Laravel/config/easy-bugsnag.php
packages/EasyBugsnag/src/Bridge/Symfony/DependencyInjection/Configuration.php
packages/EasyBugsnag/src/Bridge/Symfony/DependencyInjection/EasyBugsnagExtension.php
packages/EasyBugsnag/src/Bridge/Symfony/Resources/config/aws_ecs_fargate.php
packages/EasyBugsnag/src/Configurators/AwsEcsFargateConfigurator.php

[EasyBugsnag] Implement AWS ECS Fargate integration

---

packages/EasyBugsnag/src/Bridge/Symfony/DependencyInjection/EasyBugsnagExtension.php
packages/EasyBugsnag/src/Bridge/Symfony/Resources/config/aws_ecs_fargate.php

[EasyBugsnag] Fix symfony integration for aws ecs fargate

---

packages/EasyBugsnag/src/Bridge/Symfony/DependencyInjection/Configuration.php
packages/EasyBugsnag/src/Configurators/AwsEcsFargateConfigurator.php
packages/EasyBugsnag/tests/Configurators/AwsEcsFargateConfiguratorTest.php

[EasyBugsnag] Handle errors in aws ecs fargate configurator

---

packages/EasyBugsnag/src/Configurators/AwsEcsFargateConfigurator.php

[EasyBugsnag] Cache app version in env var once resolved

---

packages/EasyBatch/src/Bridge/Symfony/Resources/config/services.php
packages/EasyBatch/src/Repositories/AbstractBatchObjectRepository.php
packages/EasyBatch/tests/Repositories/BatchItemRepositoryTest.php

[EasyBatch] Use transform in repository

---

packages/EasyWebhook/src/Bridge/Symfony/Resources/config/debug.php

Fixes the EasyWebhook DataCollector template path.

[EasyWebhook] Fixed the DataCollector template path

---

packages/EasyHttpClient/src/Bridge/Symfony/DependencyInjection/EasyHttpClientExtension.php

[EasyHttpClient] Fix Symfony DI config file locator

---

packages/EasyBatch/src/BatchManager.php
packages/EasyBatch/src/Bridge/Doctrine/DbalStatementsProvider.php
packages/EasyBatch/src/Interfaces/BatchObjectInterface.php
packages/EasyBatch/src/Objects/AbstractBatchObject.php
packages/EasyBatch/src/Objects/MessageDecorator.php
packages/EasyBatch/src/Transformers/AbstractBatchObjectTransformer.php
packages/EasyBatch/src/Transformers/BatchItemTransformer.php
packages/EasyBatch/tests/Repositories/BatchItemRepositoryTest.php

[EasyBatch] Implement metadata on batch object

---

packages/EasyBugsnag/src/Bridge/Laravel/EasyBugsnagServiceProvider.php
packages/EasyBugsnag/src/Bridge/Laravel/config/easy-bugsnag.php
packages/EasyBugsnag/tests/Bridge/Laravel/AbstractLaravelTestCase.php
packages/EasyBugsnag/tests/Bridge/Laravel/EasyBugsnagServiceProviderTest.php

[EasyBugsnag] Add Laravel config to enable/disable entire package

---

packages/EasyBugsnag/src/Bridge/Laravel/EasyBugsnagServiceProvider.php
packages/EasyBugsnag/src/Bridge/Laravel/config/easy-bugsnag.php
packages/EasyBugsnag/src/Bridge/Symfony/DependencyInjection/Configuration.php
packages/EasyBugsnag/src/Bridge/Symfony/DependencyInjection/EasyBugsnagExtension.php
packages/EasyBugsnag/src/Bridge/Symfony/Resources/config/default_configurators.php
packages/EasyBugsnag/src/Bridge/Symfony/Resources/config/services.php
packages/EasyBugsnag/tests/Bridge/Laravel/EasyBugsnagServiceProviderTest.php
packages/EasyBugsnag/tests/Bridge/Symfony/EasyBugsnagBundleTest.php
packages/EasyBugsnag/tests/Bridge/Symfony/Fixtures/default_configurators_off.yaml

[EasyBugsnag] Add config to disable default configurators

---

packages/EasyBugsnag/src/Bridge/BridgeConstantsInterface.php
packages/EasyBugsnag/src/Bridge/Laravel/EasyBugsnagServiceProvider.php
packages/EasyBugsnag/src/Bridge/Laravel/config/easy-bugsnag.php
packages/EasyBugsnag/src/Bridge/Symfony/DependencyInjection/Configuration.php
packages/EasyBugsnag/src/Bridge/Symfony/DependencyInjection/EasyBugsnagExtension.php
packages/EasyBugsnag/src/Bridge/Symfony/Resources/config/default_configurators.php

[EasyBugsnag] Add config for bugsnag basics options

---

packages/EasyBugsnag/src/Bridge/BridgeConstantsInterface.php
packages/EasyBugsnag/src/Bridge/Laravel/EasyBugsnagServiceProvider.php
packages/EasyBugsnag/src/Bridge/Symfony/Resources/config/services.php

[EasyBugsnag] Add service ids for request resolver and shutdown strategy

---

packages/EasyBugsnag/src/Bridge/Laravel/Session/SessionTrackingConfigurator.php
packages/EasyBugsnag/src/Bridge/Laravel/config/easy-bugsnag.php
packages/EasyBugsnag/src/Bridge/Symfony/DependencyInjection/Configuration.php

[EasyBugsnag] Session cache expiry in seconds

---

packages/EasyErrorHandler/src/Bridge/BridgeConstantsInterface.php
packages/EasyErrorHandler/src/Bridge/Laravel/Provider/EasyErrorHandlerServiceProvider.php
packages/EasyErrorHandler/src/Bridge/Laravel/config/easy-error-handler.php
packages/EasyErrorHandler/src/Bridge/Symfony/DependencyInjection/Configuration.php
packages/EasyErrorHandler/src/Bridge/Symfony/DependencyInjection/EasyErrorHandlerExtension.php
packages/EasyErrorHandler/src/Bridge/Symfony/Resources/config/bugsnag_reporter.php

[EasyErrorHandler] Add config for handled exceptions

---

packages/EasyHttpClient/composer.json
packages/EasyHttpClient/src/Bridge/BridgeConstantsInterface.php
packages/EasyHttpClient/src/Bridge/Laravel/EasyHttpClientServiceProvider.php
packages/EasyHttpClient/src/Bridge/Laravel/config/easy-http-client.php
packages/EasyHttpClient/src/Bridge/Symfony/DependencyInjection/Compiler/DecorateEasyWebhookClientPass.php
packages/EasyHttpClient/src/Bridge/Symfony/DependencyInjection/Configuration.php
packages/EasyHttpClient/src/Bridge/Symfony/DependencyInjection/EasyHttpClientExtension.php
packages/EasyHttpClient/src/Bridge/Symfony/EasyHttpClientSymfonyBundle.php
packages/EasyHttpClient/tests/AbstractTestCase.php
packages/EasyHttpClient/tests/Bridge/Laravel/AbstractLaravelTestCase.php
packages/EasyHttpClient/tests/Bridge/Laravel/EasyHttpClientServiceProviderTest.php
packages/EasyHttpClient/tests/Bridge/Symfony/AbstractSymfonyTestCase.php
packages/EasyHttpClient/tests/Bridge/Symfony/EasyHttpClientSymfonyBundleTest.php
packages/EasyHttpClient/tests/Bridge/Symfony/Fixtures/decorate_default_client.yaml
packages/EasyHttpClient/tests/Bridge/Symfony/Fixtures/decorate_easy_webhook_client.yaml
packages/EasyHttpClient/tests/Bridge/Symfony/Stubs/KernelStub.php
packages/EasyHttpClient/tests/Bridge/Symfony/Stubs/MessageBusStub.php
packages/EasyHttpClient/tests/Stubs/LockServiceStub.php

[EasyHttpClient] Bridge for easy-webhook

---

packages/EasyCore/src/Bridge/Symfony/ApiPlatform/DataCollector/RequestDataCollector.php

[EasyCore] Work with api-platform 2.5 and 2.6

---

packages/EasyBugsnag/src/Bridge/Symfony/DependencyInjection/Configuration.php
packages/EasyBugsnag/src/Bridge/Symfony/DependencyInjection/EasyBugsnagExtension.php
packages/EasyBugsnag/src/Bridge/Symfony/Resources/config/sessions_messenger.php
packages/EasyBugsnag/src/Bridge/Symfony/Session/SessionTrackingMessengerSubscriber.php

[EasyBugsnag] Count Symfony Messenger messages as sessions

---

packages/EasyErrorHandler/src/Bridge/Bugsnag/UnhandledCallbackBridge.php
packages/EasyErrorHandler/src/Bridge/Bugsnag/UnhandledClientConfigurator.php
packages/EasyErrorHandler/src/Bridge/Symfony/DependencyInjection/EasyErrorHandlerExtension.php

[EasyErrorHandler] Fix bugsnag unhandled errors implementation

---

packages/EasyBugsnag/src/Bridge/Laravel/Session/SessionTrackingConfigurator.php

[EasyBugsnag] Use right laravel cache class for session tracking

---

packages/EasyBugsnag/src/Bridge/Laravel/EasyBugsnagServiceProvider.php
packages/EasyBugsnag/src/Bridge/Laravel/Session/SessionTrackingQueueListener.php
packages/EasyBugsnag/src/Bridge/Laravel/config/easy-bugsnag.php

[EasyBugsnag] Session tracking for laravel queue job

---

packages/EasyBatch/src/BatchManager.php
packages/EasyBatch/src/Transformers/AbstractBatchObjectTransformer.php
packages/EasyBatch/src/Transformers/BatchItemTransformer.php
packages/EasyBatch/src/Transformers/BatchTransformer.php

[EasyBatch] Update batch for item on approve + Fix transformers

---

packages/EasyRequestId/src/Bridge/Laravel/EasyRequestIdServiceProvider.php
packages/EasyRequestId/src/Bridge/Laravel/RequestIdRouteMatchedListener.php

[EasyRequestId] Laravel resolve IDs from request automatically

---

packages/EasyBatch/src/Transformers/AbstractBatchObjectTransformer.php

[EasyBatch] Fix metadata logic from array in transformer

---

packages/EasyBatch/src/Bridge/Symfony/Resources/config/services.php
packages/EasyBatch/src/Transformers/BatchTransformer.php

[EasyBatch] Fix batch transformer and Symfony listeners definition

---

packages/EasyRequestId/src/Bridge/Symfony/Messenger/RequestIdStamp.php
packages/EasyRequestId/src/Resolvers/FromArrayResolver.php

[EasyRequestId] RequestIdStamp getters nullable + Implement FromArrayResolver

---

packages/EasyLock/src/Bridge/Symfony/Resources/config/services.php

[EasyLock] Fix logger di for log channel

---

packages/EasyBatch/src/Listeners/BatchItemCancelledListener.php
packages/EasyBatch/src/Listeners/BatchItemCompletedListener.php

[EasyBatch] Fix batchId in batch item listeners

---

packages/EasyBatch/src/Bridge/Doctrine/DbalStatementsProvider.php
packages/EasyBatch/src/Repositories/BatchItemRepository.php

[EasyBatch] Order batch item pagination query

---

packages/EasyPagination/composer.json
packages/EasyPagination/src/Interfaces/LengthAwarePaginatorNewInterface.php
packages/EasyPagination/src/Interfaces/PaginatorInterface.php
packages/EasyPagination/src/Paginators/AbstractLengthAwarePaginatorNew.php
packages/EasyPagination/src/Paginators/AbstractPaginator.php
packages/EasyPagination/tests/Paginators/DoctrineDbalLengthAwarePaginatorNewTest.php

[EasyPagination] Improve pagination urls

---

packages/EasyWebhook/src/Middleware/SignatureHeaderMiddleware.php
packages/EasyWebhook/tests/Middleware/SignatureHeaderMiddlewareTest.php

[EasyWebhook] Improve strings that can be used for signature secret

---

packages/EasyPagination/composer.json

[EasyPagination] Add missing dependency for eonx-com/easy-utils

---

packages/EasyErrorHandler/src/Bridge/Symfony/Listener/ConsoleErrorEventListener.php
packages/EasyErrorHandler/src/Bridge/Symfony/Resources/config/services.php

[EasyErrorHandler] Report Symfony Console errors

---

packages/EasyLogging/src/Bridge/BridgeConstantsInterface.php
packages/EasyLogging/src/Bridge/Laravel/EasyLoggingServiceProvider.php
packages/EasyLogging/tests/Bridge/Laravel/EasyLoggingServiceProviderTest.php
phpstan.neon

[EasyLogging] Allow to pass channel as Laravel:make parameter

---

packages/EasyAsync/src/Bridge/BridgeConstantsInterface.php
packages/EasyAsync/src/Bridge/Laravel/Providers/EasyAsyncServiceProvider.php
packages/EasyAsync/src/Bridge/Laravel/Queue/DoctrineManagersClearListener.php
packages/EasyAsync/src/Bridge/Laravel/Queue/DoctrineManagersSanityCheckListener.php
packages/EasyAsync/src/Bridge/Symfony/Messenger/DoctrineManagersClearMiddleware.php
packages/EasyAsync/src/Bridge/Symfony/Resources/config/messenger.php
packages/EasyAsync/src/Bridge/Symfony/Resources/config/messenger_doctrine.php
packages/EasyAsync/src/Doctrine/ManagersSanityChecker.php
packages/EasyLock/src/Bridge/Laravel/EasyLockServiceProvider.php
packages/EasySecurity/src/Bridge/BridgeConstantsInterface.php
packages/EasySecurity/src/Bridge/Symfony/DependencyInjection/Compiler/RegisterPermissionExpressionFunctionPass.php
packages/EasySecurity/src/Bridge/Symfony/Resources/config/services.php
packages/EasyWebhook/src/Bridge/BridgeConstantsInterface.php
packages/EasyWebhook/src/Bridge/Laravel/EasyWebhookServiceProvider.php
packages/EasyWebhook/src/Bridge/Symfony/Resources/config/core_middleware.php

Specify custom log channel in packages

---

packages/EasyCore/src/Csv/CsvContentsProviderInterface.php
packages/EasyCore/src/Csv/CsvParserConfig.php
packages/EasyCore/src/Csv/CsvParserConfigInterface.php
packages/EasyCore/src/Csv/CsvWithHeadersParser.php
packages/EasyCore/src/Csv/CsvWithHeadersParserInterface.php
packages/EasyCore/src/Csv/Exceptions/InvalidCsvFilenameException.php
packages/EasyCore/src/Csv/Exceptions/MissingRequiredHeadersException.php
packages/EasyCore/src/Csv/Exceptions/MissingValueForRequiredHeadersException.php
packages/EasyCore/src/Csv/FromFileCsvContentsProvider.php
packages/EasyCore/tests/Csv/CsvWithHeadersParserTest.php
packages/EasyCore/tests/Csv/fixtures/empty_values.csv
packages/EasyCore/tests/Csv/fixtures/group_prefixes.csv
packages/EasyCore/tests/Csv/fixtures/missing_value_for_required_header.csv
packages/EasyCore/tests/Csv/fixtures/simple_file.csv

[EasyCore] Create CSV parser

---

packages/EasyPagination/src/Traits/DatabaseCommonPaginatorTrait.php
packages/EasyPagination/src/Traits/DoctrineCommonPaginatorTrait.php
packages/EasyPagination/src/Traits/EloquentPaginatorTrait.php
packages/EasyPagination/tests/Paginators/DoctrineDbalPaginatorTest.php
packages/EasyPagination/tests/Paginators/DoctrineOrmLengthAwarePaginatorNewTest.php
packages/EasyPagination/tests/Paginators/DoctrineOrmPaginatorTest.php
packages/EasyPagination/tests/Paginators/EloquentLengthAwarePaginatorNewTest.php
packages/EasyPagination/tests/Paginators/EloquentPaginatorTest.php

[EasyPagination] Improve criteria control on db paginators

---

packages/EasyPagination/src/Interfaces/PaginationInterface.php
packages/EasyPagination/src/Pagination.php
packages/EasyPagination/src/Paginators/AbstractPaginator.php
packages/EasyPagination/tests/PaginationTest.php

[EasyPagination] Allow apps to customize the url generation for current pagination

---

packages/EasyBatch/src/BatchManager.php
packages/EasyBatch/src/Interfaces/BatchManagerInterface.php
packages/EasyBatch/src/Objects/AbstractBatchObject.php

| Fixed tickets |    
- Fix Processed increment on BatchItem cancelling.

[EasyBatch] Fix Processed increment on BatchItem cancelling

---

packages/EasyErrorHandler/src/ErrorDetailsResolver.php
packages/EasyErrorHandler/tests/ErrorDetailsResolverTest.php

[EasyErrorHandler] Previous exceptions details at root level

---

packages/EasyBugsnag/src/Bridge/Doctrine/DBAL/SqlLogger.php
packages/EasyBugsnag/src/Bridge/Symfony/DependencyInjection/Compiler/DoctrineOrmSqlLoggerConfiguratorPass.php
packages/EasyBugsnag/tests/Bridge/Symfony/EasyBugsnagBundleTest.php
packages/EasyBugsnag/tests/Bridge/Symfony/Fixtures/sql_logger_no_method_call.yaml
packages/EasyBugsnag/tests/Bridge/Symfony/Fixtures/sql_logger_with_method_call.yaml
packages/EasyBugsnag/tests/Bridge/Symfony/Stubs/ConnectionStub.php
packages/EasyBugsnag/tests/Bridge/Symfony/Stubs/SqlLoggerStub.php
phpstan.neon

[EasyBugsnag] Fix doctrine sql logger symfony compiler pass

---

packages/EasyBugsnag/tests/Bridge/Symfony/Fixtures/default_config.yaml

[EasyBugsnag] Fix tests

---

phpstan.neon

Fix phpstan

---

packages/EasyRequestId/src/Interfaces/RequestIdServiceInterface.php

[EasyRequestId] Remove eonx from default header names

---

packages/EasyBatch/src/BatchManager.php
packages/EasyBatch/src/Bridge/Doctrine/DbalStatementsProvider.php
packages/EasyBatch/src/Interfaces/BatchInterface.php
packages/EasyBatch/src/Interfaces/BatchManagerInterface.php
packages/EasyBatch/src/Listeners/BatchCompletedListener.php
packages/EasyBatch/src/Objects/AbstractBatch.php
packages/EasyBatch/src/Transformers/BatchTransformer.php

[EasyBatch] Fix batch completed logic + Introduce cancelled count on batch

---

packages/EasyBugsnag/src/Bridge/Laravel/EasyBugsnagServiceProvider.php
packages/EasyBugsnag/src/Bridge/Laravel/config/easy-bugsnag.php

[EasyBugsnag] Define cache service in laravel + config for default store

---

packages/EasyCore/src/Search/ElasticsearchSearchService.php
packages/EasyCore/src/Search/SearchServiceInterface.php

[EasyCore] Implement delete indices on search service

---

composer.json
packages/EasyCore/src/Bridge/Symfony/Doctrine/AbstractDoctrineMigration.php
packages/EasyCore/src/Bridge/Symfony/Resources/config/search.php

[EasyCore] Improve search service in migration implementation for Symfony

---

packages/EasyBugsnag/src/Bridge/Laravel/config/easy-bugsnag.php

[EasyBugsnag] Fix Laravel session tracking config

---

packages/EasyCore/src/Bridge/Laravel/Doctrine/AbstractDoctrineMigration.php

[EasyCore] Abstract migration for indices in Laravel

---

packages/EasyRequestId/src/Bridge/EasyHttpClient/RequestIdRequestDataModifier.php
packages/EasyRequestId/src/Bridge/Laravel/EasyRequestIdServiceProvider.php
packages/EasyRequestId/src/Bridge/Laravel/config/easy-request-id.php
packages/EasyRequestId/src/Bridge/Symfony/DependencyInjection/Configuration.php
packages/EasyRequestId/src/Bridge/Symfony/DependencyInjection/EasyRequestIdExtension.php
packages/EasyRequestId/src/Bridge/Symfony/Resources/config/easy_http_client.php

[EasyRequestId] Bridge for eonx-com/easy-http-client

---

packages/EasySecurity/src/Bridge/Symfony/Resources/config/services.php
packages/EasySecurity/src/Bridge/Symfony/Security/SecurityContextAuthenticator.php

[EasySecurity] Support new symfony security system

---

packages/EasyBatch/src/Bridge/Doctrine/DateTimeWithMicroSeconds.php
packages/EasyBatch/src/Bridge/Doctrine/DbalStatementsProvider.php
phpstan.neon

[EasyBatch] Fix datetime type with microseconds

---

packages/EasyRandom/src/RandomString.php

[EasyRandom] Fix duplicated symbols issue

---

packages/EasyHttpClient/src/Bridge/BridgeConstantsInterface.php
packages/EasyHttpClient/src/Bridge/Symfony/Resources/config/psr_logger.php

[HttpClient] Fix logger channel in Symfony bridge

---

packages/EasyHttpClient/src/Bridge/Symfony/Resources/config/psr_logger.php

[HttpClient] Factories must have a class name

---

packages/EasyNotification/src/Exceptions/InvalidRealTimeMessageTypeException.php
packages/EasyNotification/src/Interfaces/MessageInterface.php
packages/EasyNotification/src/Messages/RealTimeMessage.php
packages/EasyNotification/tests/Messages/RealTimeMessageTest.php

[EasyNotification] Support flash real time messages

---

packages/EasySecurity/src/Bridge/Symfony/Security/Voters/PermissionVoter.php
packages/EasySecurity/src/Bridge/Symfony/Security/Voters/ProviderVoter.php
packages/EasySecurity/src/Bridge/Symfony/Security/Voters/RoleVoter.php
packages/EasySecurity/tests/Bridge/Symfony/Security/Voters/PermissionVoterTest.php
packages/EasySecurity/tests/Bridge/Symfony/Security/Voters/ProviderVoterTest.php
packages/EasySecurity/tests/Bridge/Symfony/Security/Voters/RoleVoterTest.php
packages/EasySecurity/tests/Stubs/SecurityContextResolverStub.php

[EasySecurity] Fix Symfony Voters to use SecurityContextResolverInterface

---

packages/EasySecurity/src/Bridge/Symfony/Security/ContextAuthenticator.php
packages/EasySecurity/src/Bridge/Symfony/Security/SecurityContextAuthenticator.php

[EasySecurity] Implement configuration fix in new Symfony security

---

packages/EasyCore/docs/doctrine/entity_manager_decorator.md

[EasyCore] Add documentation for Doctrine features

---

packages/EasyDecision/src/Bridge/Symfony/DataCollector/DecisionDataCollector.php
packages/EasyDecision/src/Bridge/Symfony/Resources/config/services.php

[EasyDecision] Fix Symfony DataCollector

---

packages/EasyTest/src/InvalidDataMaker/InvalidDataMaker.php

Add yieldDateTimeLessThanOrEqualRelatedProperty
Fix message in yieldDateTimeLessThanRelatedProperty

[EastTest] Add yieldDateTimeLessThanOrEqualRelatedProperty 

---

packages/EasyLock/src/Bridge/EasyAsync/Exceptions/LockAcquiringException.php
packages/EasyLock/src/LockService.php

[EasyLock] Implement easy-async bridge for exception to kill worker

---

packages/EasyApiToken/src/External/FirebaseJwtDriver.php
packages/EasyApiToken/tests/External/FirebaseJwtDriverTest.php
phpstan.neon

[EasyApiToken] Fix type confusion issue in FirebaseJwtDriver.php

---

packages/EasyRequestId/src/Bridge/Symfony/Resources/config/services.php
packages/EasyRequestId/src/Bridge/Symfony/Twig/RequestIdTwigExtension.php

[EasyRequestId] Add twig extension

---

packages/EasyBatch/src/BatchManager.php
packages/EasyBatch/src/Interfaces/BatchManagerInterface.php

[EasyBatch] Support before first dispatch callback

---

packages/EasyWebhook/src/Middleware/LockMiddleware.php

[EasyWebhook] Do not lock webhook when dispatching it to the queue

---

packages/EasyAsync/src/Bridge/Symfony/Messenger/BatchDispatcher.php
packages/EasyAsync/src/Bridge/Symfony/Messenger/BatchItemRequiresApprovalStamp.php
packages/EasyAsync/src/Bridge/Symfony/Messenger/BatchItemStamp.php
packages/EasyAsync/src/Bridge/Symfony/Messenger/BatchStamp.php
packages/EasyAsync/src/Bridge/Symfony/Messenger/DispatchBatchMiddleware.php
packages/EasyAsync/src/Bridge/Symfony/Messenger/ProcessBatchItemMiddleware.php
packages/EasyAsync/src/Bridge/Symfony/Messenger/ProcessJobLogMiddleware.php
packages/EasyAsync/src/Bridge/WithProcessJobLogDataTrait.php
packages/EasyAsync/src/Bridge/WithProcessJobLogTrait.php
packages/EasyAsync/src/Interfaces/Batch/BatchCancellerInterface.php
packages/EasyAsync/src/Interfaces/Batch/BatchDispatcherInterface.php
packages/EasyAsync/src/Interfaces/Batch/BatchFactoryInterface.php
packages/EasyAsync/src/Interfaces/Batch/BatchInterface.php
packages/EasyAsync/src/Interfaces/Batch/BatchItemApproverInterface.php
packages/EasyAsync/src/Interfaces/Batch/BatchItemFactoryInterface.php
packages/EasyAsync/src/Interfaces/Batch/BatchItemInterface.php
packages/EasyAsync/src/Interfaces/Batch/BatchItemProcessorInterface.php
packages/EasyAsync/src/Interfaces/Batch/BatchItemRequiresApprovalInterface.php
packages/EasyAsync/src/Interfaces/Batch/BatchItemStoreInterface.php
packages/EasyAsync/src/Interfaces/Batch/BatchStoreInterface.php
packages/EasyAsync/src/Interfaces/Batch/BatchUpdaterInterface.php
packages/EasyAsync/tests/Batch/BatchFactoryTest.php
packages/EasyAsync/tests/Batch/BatchTest.php
packages/EasyAsync/tests/Batch/Store/DoctrineDbalBatchItemStoreTest.php
packages/EasyAsync/tests/Batch/Store/DoctrineDbalBatchStoreTest.php

[EasyAsync] Deprecate batch classes

---

packages/EasyCore/src/Bridge/Symfony/Validator/Constraints/Alphanumeric.php
packages/EasyCore/src/Bridge/Symfony/Validator/Constraints/AlphanumericHyphen.php
packages/EasyCore/src/Bridge/Symfony/Validator/Constraints/AlphanumericHyphenValidator.php
packages/EasyCore/src/Bridge/Symfony/Validator/Constraints/AlphanumericValidator.php
packages/EasyCore/src/Bridge/Symfony/Validator/Constraints/DateInterval.php
packages/EasyCore/src/Bridge/Symfony/Validator/Constraints/DateIntervalValidator.php
packages/EasyCore/src/Bridge/Symfony/Validator/Constraints/Decimal.php
packages/EasyCore/src/Bridge/Symfony/Validator/Constraints/DecimalValidator.php
packages/EasyCore/tests/Bridge/Symfony/Validator/Constraints/AlphanumericHyphenValidatorTest.php
packages/EasyCore/tests/Bridge/Symfony/Validator/Constraints/AlphanumericValidatorTest.php
packages/EasyCore/tests/Bridge/Symfony/Validator/Constraints/DateIntervalValidatorTest.php
packages/EasyCore/tests/Bridge/Symfony/Validator/Constraints/DecimalValidatorTest.php

Add new constraints:
- Alphanumeric
- AlphanumericHyphen
- DateInterval
- Decimal

[EasyCore] Add new constraints

---

packages/EasyAsync/src/Bridge/Laravel/Queue/QueueWorkerStoppingListener.php

[EasyAsync] Support Laravel Worker Stopping Timeout status

---

packages/EasyDecision/src/Bridge/Laravel/EasyDecisionServiceProvider.php
packages/EasyDecision/src/Bridge/Symfony/Resources/config/use_expression_language.php

[EasyDecision] Register ValueExpressionFunctionProvider helper as service

---

packages/EasyCore/src/Bridge/Symfony/DependencyInjection/EasyCoreExtension.php
packages/EasyCore/tests/Bridge/Symfony/EasyCoreSymfonyBundleTest.php
packages/EasyCore/tests/Bridge/Symfony/Stubs/KernelStub.php

| Deprecations? | yno 
Fixes #739

[EasyCore] Make it work without ApiPlatform

---

packages/EasyRandom/src/Interfaces/RandomStringInterface.php
packages/EasyRandom/src/RandomString.php
packages/EasyRandom/tests/RandomStringTest.php

[EasyRandom] Support prefix and suffix

---

packages/EasyAsync/src/Bridge/EasyErrorHandler/WorkerStoppingException.php
packages/EasyAsync/src/Bridge/EasyErrorHandler/WorkerStoppingListener.php
packages/EasyAsync/src/Bridge/Laravel/Interfaces/QueueWorkerStoppingReasonsInterface.php
packages/EasyAsync/src/Bridge/Laravel/Providers/EasyAsyncServiceProvider.php
packages/EasyAsync/src/Bridge/Laravel/Queue/QueueWorkerStoppingListener.php
packages/EasyAsync/src/Bridge/Laravel/config/easy-async.php

[EasyAsync] EasyErrorHandler bridge for Laravel worker stopping

---

composer.json
packages/EasyApiToken/composer.json
packages/EasyApiToken/src/External/Auth0/TokenGenerator.php
packages/EasyApiToken/src/External/Auth0JwtDriver.php
packages/EasyApiToken/src/External/Auth0V7/TokenVerifier.php
packages/EasyApiToken/src/Interfaces/AlgorithmsInterface.php
packages/EasyApiToken/tests/AbstractTestCase.php
phpstan.neon

[EasyApiToken] Support auth0-php v7

---

composer.json
packages/EasyApiToken/composer.json

[EasyApiToken] Fix openssl extension version

---

packages/EasyApiToken/composer.json

[EasyApiToken] Remove EasyPsr7Factory dependency

---

packages/EasyTest/src/InvalidDataMaker/AbstractInvalidDataMaker.php

[EasyTest] Change variable order

---

composer.json
packages/EasyPsr7Factory/composer.json

[EasyPsr7Factory] Support Symfony Http Message Bridge v2

---

packages/EasyTest/src/InvalidDataMaker/AbstractInvalidDataMaker.php
packages/EasyTest/src/InvalidDataMaker/InvalidDataMaker.php

-fixed bug when using wrapWith
-fixed bug in yieldNotEqualTo

[EasyTest] Fixed bug when using wrapWith

---

packages/EasyCore/src/Bridge/Laravel/ApiFormats/Middleware/ReplaceApiFormatsMiddleware.php

[EasyCore] Fix api formats middleware for Laravel

---

symfony-recipes/eonx-com/easy-bugsnag/3.4/config/packages/dev/easy_bugsnag.yaml
symfony-recipes/eonx-com/easy-bugsnag/3.4/config/packages/easy_bugsnag.yaml
symfony-recipes/eonx-com/easy-bugsnag/3.4/config/packages/local/easy_bugsnag.yaml
symfony-recipes/eonx-com/easy-bugsnag/3.4/config/packages/test/easy_bugsnag.yaml
symfony-recipes/eonx-com/easy-bugsnag/3.4/manifest.json

[EasyBugsnag] Create symfony recipe

---

symfony-recipes/eonx-com/easy-error-handler/3.4/config/packages/dev/easy_error_handler.yaml
symfony-recipes/eonx-com/easy-error-handler/3.4/config/packages/easy_error_handler.yaml
symfony-recipes/eonx-com/easy-error-handler/3.4/config/packages/local/easy_error_handler.yaml
symfony-recipes/eonx-com/easy-error-handler/3.4/config/packages/test/easy_error_handler.yaml
symfony-recipes/eonx-com/easy-error-handler/3.4/manifest.json

[EasyErrorHandler] Create symfony recipe

---

symfony-recipes/eonx-com/easy-webhook/3.4/config/packages/easy_webhook.yaml
symfony-recipes/eonx-com/easy-webhook/3.4/manifest.json

[EasyWebhook] Create symfony recipe

---

packages/EasyTest/config/services.yaml

[EasyTest] Fix exclude path for DTOs

---

packages/EasyTest/src/InvalidDataMaker/InvalidDataMaker.php

[EasyTest] Generate float with lower precision

---

packages/EasyBugsnag/docs/config.md
packages/EasyBugsnag/src/Bridge/BridgeConstantsInterface.php
packages/EasyBugsnag/src/Bridge/Laravel/EasyBugsnagServiceProvider.php
packages/EasyBugsnag/src/Bridge/Laravel/config/easy-bugsnag.php
packages/EasyBugsnag/src/Bridge/Symfony/DependencyInjection/Configuration.php
packages/EasyBugsnag/src/Bridge/Symfony/DependencyInjection/EasyBugsnagExtension.php
packages/EasyBugsnag/src/Bridge/Symfony/Resources/config/app_name.php
packages/EasyBugsnag/src/Configurators/AppNameConfigurator.php
packages/EasyBugsnag/src/Interfaces/AppNameResolverInterface.php
packages/EasyBugsnag/src/Resolvers/DefaultAppNameResolver.php
symfony-recipes/eonx-com/easy-bugsnag/3.4/config/packages/easy_bugsnag.yaml

[EasyBugsnag] Add AppNameConfigurator.php

---

symfony-recipes/eonx-com/easy-bugsnag/3.4/config/packages/easy_bugsnag.yaml

[EasyBugsnag] Remove aws_ecs_fargate.meta_url from package config in Symfony Recipe

---

packages/EasyTest/src/InvalidDataMaker/InvalidDataMaker.php

[EasyTest] Fix yield invalid date

---

packages/EasyErrorHandler/src/ErrorHandler.php
packages/EasyErrorHandler/src/Reporters/FromIterableReporterProvider.php
packages/EasyErrorHandler/tests/ErrorHandlerTest.php
packages/EasyErrorHandler/tests/Stubs/ErrorReporterStub.php

[EasyErrorHandler] Support Symfony Messenger HandlerFailedException

---

packages/EasyDoctrine/src/DBAL/Types/DateTimeImmutableMicrosecondsType.php
packages/EasyDoctrine/src/DBAL/Types/DateTimeMicrosecondsType.php
packages/EasyDoctrine/tests/DBAL/Types/DateTimeImmutableMicrosecondsTypeTest.php
packages/EasyDoctrine/tests/DBAL/Types/DateTimeMicrosecondsTypeTest.php

Moved DatetimeImmutableMicrosecondsType from Payments to EasyDoctrine

[EasyDoctrine] Add DateTimeImmutableMicrosecondsType

---

packages/EasyCore/src/Csv/CsvWithHeadersParser.php
packages/EasyCore/tests/Csv/CsvWithHeadersParserTest.php
packages/EasyCore/tests/Csv/fixtures/hidden_characters.csv

[EasyCore] Update CsvWithHeadersParser.php to sanitize headers

---

packages/EasyApiToken/composer.json
packages/EasyApiToken/src/Exceptions/InvalidJwtException.php
packages/EasyApiToken/src/Exceptions/MethodNotSupportedException.php
packages/EasyApiToken/src/External/AwsCognito/Interfaces/JwkFetcherInterface.php
packages/EasyApiToken/src/External/AwsCognito/Interfaces/UserPoolConfigInterface.php
packages/EasyApiToken/src/External/AwsCognito/JwkFetcher.php
packages/EasyApiToken/src/External/AwsCognito/UserPoolConfig.php
packages/EasyApiToken/src/External/AwsCognitoJwtDriver.php
packages/EasyApiToken/tests/External/AwsCognitoJwtDriverTest.php
phpstan.neon

[EasyApiToken] Create AWS Cognito JWT Driver

---

packages/EasyApiToken/src/External/AwsCognito/JwkFetcher.php

[EasyApiToken] Convert keys to pem for Cognito

---

composer.json
packages/EasyApiToken/composer.json
packages/EasyApiToken/src/External/AwsCognito/JwkFetcher.php
phpstan.neon

[EasyApiToken] Fixed converting JWK to PEM for AWS Cognito.

---

packages/EasyCore/src/Bridge/Symfony/Doctrine/AbstractDoctrineMigration.php

[EasyCore] Deprecate AbstractDoctrineMigration

---

packages/EasyApiToken/docs/decoders.md

[EasyApiToken] Updated the documentation

---

packages/EasyCore/composer.json
packages/EasyCore/src/Bridge/Symfony/ApiPlatform/Normalizers/CarbonNormalizer.php
packages/EasyCore/tests/Bridge/Symfony/ApiPlatform/Normalizers/CarbonNormalizerTest.php

- added CarbonNormalizer to EasyCore

[EasyCore] Moved CarbonNormalizer from Payments

---

packages/EasyDoctrine/src/ORM/Query/AST/Functions/Cast.php
packages/EasyDoctrine/src/ORM/Query/AST/Functions/StringAgg.php
packages/EasyDoctrine/tests/ORM/Query/AST/Functions/CastTest.php
packages/EasyDoctrine/tests/ORM/Query/AST/Functions/StringAggTest.php

[EasyDoctrine] Move CAST and STRING_AGG functions

---

packages/EasyBatch/src/Repositories/BatchItemRepository.php
packages/EasyBatch/tests/Repositories/BatchItemRepositoryTest.php

[EasyBatch] Dispatch only pending batch items

---

composer.json
packages/EasyActivity/composer.json
packages/EasyCore/src/Bridge/Symfony/Validator/Constraints/Abn.php
packages/EasyCore/src/Bridge/Symfony/Validator/Constraints/Alphanumeric.php
packages/EasyCore/src/Bridge/Symfony/Validator/Constraints/AlphanumericHyphen.php
packages/EasyCore/src/Bridge/Symfony/Validator/Constraints/DateInterval.php
packages/EasyCore/src/Bridge/Symfony/Validator/Constraints/Decimal.php
packages/EasyCore/tests/Bridge/Symfony/ApiPlatform/Normalizers/CarbonNormalizerTest.php
packages/EasyDoctrine/composer.json
packages/EasyPagination/composer.json

[EasyCore] Support php 8.0 Attributes

---

packages/EasyTest/src/Coverage/Resolvers/CloverCoverageResolver.php

- Fix division by zero for the very new project
Error
After fix

[EasyTest] Fix division by zero while calculating coverage for a brand new (empty) project

---

composer.json
packages/EasyAsync/tests/Implementations/Doctrine/DBAL/JobLogPersisterTest.php
packages/EasyAsync/tests/Implementations/Doctrine/DBAL/JobPersisterTest.php
packages/EasyPagination/src/Paginators/DoctrineDbalLengthAwarePaginator.php

* fetchAssoc to fetchAssociative

[EasyPagination] FetchAssoc to fetchAssociative

---

packages/EasyBatch/src/Bridge/Symfony/Resources/config/services.php
packages/EasyBatch/tests/Bridge/Symfony/Stubs/KernelStub.php

[EasyBatch] Symfony service configuration fix

---

packages/EasyDoctrine/src/DBAL/Types/CarbonImmutableDateTimeMicrosecondsType.php
packages/EasyDoctrine/src/DBAL/Types/CarbonImmutableDateType.php
packages/EasyDoctrine/tests/DBAL/Types/CarbonImmutableDateTimeMicrosecondsTypeTest.php
packages/EasyDoctrine/tests/DBAL/Types/CarbonImmutableDateTypeTest.php
phpstan.neon

Added CarbonImmutableDateTimeMicrosecondsType and CarbonImmutableDateType

[EasyDoctrine] Carbon immutable to EasyDoctrine

---

packages/EasyBatch/src/BatchManager.php
packages/EasyBatch/src/Exceptions/BatchItemCancelledException.php
packages/EasyBatch/src/Exceptions/BatchItemCompletedException.php
phpstan.neon

[EasyBatch] Ensure batchItem cannot be completed more than once

---

packages/EasyBatch/src/BatchManager.php
packages/EasyBatch/src/Bridge/Symfony/Messenger/AsyncDispatcher.php
packages/EasyBatch/src/Interfaces/AsyncDispatcherInterface.php
packages/EasyBatch/tests/Stubs/AsyncDispatcherStub.php

[EasyBatch] Fix initial batch dispatch not to miss items

---

packages/EasyNotification/src/Bridge/Laravel/EasyNotificationServiceProvider.php
packages/EasyNotification/src/Bridge/Symfony/Resources/config/services.php
packages/EasyNotification/src/Interfaces/MessageInterface.php
packages/EasyNotification/src/Messages/PushMessage.php
packages/EasyNotification/src/Queue/Configurators/PushBodyConfigurator.php

[EasyNotification] Implement PushMessage

---

composer.json
packages/EasyApiToken/composer.json
packages/EasyApiToken/src/External/Auth0JwtDriver.php
packages/EasyApiToken/tests/AbstractAuth0JwtTokenTestCase.php
phpstan.neon

[EasyApiToken] Add support for auth0-php v8

---

packages/EasyEncryption/src/Encryptor.php
packages/EasyEncryption/src/Factories/DefaultEncryptionKeyFactory.php

[EasyEncryption] Support new HiddenString

---

packages/EasyBatch/src/Bridge/Symfony/Messenger/ProcessBatchItemMiddleware.php
packages/EasyErrorHandler/src/ErrorHandler.php

[EasyErrorHandler] Support Symfony Messenger Unrecoverable exception previous

---

packages/EasyActivity/src/Bridge/Symfony/DependencyInjection/Configuration.php

[EasyActivity] Fix configuration definition

---

composer.json
packages/EasyApiToken/composer.json
packages/EasyTest/src/InvalidDataMaker/AbstractInvalidDataMaker.php
packages/EasyTest/src/InvalidDataMaker/InvalidDataMaker.php
phpstan.neon

[EasyTest] Fixed the `make` method of the `AbstractInvalidDataMaker` class

---

packages/EasySecurity/src/Authorization/Helpers/AuthorizationMatrixFormatter.php
packages/EasySecurity/src/SecurityContext.php
packages/EasySecurity/tests/Bridge/Symfony/Security/Voters/RoleVoterTest.php
packages/EasySecurity/tests/SecurityContextTest.php

[EasySecurity] Allow setting roles on context using identifier

---

packages/EasyNotification/src/Messages/PushMessage.php

[EasyNotification] Add do not send token feature to PushMessage.php

---

packages/EasyErrorHandler/src/Bridge/BridgeConstantsInterface.php
packages/EasyErrorHandler/src/Bridge/Laravel/Provider/EasyErrorHandlerServiceProvider.php
packages/EasyErrorHandler/src/Bridge/Symfony/DependencyInjection/EasyErrorHandlerExtension.php
packages/EasyErrorHandler/src/Bridge/Symfony/Resources/config/services.php
packages/EasyErrorHandler/src/Builders/ExtendedExceptionBuilder.php
packages/EasyErrorHandler/src/ErrorHandler.php
packages/EasyErrorHandler/src/Interfaces/VerboseStrategyDriverInterface.php
packages/EasyErrorHandler/src/Interfaces/VerboseStrategyInterface.php
packages/EasyErrorHandler/src/Verbose/ChainVerboseStrategy.php
packages/EasyErrorHandler/tests/ErrorHandlerTest.php

[EasyErrorHandler] Implement verbose strategy

---

packages/EasyErrorHandler/src/ErrorDetailsResolver.php
packages/EasyUtils/src/ErrorDetailsHelper.php
packages/EasyWebhook/src/Stores/DoctrineDbalResultStore.php

[EasyUtils] Implement ErrorDetailsHelper to resolve simple error details

---

packages/EasyBatch/composer.json
packages/EasyBatch/src/Interfaces/BatchObjectInterface.php
packages/EasyBatch/src/Objects/AbstractBatchObject.php
packages/EasyBatch/src/Transformers/AbstractBatchObjectTransformer.php

[EasyBatch] Do not serialize Throwable anymore, use json format instead

---

packages/EasyBatch/composer.json
packages/EasyBatch/src/Interfaces/BatchObjectInterface.php
packages/EasyBatch/src/Objects/AbstractBatchObject.php
packages/EasyBatch/src/Transformers/AbstractBatchObjectTransformer.php
packages/EasyErrorHandler/src/ErrorDetailsResolver.php
packages/EasyUtils/src/ErrorDetailsHelper.php
packages/EasyWebhook/src/Stores/DoctrineDbalResultStore.php

Sync master with v3

---

packages/EasyBankFiles/src/Generators/BaseGenerator.php
packages/EasyBatch/src/BatchManager.php
packages/EasyBatch/src/Bridge/Doctrine/DbalStatementsProvider.php
packages/EasyBatch/src/Bridge/Symfony/Messenger/ProcessBatchItemMiddleware.php
packages/EasyBatch/src/Exceptions/BatchItemCannotBeRetriedException.php
packages/EasyBatch/src/Factories/BatchItemFactory.php
packages/EasyBatch/src/Interfaces/BatchItemFactoryInterface.php
packages/EasyBatch/src/Interfaces/BatchItemInterface.php
packages/EasyBatch/src/Interfaces/BatchManagerInterface.php
packages/EasyBatch/src/Objects/AbstractBatchItem.php
packages/EasyBatch/src/Objects/MessageDecorator.php
packages/EasyBatch/src/Transformers/BatchItemTransformer.php
phpstan.neon

[EasyBatch] Better support of item retries

---

packages/EasyBatch/src/Transformers/BatchItemTransformer.php

[EasyBatch] Fix default for max_attempts to 1

---

packages/EasyBatch/composer.json
packages/EasyBatch/src/BatchManager.php
packages/EasyBatch/src/Bridge/Doctrine/DbalStatementsProvider.php
packages/EasyBatch/src/Bridge/Symfony/DependencyInjection/Compiler/SetEncryptorOnBatchItemTransformerCompilerPass.php
packages/EasyBatch/src/Bridge/Symfony/EasyBatchSymfonyBundle.php
packages/EasyBatch/src/Bridge/Symfony/Resources/config/services.php
packages/EasyBatch/src/Exceptions/BatchItemCannotBeEncryptedException.php
packages/EasyBatch/src/Interfaces/BatchItemInterface.php
packages/EasyBatch/src/Objects/AbstractBatchItem.php
packages/EasyBatch/src/Objects/MessageDecorator.php
packages/EasyBatch/src/Transformers/AbstractBatchObjectTransformer.php
packages/EasyBatch/src/Transformers/BatchItemTransformer.php
packages/EasyBatch/src/Transformers/BatchTransformer.php
packages/EasyBatch/tests/AbstractTestCase.php
packages/EasyBatch/tests/BatchManagerTest.php
packages/EasyBatch/tests/Bridge/Symfony/Stubs/KernelStub.php
packages/EasyBatch/tests/Transformers/BatchItemTransformerTest.php

[EasyBatch] Support message encryption

---

packages/EasyBatch/src/Objects/AbstractBatchItem.php

[EasyBatch] Fix BachItem::encrypted in toArray to be integer

---

packages/EasyBatch/src/Repositories/AbstractBatchObjectRepository.php

[EasyBatch] Prevent extra columns to break database interactions

---

packages/EasyPagination/src/Resolvers/DefaultPaginationResolver.php
packages/EasyPagination/src/Resolvers/FromHttpFoundationRequestResolver.php

[EasyPagination] Fix pagination resolver to set right types

---

packages/EasyPagination/src/Interfaces/LengthAwarePaginatorInterface.php
packages/EasyPagination/src/Interfaces/PaginatorInterface.php
packages/EasyPagination/src/Paginators/AbstractLengthAwarePaginator.php
packages/EasyPagination/src/Paginators/AbstractPaginator.php
packages/EasyPagination/src/Paginators/IterableLengthAwarePaginator.php
packages/EasyPagination/src/Paginators/IterablePaginator.php
packages/EasyPagination/tests/Paginators/DoctrineDbalLengthAwarePaginatorNewTest.php
packages/EasyPagination/tests/Paginators/IterableLengthAwarePaginatorTest.php

[EasyPagination] Make it easier to return paginator in response

---

packages/EasyBatch/src/Repositories/AbstractBatchObjectRepository.php

[EasyBatch] Fix bug with non SQLite DB

---

packages/EasyTest/composer.json
packages/EasyTest/config/services.yaml
packages/EasyTest/src/Console/EasyTestApplication.php
packages/EasyTest/src/HttpKernel/EasyTestKernel.php

[EasyTest] Remove dependencies on autowire array parameter package

---

packages/EasyApiToken/src/Bridge/Laravel/EasyApiTokenServiceProvider.php
packages/EasyApiToken/src/Bridge/Symfony/Resources/config/services.php
packages/EasyApiToken/src/Decoders/ApiKeyDecoder.php
packages/EasyApiToken/src/Factories/ApiTokenDecoderFactory.php
packages/EasyApiToken/src/Interfaces/Tokens/HashedApiKeyDriverInterface.php
packages/EasyApiToken/src/Interfaces/Tokens/HashedApiKeyInterface.php
packages/EasyApiToken/src/Tokens/ApiKey.php
packages/EasyApiToken/src/Tokens/BasicAuth.php
packages/EasyApiToken/src/Tokens/HashedApiKey.php
packages/EasyApiToken/src/Tokens/HashedApiKeyDriver.php
packages/EasyApiToken/src/Tokens/Jwt.php
packages/EasyApiToken/tests/Decoders/ApiKeyDecoderTest.php
packages/EasyApiToken/tests/Tokens/HashedApiKeyDriverTest.php
packages/EasySecurity/src/Configurators/AbstractFromHashedApiKeyConfigurator.php
packages/EasySecurity/tests/Configurators/AbstractFromHashedApiKeyConfiguratorTest.php
packages/EasySecurity/tests/Stubs/PermissionFromHashedApiKeyConfiguratorStub.php
packages/EasyUtils/src/UrlHelper.php

[EasyApiToken] Implement HashedApiKey

---

packages/EasyBatch/src/Transformers/BatchItemTransformer.php
packages/EasyBatch/tests/Transformers/BatchItemTransformerTest.php

[EasyBatch] Fix BatchItem to object transformer

---

packages/EasyApiToken/composer.json
packages/EasyApiToken/src/Bridge/Symfony/Providers/AbstractFirewallAwareDecoderProvider.php
packages/EasyApiToken/src/Decoders/AbstractApiTokenDecoder.php
packages/EasyApiToken/tests/Bridge/Symfony/AbstractSymfonyTestCase.php
packages/EasyApiToken/tests/Bridge/Symfony/EasyApiTokenBundleTest.php
packages/EasyApiToken/tests/Bridge/Symfony/Fixtures/config/default_firewall_context.yaml
packages/EasyApiToken/tests/Bridge/Symfony/Providers/AbstractFirewallAwareDecoderProviderTest.php
packages/EasyApiToken/tests/Bridge/Symfony/Stubs/KernelStub.php

[EasyApiToken] Implement AbstractFirewallAwareDecoderProvider

---

packages/EasyCore/src/Bridge/Symfony/ApiPlatform/DataPersister/ChainSimpleDataPersister.php
packages/EasyCore/src/Bridge/Symfony/DependencyInjection/Compiler/ApiPlatformDataPersistersPass.php
packages/EasyCore/src/Bridge/Symfony/Env/ForBuildEnvVarProcessor.php
packages/EasySecurity/src/Bridge/Symfony/Resources/config/services.php

| Bug fix?      | yes and no
[EasyCore] Improved compatibility with Symfony 6.
[EasySecurity] Fixed the configuration of services.

Improved compatibility with Symfony 6

---

packages/EasyUtils/src/EnvVarSubstitutionHelper.php
phpstan.neon

[EasyUtils] Create EnvVarSubstitutionHelper.php

---

monorepo/Release/AutoGeneratedReleaseNotesWorker.php
monorepo/Release/PackagesListInReadmeReleaseWorker.php
monorepo/Release/UpdateTagInGithubWorkflow.php
packages/EasyApiToken/src/External/AwsCognitoJwtDriver.php

[EasyApiToken] Improved the `AwsCognitoJwtDriver` driver to be able to handle access tokens.

[EasyApiToken] Improved the `AwsCognitoJwtDriver` driver

---

packages/EasyBugsnag/src/Bridge/Symfony/Request/SymfonyRequestResolver.php

[EasyBugsnag] Fix symfony request bridge

---

packages/EasyErrorHandler/src/Bridge/Symfony/Verbose/IpAddressVerboseStrategyDriver.php
packages/EasyErrorHandler/src/Verbose/AbstractVerboseStrategyDriver.php
packages/EasyUtils/tests/EnvVarSubstitutionHelperTest.php

[EasyErrorHandler] Implement IP address verbose strategy driver

---

packages/EasyPagination/src/Bridge/Symfony/Resources/config/default_resolver.php

[EasyPagination] Fix symfony default resolver listener

---

packages/EasyRepository/src/Bridge/BridgeConstantsInterface.php
packages/EasyRepository/src/Bridge/Symfony/DependencyInjection/Compiler/SetPaginationOnRepositoryPass.php
packages/EasyRepository/src/Bridge/Symfony/DependencyInjection/EasyRepositoryExtension.php
packages/EasyRepository/src/Bridge/Symfony/EasyRepositorySymfonyBundle.php
packages/EasyRepository/src/Exceptions/AbstractEasyRepositoryException.php
packages/EasyRepository/src/Exceptions/EasyPaginationNotInstalledException.php
packages/EasyRepository/src/Implementations/Doctrine/ORM/AbstractOptimizedDoctrineOrmRepository.php
packages/EasyRepository/src/Implementations/Doctrine/ORM/AbstractPaginatedDoctrineOrmRepository.php
packages/EasyRepository/src/Implementations/Doctrine/ORM/DoctrineOrmRepositoryTrait.php
packages/EasyRepository/src/Implementations/Illuminate/AbstractEloquentRepository.php
packages/EasyRepository/src/Interfaces/DatabaseRepositoryInterface.php
packages/EasyRepository/src/Interfaces/EasyRepositoryExceptionInterface.php
packages/EasyRepository/src/Interfaces/ObjectRepositoryInterface.php
phpstan.neon

[EasyRepository] Create optimized doctrine orm repository

---

packages/EasyRepository/src/Implementations/Doctrine/ORM/AbstractOptimizedDoctrineOrmRepository.php

[EasyRepository] Fix save method to use persist on doctrine em

---

packages/EasyBugsnag/src/Bridge/BridgeConstantsInterface.php
packages/EasyBugsnag/src/Bridge/EasyUtils/Exceptions/EasyUtilsNotInstalledException.php
packages/EasyBugsnag/src/Bridge/EasyUtils/SensitiveDataConfigurator.php
packages/EasyBugsnag/src/Bridge/Laravel/EasyBugsnagServiceProvider.php
packages/EasyBugsnag/src/Bridge/Laravel/config/easy-bugsnag.php
packages/EasyBugsnag/src/Bridge/Symfony/DependencyInjection/Compiler/SensitiveDataCompilerPass.php
packages/EasyBugsnag/src/Bridge/Symfony/DependencyInjection/Configuration.php
packages/EasyBugsnag/src/Bridge/Symfony/DependencyInjection/EasyBugsnagExtension.php
packages/EasyBugsnag/src/Bridge/Symfony/EasyBugsnagSymfonyBundle.php
packages/EasyBugsnag/src/Bridge/Symfony/Resources/config/sensitive_data.php
packages/EasyBugsnag/src/Interfaces/EasyBugsnagExceptionInterface.php
packages/EasyBugsnag/tests/Bridge/Symfony/Fixtures/default_config.yaml
packages/EasyBugsnag/tests/Bridge/Symfony/Stubs/KernelStub.php

[EasyBugsnag] Add bridge for sensitive data sanitization

---

packages/EasyBugsnag/src/Bridge/BridgeConstantsInterface.php
packages/EasyBugsnag/src/Bridge/EasyUtils/SensitiveDataSanitizerConfigurator.php
packages/EasyBugsnag/src/Bridge/Laravel/EasyBugsnagServiceProvider.php
packages/EasyBugsnag/src/Bridge/Laravel/config/easy-bugsnag.php
packages/EasyBugsnag/src/Bridge/Symfony/DependencyInjection/Compiler/SensitiveDataCompilerPass.php
packages/EasyBugsnag/src/Bridge/Symfony/DependencyInjection/Configuration.php
packages/EasyBugsnag/src/Bridge/Symfony/DependencyInjection/EasyBugsnagExtension.php
packages/EasyBugsnag/src/Bridge/Symfony/Resources/config/sensitive_data_sanitizer.php
packages/EasyBugsnag/tests/Bridge/Symfony/Fixtures/default_config.yaml

[EasyBugsnag] Rename sensitive data to sensitive data sanitizer

---

packages/EasyBugsnag/src/Bridge/Symfony/DependencyInjection/Compiler/SensitiveDataSanitizerCompilerPass.php
packages/EasyBugsnag/src/Bridge/Symfony/EasyBugsnagSymfonyBundle.php
packages/EasyLogging/src/Bridge/BridgeConstantsInterface.php
packages/EasyLogging/src/Bridge/EasyUtils/Exceptions/EasyUtilsNotInstalledException.php
packages/EasyLogging/src/Bridge/EasyUtils/SensitiveDataSanitizerProcessor.php
packages/EasyLogging/src/Bridge/Laravel/EasyLoggingServiceProvider.php
packages/EasyLogging/src/Bridge/Laravel/config/easy-logging.php
packages/EasyLogging/src/Bridge/Symfony/DependencyInjection/Compiler/SensitiveDataSanitizerCompilerPass.php
packages/EasyLogging/src/Bridge/Symfony/DependencyInjection/Configuration.php
packages/EasyLogging/src/Bridge/Symfony/DependencyInjection/EasyLoggingExtension.php
packages/EasyLogging/src/Bridge/Symfony/EasyLoggingSymfonyBundle.php
packages/EasyLogging/src/Interfaces/EasyLoggingExceptionInterface.php
packages/EasyLogging/tests/Bridge/Symfony/Fixtures/default_config.yaml
packages/EasyLogging/tests/Bridge/Symfony/Stubs/KernelStub.php

[EasyLogging] Implement sensitive data sanitizer

---

packages/EasyPagination/src/Traits/DatabaseCommonPaginatorTrait.php
packages/EasyPagination/src/Traits/DoctrineCommonPaginatorTrait.php
packages/EasyPagination/src/Traits/DoctrineDbalPaginatorTrait.php
packages/EasyPagination/src/Traits/DoctrineOrmPaginatorTrait.php
packages/EasyPagination/src/Traits/EloquentPaginatorTrait.php

[EasyPagination] Allow list of criteria callables on paginator instead of one

---

packages/EasyBatch/src/Bridge/Symfony/DependencyInjection/Compiler/AddMessengerMiddlewareToBusesCompilerPass.php
packages/EasyBatch/src/Bridge/Symfony/EasyBatchSymfonyBundle.php

[EasyBatch] Register messenger middleware automatically

---

packages/EasyBatch/src/Bridge/Symfony/DependencyInjection/Compiler/AddMessengerMiddlewareToBusesCompilerPass.php
packages/EasyBatch/src/Bridge/Symfony/EasyBatchSymfonyBundle.php
packages/EasyBatch/src/Bridge/Symfony/Resources/config/services.php

[EasyBatch] Fix symfony bridge for messenger middleware auto register

---

packages/EasyBatch/src/Repositories/BatchItemRepository.php
phpstan.neon

[EasyBatch] Fix BatchItemRepository::updateStatusToPending()

---

packages/EasyBatch/src/Bridge/Symfony/Messenger/BatchItemExceptionHandler.php
packages/EasyBatch/src/Exceptions/BatchCancelledException.php
packages/EasyBatch/src/Exceptions/BatchItemCannotBeRetriedException.php
packages/EasyBatch/src/Exceptions/BatchItemCompletedException.php
packages/EasyBatch/src/Interfaces/EasyBatchPreventProcessExceptionInterface.php

[EasyBatch] Do not bubble up prevent process exceptions anymore

---

packages/EasyPagination/src/Interfaces/ExtendablePaginatorInterface.php
packages/EasyPagination/src/Paginators/DoctrineDbalLengthAwarePaginator.php
packages/EasyPagination/src/Paginators/DoctrineDbalPaginator.php
packages/EasyPagination/src/Paginators/DoctrineOrmLengthAwarePaginator.php
packages/EasyPagination/src/Paginators/DoctrineOrmPaginator.php
packages/EasyPagination/src/Paginators/EloquentLengthAwarePaginator.php
packages/EasyPagination/src/Paginators/EloquentPaginator.php
packages/EasyPagination/src/Paginators/IterableLengthAwarePaginator.php
packages/EasyPagination/src/Paginators/IterablePaginator.php
phpstan.neon

[EasyPagination] Implement ExtendablePaginatorInterface

---

packages/EasyBatch/src/BatchObjectManager.php
packages/EasyBatch/src/Bridge/Doctrine/DbalStatementsProvider.php
packages/EasyBatch/src/Bridge/Symfony/Messenger/BatchItemExceptionHandler.php
packages/EasyBatch/src/Bridge/Symfony/Messenger/Emergency/ProcessBatchForBatchItemHandler.php
packages/EasyBatch/src/Bridge/Symfony/Messenger/Emergency/ProcessBatchForBatchItemMessage.php
packages/EasyBatch/src/Bridge/Symfony/Messenger/Emergency/UpdateBatchItemHandler.php
packages/EasyBatch/src/Bridge/Symfony/Messenger/Emergency/UpdateBatchItemMessage.php
packages/EasyBatch/src/Exceptions/BatchItemProcessedButNotSavedException.php
packages/EasyBatch/src/Exceptions/BatchItemSavedButBatchNotProcessedException.php
packages/EasyBatch/src/Interfaces/BatchItemInterface.php
packages/EasyBatch/src/Interfaces/BatchItemRepositoryInterface.php
packages/EasyBatch/src/Interfaces/BatchObjectInterface.php
packages/EasyBatch/src/Interfaces/EasyBatchEmergencyExceptionInterface.php
packages/EasyBatch/src/Iterator/BatchItemIterator.php
packages/EasyBatch/src/Iterator/IteratorConfig.php
packages/EasyBatch/src/Objects/AbstractBatchObject.php
packages/EasyBatch/src/Processors/BatchItemProcessor.php
packages/EasyBatch/src/Repositories/BatchItemRepository.php
packages/EasyBatch/tests/Repositories/BatchItemRepositoryTest.php
packages/EasyPagination/src/Traits/DoctrineDbalPaginatorTrait.php
phpstan.neon

[EasyBatch] Fix database interactions

---

packages/EasyBatch/src/BatchObjectManager.php
packages/EasyBatch/src/Bridge/Doctrine/DbalStatementsProvider.php
packages/EasyBatch/src/Bridge/Symfony/Messenger/BatchItemExceptionHandler.php
packages/EasyBatch/src/Bridge/Symfony/Messenger/Emergency/ProcessBatchForBatchItemHandler.php
packages/EasyBatch/src/Bridge/Symfony/Messenger/Emergency/ProcessBatchForBatchItemMessage.php
packages/EasyBatch/src/Bridge/Symfony/Messenger/Emergency/UpdateBatchItemHandler.php
packages/EasyBatch/src/Bridge/Symfony/Messenger/Emergency/UpdateBatchItemMessage.php
packages/EasyBatch/src/Exceptions/BatchItemProcessedButNotSavedException.php
packages/EasyBatch/src/Exceptions/BatchItemSavedButBatchNotProcessedException.php
packages/EasyBatch/src/Interfaces/BatchItemInterface.php
packages/EasyBatch/src/Interfaces/BatchItemRepositoryInterface.php
packages/EasyBatch/src/Interfaces/BatchObjectInterface.php
packages/EasyBatch/src/Interfaces/EasyBatchEmergencyExceptionInterface.php
packages/EasyBatch/src/Iterator/BatchItemIterator.php
packages/EasyBatch/src/Iterator/IteratorConfig.php
packages/EasyBatch/src/Objects/AbstractBatchItem.php
packages/EasyBatch/src/Objects/AbstractBatchObject.php
packages/EasyBatch/src/Processors/BatchItemProcessor.php
packages/EasyBatch/src/Processors/BatchProcessor.php
packages/EasyBatch/src/Repositories/BatchItemRepository.php
packages/EasyBatch/tests/Repositories/BatchItemRepositoryTest.php
packages/EasyPagination/src/Traits/DoctrineDbalPaginatorTrait.php
phpstan.neon

[EasyBatch] Fix process batch item dependent objects

---

packages/EasyBatch/src/BatchObjectManager.php

[EasyBatch] Fix batch item attempts on approve and cancel

---

packages/EasyBatch/src/Processors/BatchItemProcessor.php

[EasyBatch] Fix update batch item emergency flow

---

packages/EasyBatch/src/Bridge/Symfony/DependencyInjection/Compiler/MakeMessengerReceiversPublicCompilerPass.php
packages/EasyBatch/src/Bridge/Symfony/EasyBatchSymfonyBundle.php
packages/EasyBatch/src/Bridge/Symfony/Messenger/BatchItemExceptionHandler.php

[EasyBatch] Fix emergency transport name

---

packages/EasyBatch/src/BatchManager.php
packages/EasyBatch/src/Bridge/Symfony/Resources/config/services.php
packages/EasyBatch/src/Interfaces/BatchManagerInterface.php

[EasyBatch] Implement BatchManagerInterface for BC compatibility

---

packages/EasyAsync/src/Bridge/BridgeConstantsInterface.php
packages/EasyAsync/src/Bridge/EasyErrorHandler/WorkerStoppingListener.php
packages/EasyAsync/src/Bridge/Symfony/DependencyInjection/Compiler/RegisterMessengerMiddlewareCompilerPass.php
packages/EasyAsync/src/Bridge/Symfony/DependencyInjection/Configuration.php
packages/EasyAsync/src/Bridge/Symfony/DependencyInjection/EasyAsyncExtension.php
packages/EasyAsync/src/Bridge/Symfony/EasyAsyncSymfonyBundle.php

[EasyAsync] Auto register Symfony Messenger middleware

---

packages/EasyLock/src/Bridge/BridgeConstantsInterface.php
packages/EasyLock/src/Bridge/Symfony/DependencyInjection/Compiler/RegisterMessengerMiddlewareCompilerPass.php
packages/EasyLock/src/Bridge/Symfony/DependencyInjection/Configuration.php
packages/EasyLock/src/Bridge/Symfony/DependencyInjection/EasyLockExtension.php
packages/EasyLock/src/Bridge/Symfony/EasyLockSymfonyBundle.php

[EasyLock] Auto register Symfony Messenger middleware

---

composer.json
packages/EasyEncryption/composer.json

[EasyEncryption] Support Halite v5

---

packages/EasyLogging/composer.json
packages/EasyLogging/src/Bridge/BridgeConstantsInterface.php

[EasyLogging] Fix bridge constant for sensitive data sanitizer

---

packages/EasyBugsnag/src/Bridge/Laravel/config/easy-bugsnag.php
packages/EasyBugsnag/src/Bridge/Symfony/DependencyInjection/Configuration.php
packages/EasyBugsnag/src/Configurators/AwsEcsFargateConfigurator.php

[EasyBugsnag] Fix AWS Fargate configurator

---

packages/EasyAsync/src/Bridge/Symfony/Messenger/Serializer/MessageSerializer.php

[EasyAsync] Fix MessageSerializer.php stamps in case of error

---

packages/EasySecurity/src/Authorization/Role.php
packages/EasySecurity/src/Interfaces/Authorization/RoleInterface.php
packages/EasySecurity/src/Interfaces/SecurityContextInterface.php
packages/EasySecurity/src/SecurityContext.php
packages/EasySecurity/tests/Authorization/RoleTest.php
packages/EasySecurity/tests/SecurityContextTest.php

[EasySecurity] Improve Role metadata + SecurityContext roles and permissions functions

---

packages/EasySecurity/src/Bridge/Laravel/EasySecurityServiceProvider.php
packages/EasySecurity/src/Configurators/FromRequestConfigurator.php
packages/EasySecurity/src/SecurityContextResolver.php

[EasySecurity] Create authorization matrix only when needed

---

composer.json
packages/EasyHttpClient/composer.json
packages/EasyHttpClient/src/Bridge/BridgeConstantsInterface.php
packages/EasyHttpClient/src/Bridge/Symfony/DependencyInjection/Compiler/AbstractEasyHttpClientCompilerPass.php
packages/EasyHttpClient/src/Bridge/Symfony/DependencyInjection/Compiler/DecorateDefaultClientPass.php
packages/EasyHttpClient/src/Bridge/Symfony/DependencyInjection/Compiler/DecorateEasyWebhookClientPass.php
packages/EasyHttpClient/src/Bridge/Symfony/DependencyInjection/Compiler/DecorateMessengerSqsClientPass.php
packages/EasyHttpClient/src/Bridge/Symfony/DependencyInjection/Configuration.php
packages/EasyHttpClient/src/Bridge/Symfony/DependencyInjection/EasyHttpClientExtension.php
packages/EasyHttpClient/src/Bridge/Symfony/EasyHttpClientSymfonyBundle.php
packages/EasyHttpClient/src/Bridge/Symfony/Messenger/AmazonSqsTransportFactory.php

[EasyHttpClient] Use default http client for SQS transport

---

packages/EasyBugsnag/src/Interfaces/ValueOptionInterface.php
packages/EasyBugsnag/src/Request/AbstractRequestResolver.php

[EasyBugsnag] Allow to resolve request in cli

---

packages/EasySecurity/src/Bridge/Symfony/Resources/config/services.php

Now don't use AuthorizationMatrix as a service.

[EasySecurity] Remove AuthorizationMatrix setup

---

composer.json
packages/EasySwoole/.gitignore
packages/EasySwoole/composer.json
packages/EasySwoole/license
packages/EasySwoole/phpunit.xml
packages/EasySwoole/readme.md
packages/EasySwoole/src/AbstractApplicationStateChecker.php
packages/EasySwoole/src/AbstractApplicationStateResetter.php
packages/EasySwoole/src/Bridge/BridgeConstantsInterface.php
packages/EasySwoole/src/Bridge/Doctrine/Orm/ManagersChecker.php
packages/EasySwoole/src/Bridge/Doctrine/Orm/ManagersResetter.php
packages/EasySwoole/src/Bridge/Symfony/DependencyInjection/Configuration.php
packages/EasySwoole/src/Bridge/Symfony/DependencyInjection/EasySwooleExtension.php
packages/EasySwoole/src/Bridge/Symfony/EasySwooleSymfonyBundle.php
packages/EasySwoole/src/Bridge/Symfony/Listeners/ApplicationStateCheckListener.php
packages/EasySwoole/src/Bridge/Symfony/Listeners/ApplicationStateResetListener.php
packages/EasySwoole/src/Bridge/Symfony/Resources/config/doctrine.php
packages/EasySwoole/src/Bridge/Symfony/Resources/config/services.php
packages/EasySwoole/src/Helpers/EasySwooleEnabledHelper.php
packages/EasySwoole/src/Helpers/HttpFoundationHelper.php
packages/EasySwoole/src/Interfaces/ApplicationStateCheckerInterface.php
packages/EasySwoole/src/Interfaces/ApplicationStateResetterInterface.php
packages/EasySwoole/src/Interfaces/RequestAttributesInterface.php
packages/EasySwoole/src/Runtime/EasySwooleRunner.php
packages/EasySwoole/src/Runtime/EasySwooleRuntime.php
packages/EasySwoole/tests/AbstractTestCase.php
packages/EasySwoole/tests/Bridge/Symfony/AbstractSymfonyTestCase.php
packages/EasySwoole/tests/Bridge/Symfony/EasySwooleSymfonyBundleTest.php
packages/EasySwoole/tests/Bridge/Symfony/Fixtures/config/default.yaml
packages/EasySwoole/tests/Bridge/Symfony/Stubs/KernelStub.php

[EasySwoole] Create package with doctrine bridge

---

packages/EasySwoole/composer.json

[EasySwoole] Fix dependencies

---

packages/EasySecurity/src/Bridge/EasyBugsnag/SecurityContextClientConfigurator.php

[EasySecurity] Handle exceptions in easy-bugsnag bridge

---

composer.json
packages/EasySwoole/composer.json
packages/EasySwoole/src/AppStateCheckers/AbstractAppStateChecker.php
packages/EasySwoole/src/AppStateCheckers/RequestLimitsChecker.php
packages/EasySwoole/src/AppStateResetters/AbstractAppStateResetter.php
packages/EasySwoole/src/Bridge/BridgeConstantsInterface.php
packages/EasySwoole/src/Bridge/Doctrine/Orm/ManagersChecker.php
packages/EasySwoole/src/Bridge/Doctrine/Orm/ManagersResetter.php
packages/EasySwoole/src/Bridge/Symfony/DependencyInjection/Configuration.php
packages/EasySwoole/src/Bridge/Symfony/DependencyInjection/EasySwooleExtension.php
packages/EasySwoole/src/Bridge/Symfony/Listeners/ApplicationStateCheckListener.php
packages/EasySwoole/src/Bridge/Symfony/Listeners/ApplicationStateResetListener.php
packages/EasySwoole/src/Bridge/Symfony/Resources/config/request_limits.php
packages/EasySwoole/src/Interfaces/AppStateCheckerInterface.php
packages/EasySwoole/src/Interfaces/AppStateResetterInterface.php
packages/EasySwoole/src/Runtime/EasySwooleRunner.php
packages/EasySwoole/src/Runtime/EasySwooleRuntime.php

[EasySwoole] Start server + Implement request limits per worker

---

packages/EasySwoole/src/Runtime/EasySwooleRuntime.php

[EasySwoole] Implement eonx-com/easy-bugsnag bridge

---

packages/EasySwoole/src/Runtime/EasySwooleRuntime.php

[EasySwoole] Add default static handler settings

---

packages/EasyBugsnag/src/Bridge/Symfony/DependencyInjection/Compiler/SensitiveDataSanitizerCompilerPass.php
packages/EasyLogging/src/Bridge/Symfony/DependencyInjection/Compiler/DefaultStreamHandlerPass.php
packages/EasyLogging/src/Bridge/Symfony/DependencyInjection/Compiler/SensitiveDataSanitizerCompilerPass.php
packages/EasyUtils/src/SensitiveData/SensitiveDataSanitizer.php

[EasyLogging][EasyBugsnag][EasyUtil] Fix sensitive data sanitizer setup

---

packages/EasySwoole/src/AccessLog/HttpFoundationAccessLogFormatter.php
packages/EasySwoole/src/AccessLog/MonologLoggerFactory.php
packages/EasySwoole/src/Bridge/Symfony/Resources/config/access_log.php
packages/EasySwoole/src/Runtime/EasySwooleRuntime.php

[EasySwoole] Fix access log integration

---

ecs.php

[ECS] Update ECS configuration

---

ecs.php
packages/EasyCore/src/Csv/CsvWithHeadersParserInterface.php
packages/EasyUtils/src/Bridge/Laravel/EasyUtilsServiceProvider.php
packages/EasyUtils/src/Bridge/Symfony/Resources/config/services.php
packages/EasyUtils/src/Csv/CsvContentsProviderInterface.php
packages/EasyUtils/src/Csv/CsvParserConfig.php
packages/EasyUtils/src/Csv/CsvParserConfigInterface.php
packages/EasyUtils/src/Csv/CsvWithHeadersParser.php
packages/EasyUtils/src/Csv/CsvWithHeadersParserInterface.php
packages/EasyUtils/src/Csv/Exceptions/InvalidCsvFilenameException.php
packages/EasyUtils/src/Csv/Exceptions/MissingRequiredHeadersException.php
packages/EasyUtils/src/Csv/Exceptions/MissingValueForRequiredHeadersException.php
packages/EasyUtils/src/Csv/FromFileCsvContentsProvider.php
packages/EasyUtils/src/Exceptions/AbstractEasyUtilsException.php
packages/EasyUtils/tests/Csv/CsvWithHeadersParserTest.php
packages/EasyUtils/tests/Csv/fixtures/empty_values.csv
packages/EasyUtils/tests/Csv/fixtures/group_prefixes.csv
packages/EasyUtils/tests/Csv/fixtures/hidden_characters.csv
packages/EasyUtils/tests/Csv/fixtures/missing_value_for_required_header.csv
packages/EasyUtils/tests/Csv/fixtures/simple_file.csv

[EasyUtils] Move CSV parser to eonx-com/easy-utils

---

packages/EasyUtils/src/Csv/CsvParserConfig.php
packages/EasyUtils/src/Csv/CsvParserConfigInterface.php
packages/EasyUtils/src/Csv/CsvWithHeadersParser.php
packages/EasyUtils/tests/Csv/CsvWithHeadersParserTest.php
packages/EasyUtils/tests/Csv/fixtures/empty_records.csv

[EasyUtils] Allow to ignore empty records

---

packages/EasyUtils/src/Csv/CsvParserConfig.php
packages/EasyUtils/src/Csv/CsvParserConfigInterface.php
packages/EasyUtils/src/Csv/CsvWithHeadersParser.php
packages/EasyUtils/tests/Csv/CsvWithHeadersParserTest.php
packages/EasyUtils/tests/Csv/fixtures/simple_file.csv

[EasyUtils] Implement csv record transformers

---

packages/EasyBatch/src/Bridge/Symfony/Messenger/ProcessBatchItemMiddleware.php
packages/EasyBatch/src/Interfaces/CurrentBatchAwareInterface.php
packages/EasyBatch/src/Interfaces/CurrentBatchItemAwareInterface.php
packages/EasyBatch/src/Interfaces/CurrentBatchObjectsAwareInterface.php
packages/EasyBatch/src/Traits/CurrentBatchObjectsAwareTrait.php

[EasyBatch] Unset current batch objects on message after processing it

---

packages/EasyBatch/src/BatchObjectManager.php
packages/EasyBatch/src/Interfaces/BatchItemRepositoryInterface.php
packages/EasyBatch/src/Interfaces/BatchObjectManagerInterface.php
packages/EasyBatch/src/Processors/BatchProcessor.php
packages/EasyBatch/src/Repositories/BatchCountsDto.php
packages/EasyBatch/src/Repositories/BatchItemRepository.php
packages/EasyBatch/src/Repositories/BatchRepository.php
packages/EasyBatch/tests/Bridge/Symfony/AbstractSymfonyTestCase.php
packages/EasyBatch/tests/Bridge/Symfony/EasyBatchSymfonyBundleTest.php
packages/EasyBatch/tests/Repositories/BatchItemRepositoryTest.php

[EasyBatch] Allow to restore batch state

---

ecs.php
packages/EasyErrorHandler/src/Bridge/BridgeConstantsInterface.php
packages/EasyErrorHandler/src/Bridge/Bugsnag/ErrorDetailsClientConfigurator.php
packages/EasyErrorHandler/src/Bridge/Laravel/Provider/EasyErrorHandlerServiceProvider.php
packages/EasyErrorHandler/src/Bridge/Laravel/Translator.php
packages/EasyErrorHandler/src/Bridge/Laravel/config/easy-error-handler.php
packages/EasyErrorHandler/src/Bridge/Symfony/DependencyInjection/Compiler/ErrorRendererCompilerPass.php
packages/EasyErrorHandler/src/Bridge/Symfony/DependencyInjection/Configuration.php
packages/EasyErrorHandler/src/Bridge/Symfony/DependencyInjection/EasyErrorHandlerExtension.php
packages/EasyErrorHandler/src/Bridge/Symfony/EasyErrorHandlerSymfonyBundle.php
packages/EasyErrorHandler/src/Bridge/Symfony/ErrorRenderer/TranslateInternalErrorMessageErrorRenderer.php
packages/EasyErrorHandler/src/Bridge/Symfony/Messenger/ReportErrorEventListener.php
packages/EasyErrorHandler/src/Bridge/Symfony/Resources/config/services.php
packages/EasyErrorHandler/src/Bridge/Symfony/Translator.php
packages/EasyErrorHandler/src/ErrorDetailsResolver.php
packages/EasyErrorHandler/src/Interfaces/ErrorDetailsResolverInterface.php
packages/EasyErrorHandler/src/Interfaces/TranslatorInterface.php
packages/EasyErrorHandler/src/Reporters/LoggerReporter.php
packages/EasyErrorHandler/tests/ErrorDetailsResolverTest.php
packages/EasyErrorHandler/tests/Stubs/TranslatorStub.php

[EasyErrorHandler] Translate internal error messages

---

packages/EasyBatch/src/Exceptions/BatchObjectNotSavedException.php
packages/EasyBatch/src/Repositories/AbstractBatchObjectRepository.php
packages/EasyBatch/tests/Bridge/Symfony/EasyBatchSymfonyBundleTest.php
packages/EasyBatch/tests/Bridge/Symfony/EasyBatchTestContext.php

[EasyBatch] Add more checks around db interactions

---

packages/EasyTest/config/services.yaml
packages/EasyTest/src/Stub/HttpClient/HttpClientAssertTrait.php
packages/EasyTest/src/Stub/HttpClient/HttpClientAssertionTrait.php
packages/EasyTest/src/Stub/HttpClient/HttpClientRequestStub.php
packages/EasyTest/src/Stub/HttpClient/HttpClientStub.php
phpstan.neon

- [EasyTest] Add HttpClient stubs.

[EasyTest] Add HttpClient stubs.

---

packages/EasySwoole/src/Bridge/Symfony/AppStateResetters/SymfonyServicesAppStateResetter.php
packages/EasySwoole/src/Bridge/Symfony/DependencyInjection/Configuration.php
packages/EasySwoole/src/Bridge/Symfony/DependencyInjection/EasySwooleExtension.php
packages/EasySwoole/src/Bridge/Symfony/Resources/config/reset_services.php
packages/EasySwoole/tests/Bridge/Symfony/Stubs/KernelStub.php
packages/EasySwoole/tests/Bridge/Symfony/Stubs/ServicesResetterStub.php

[EasySwoole] Reset Symfony services

---

packages/EasyErrorHandler/src/Bridge/Symfony/Listener/ExceptionEventListener.php
packages/EasyErrorHandler/src/ErrorHandler.php
packages/EasyErrorHandler/src/Interfaces/FormatAwareInterface.php
packages/EasyErrorHandler/src/Response/ErrorResponseFactory.php

[EasyErrorHandler] Improve error response format handling

---

packages/EasyActivity/src/Resolvers/DefaultActivitySubjectResolver.php

- fixed bug with proxy classes

[EasyActivity] Fixed bug with doctrine proxy

---

packages/EasySwoole/src/Helpers/HttpFoundationHelper.php
packages/EasySwoole/src/Runtime/EasySwooleRunner.php

[EasySwoole] Improve HTTP response handling

---

packages/EasySwoole/src/Helpers/HttpFoundationHelper.php

[EasySwoole] Fix swoole response cookie implementation

---

packages/EasySwoole/src/Bridge/Symfony/Listeners/AbstractRequestEventListener.php
packages/EasySwoole/src/Bridge/Symfony/Listeners/TrustedProxiesListener.php
packages/EasySwoole/src/Bridge/Symfony/Resources/config/services.php
packages/EasySwoole/tests/Bridge/Symfony/Stubs/KernelStub.php

[EasySwoole] Fix support for REMOTE_ADDR in trusted proxies

---

packages/EasyDoctrine/src/Bridge/Symfony/DependencyInjection/Configuration.php
packages/EasyDoctrine/src/Bridge/Symfony/DependencyInjection/EasyDoctrineExtension.php

[EasyDoctrine] Add trick to disable RDS IAM in CLI

---

packages/EasyDoctrine/src/Bridge/Symfony/DependencyInjection/Configuration.php

[EasyDoctrine] Change default AWS RDS IAM username to disabled

---

packages/EasyDoctrine/src/Bridge/Symfony/Aws/Rds/AuthTokenConnectionFactory.php
packages/EasyDoctrine/src/Bridge/Symfony/DependencyInjection/Configuration.php
packages/EasyDoctrine/src/Bridge/Symfony/DependencyInjection/EasyDoctrineExtension.php

[EasyDoctrine] Add way to disable AWS RDS IAM using env var

---

packages/EasySwoole/src/Bridge/BridgeConstantsInterface.php
packages/EasySwoole/src/Bridge/Symfony/DependencyInjection/Configuration.php
packages/EasySwoole/src/Bridge/Symfony/DependencyInjection/EasySwooleExtension.php
packages/EasySwoole/src/Bridge/Symfony/Listeners/StaticPhpFileListener.php
packages/EasySwoole/src/Bridge/Symfony/Resources/config/static_php_files.php
packages/EasySwoole/tests/Bridge/Symfony/ConfigurationTest.php
packages/EasyUtils/src/Helpers/ArrayHelper.php

[EasySwoole] Support for static PHP files

---

packages/EasyDoctrine/src/Bridge/Symfony/Aws/Rds/AuthTokenConnectionFactory.php

[EasyDoctrine] Use AWS username as db username for RDS IAM

---

packages/EasySwoole/src/Runtime/EasySwooleRuntime.php

[EasySwoole] Define default for reactor_num

---

packages/EasySwoole/src/Runtime/EasySwooleRunner.php

[EasySwoole] Add prefix to output

---

packages/EasyCore/src/Bridge/Symfony/ApiPlatform/DataPersister/ChainSimpleDataPersister.php
packages/EasyCore/src/Bridge/Symfony/ApiPlatform/DataPersister/TraceableChainSimpleDataPersister.php

[EasyCore] Actually implement reset method on simple data persisters

---

packages/EasySwoole/composer.json
packages/EasySwoole/src/Bridge/Symfony/Listeners/AbstractExceptionEventListener.php
packages/EasySwoole/src/Bridge/Symfony/Listeners/SwooleDdListener.php
packages/EasySwoole/src/Bridge/Symfony/Resources/config/services.php
packages/EasySwoole/src/Exceptions/SwooleDdException.php
packages/EasySwoole/src/Helpers/VarDumpHelper.php
packages/EasySwoole/src/Resources/functions/dump.php
phpstan.neon

[EasySwoole] Implement swoole_dump and swoole_dd

---

packages/EasySwoole/src/Bridge/Monolog/SimpleFormatter.php
packages/EasySwoole/src/Helpers/OutputHelper.php
packages/EasySwoole/src/Runtime/EasySwooleRunner.php
packages/EasySwoole/tests/Helpers/OutputHelperTest.php
phpstan.neon

[EasySwoole] Implement hot reload

---

packages/EasySwoole/src/Bridge/Monolog/SimpleFormatter.php
packages/EasySwoole/src/Runtime/EasySwooleRunner.php

[EasySwoole] Improve output management

---

packages/EasySwoole/src/Helpers/HttpFoundationHelper.php

[EasySwoole] Replicate PHP BasicAuth logic

---

packages/EasyApiToken/src/Bridge/Symfony/Providers/AbstractFirewallAwareDecoderProvider.php
packages/EasyApiToken/src/Bridge/Symfony/Resources/config/services.php
packages/EasyApiToken/src/Factories/ApiTokenDecoderFactory.php
packages/EasyApiToken/src/Interfaces/Factories/ApiTokenDecoderFactoryInterface.php
packages/EasySecurity/src/Bridge/Laravel/EasySecurityServiceProvider.php
packages/EasySecurity/src/Bridge/Symfony/Resources/config/default_configurators.php
packages/EasySecurity/src/Bridge/Symfony/Resources/config/services.php
packages/EasySecurity/src/Configurators/ApiTokenConfigurator.php

[EasyApiToken] Allow to reset api token decoder factory

---

packages/EasyHttpClient/src/Implementations/Symfony/WithEventsHttpClient.php

[EasyHttpClient] Support exceptions from chunks

---

packages/EasyDoctrine/src/Bridge/Symfony/Aws/Rds/AuthTokenConnectionFactory.php
packages/EasyDoctrine/src/Bridge/Symfony/Aws/Rds/RdsIamConnection.php
packages/EasySwoole/src/Bridge/Doctrine/Orm/ManagersResetter.php
phpstan.neon

[EasyDoctrine] Delegate rds iam password generation to connection class

---

packages/EasySwoole/src/Bridge/Doctrine/Orm/ManagersChecker.php

[EasySwoole] Check if db connection open before testing it

---

packages/EasyLock/src/Interfaces/LockDataInterface.php
packages/EasyLock/src/LockData.php
packages/EasyLock/tests/LockDataTest.php

[EasyLock] Allow to update existing LockData

---

packages/EasySwoole/src/Bridge/BridgeConstantsInterface.php
packages/EasySwoole/src/Bridge/Doctrine/Orm/ManagersResetter.php
packages/EasySwoole/src/Bridge/Symfony/DependencyInjection/Configuration.php
packages/EasySwoole/src/Bridge/Symfony/DependencyInjection/EasySwooleExtension.php
packages/EasySwoole/src/Bridge/Symfony/Resources/config/doctrine.php
packages/EasySwoole/tests/Bridge/Symfony/ConfigurationTest.php

[EasySwoole] Add config for doctrine dbal connections reset

---

packages/EasySwoole/src/AppStateInitializers/AbstractAppStateInitializer.php
packages/EasySwoole/src/Bridge/BridgeConstantsInterface.php
packages/EasySwoole/src/Bridge/Doctrine/Orm/ManagerConnectionsInitializer.php
packages/EasySwoole/src/Bridge/Doctrine/Orm/ManagersChecker.php
packages/EasySwoole/src/Bridge/Symfony/DependencyInjection/EasySwooleExtension.php
packages/EasySwoole/src/Bridge/Symfony/Listeners/ApplicationStateInitListener.php
packages/EasySwoole/src/Bridge/Symfony/Resources/config/doctrine.php
packages/EasySwoole/src/Bridge/Symfony/Resources/config/services.php
packages/EasySwoole/src/Interfaces/AppStateInitializerInterface.php

[EasySwoole] Improve doctrine dbal connections management

---

packages/EasySwoole/src/Runtime/EasySwooleRunner.php

[EasySwoole] Improve hot reload setup

---

packages/EasyErrorHandler/src/Bridge/Symfony/Resources/config/bugsnag_reporter.php
packages/EasyErrorHandler/src/Bridge/Symfony/Resources/config/services.php

[EasyErrorHandler] Fix Bugsnag configuration

---

packages/EasySwoole/src/Helpers/HttpFoundationHelper.php

[EasySwoole] Prevent issues with empty uploaded files

---

packages/EasyTest/src/Trait/Messenger/MessengerAssertionsTrait.php
packages/EasyTest/src/Traits/MessengerAssertionsTrait.php

[EasyTest] Add MessengerAssertionsTrait

---

packages/EasySchedule/src/Bridge/Symfony/DataCollector/ScheduleDataCollector.php

[EasySchedule] Fix data collector getters

---

packages/EasySwoole/composer.json
packages/EasySwoole/src/Runtime/EasySwooleRuntime.php
phpstan.neon

[EasySwoole] Allow individual setting to be defined using env variables

---

packages/EasyLock/composer.json

With the lover version, it causes bugs in tests.
Please see https://github.com/dmaicher/doctrine-test-bundle/pull/224

[EasyLock] Add conflict package

---

.github/workflows/php-ci.yml
packages/EasySwoole/src/Runtime/EasySwooleRuntime.php

[EasySwoole] Improve env vars substitution in runtime

---

packages/EasySwoole/src/Runtime/EasySwooleRuntime.php

[EasySwoole] Support multiple env files

---

packages/EasyActivity/composer.json
packages/EasyActivity/src/Bridge/Symfony/Messenger/ActivityLogEntryMessage.php

[EasyActivity] ActivityLogEntryMessage does not implement WithLockDataInterface

---

packages/EasyCore/src/Bridge/Symfony/ApiPlatform/Command/ApiResourceAndSimpleDataPersisterMaker.php
packages/EasyCore/src/Bridge/Symfony/DependencyInjection/EasyCoreExtension.php

[EasyCore] Added support of API Platform v2.7

---

packages/EasyErrorHandler/src/Bridge/Symfony/Builder/ApiPlatformBuilderProvider.php
packages/EasyErrorHandler/src/Bridge/Symfony/Builder/ApiPlatformValidationExceptionResponseBuilder.php

[EasyErrorHandler] Added support of API Platform v2.7

---

packages/EasySwoole/src/Helpers/EnvVarHelper.php
packages/EasySwoole/src/Runtime/EasySwooleRuntime.php

[EasySwoole] Support JSON env vars for secrets

---

packages/EasyBatch/src/Bridge/Symfony/Messenger/BatchItemExceptionHandler.php
packages/EasyBatch/src/Bridge/Symfony/Messenger/ProcessBatchItemMiddleware.php
packages/EasyBatch/src/Exceptions/AbstractEasyBatchException.php
packages/EasyBatch/src/Exceptions/BatchItemNotHandledException.php
packages/EasyBatch/src/Interfaces/EasyBatchExceptionInterface.php

[EasyBatch] Error when batch item not handled

---

packages/EasyBatch/src/Processors/BatchProcessor.php

[EasyBatch] Update batch counts only when required

---

packages/EasyBatch/src/Bridge/Symfony/Messenger/ProcessBatchItemMiddleware.php

[EasyBatch] Use new envelope for not handled logic

---

packages/EasyBatch/src/Bridge/Symfony/Messenger/ProcessBatchItemMiddleware.php

[EasyBatch] Check handled stamp only when consumed by worker

---

packages/EasyErrorHandler/src/Bridge/Symfony/Builder/ApiPlatformValidationErrorResponseBuilder.php

[EasyErrorHandler] Fix ApiPlatformValidationErrorResponseBuilder for API Platform 2.7

---

packages/EasyDoctrine/src/Bridge/Symfony/Aws/Rds/AuthTokenConnectionFactory.php

[EasyDoctrine] Allow different AWS RDS configs per connection

---

packages/EasyErrorHandler/src/Bridge/Symfony/Builder/ApiPlatformValidationErrorResponseBuilder.php
packages/EasyErrorHandler/src/Bridge/Symfony/Builder/ApiPlatformValidationExceptionResponseBuilder.php

[EasyErrorHandler] Fix phpstan

---

packages/EasyBugsnag/src/Bridge/Laravel/EasyBugsnagServiceProvider.php

| Fixed tickets | https://eonx.atlassian.net/browse/PRO-12832
Will fix this issue when installing on a Laravel project

[EasyBugsnag] Move resolving of queue in boot method instead of register in the laravel service provider of easy bugsnag. 

---

packages/EasyActivity/phpunit.xml
packages/EasyApiPlatform/phpunit.xml
packages/EasyApiToken/phpunit.xml
packages/EasyAsync/phpunit.xml
packages/EasyAwsCredentialsFinder/phpunit.xml
packages/EasyBankFiles/phpunit.xml
packages/EasyBatch/phpunit.xml
packages/EasyBugsnag/phpunit.xml
packages/EasyCore/phpunit.xml
packages/EasyDecision/phpunit.xml
packages/EasyDoctrine/phpunit.xml
packages/EasyEventDispatcher/phpunit.xml
packages/EasyHttpClient/phpunit.xml
packages/EasyLock/phpunit.xml
packages/EasyLogging/phpunit.xml
packages/EasyNotification/phpunit.xml
packages/EasyPagination/phpunit.xml
packages/EasyPipeline/phpunit.xml
packages/EasyPsr7Factory/phpunit.xml
packages/EasyRandom/phpunit.xml
packages/EasyRepository/phpunit.xml
packages/EasyRequestId/phpunit.xml
packages/EasySecurity/phpunit.xml
packages/EasySsm/phpunit.xml
packages/EasySwoole/phpunit.xml
packages/EasyTemplatingBlock/phpunit.xml
packages/EasyTest/phpunit.xml
packages/EasyUtils/phpunit.xml
packages/EasyWebhook/phpunit.xml
phpunit.xml

Update phpunit config to new format

---

packages/EasyApiToken/src/Decoders/BearerTokenDecoder.php
packages/EasyApiToken/src/External/Auth0JwtDriver.php
packages/EasyApiToken/tests/AbstractAuth0JwtTokenTestCase.php
packages/EasyApiToken/tests/Decoders/Auth0BearerTokenDecoderTest.php

[EasyApiToken] Fix broken test and add compatibility with auth0-PHP >= 8.3

---

packages/EasySwoole/src/Bridge/EasySchedule/EasyScheduleSwooleRunner.php

[EasySwoole] Fix runner to run schedule only once per minute

---

packages/EasySwoole/src/Helpers/FunctionHelper.php
packages/EasySwoole/src/Runtime/EasySwooleRuntime.php
packages/EasySwoole/tests/Helpers/FunctionHelperTest.php
phpstan.neon

[EasySwoole] Support OpenSwoole v22

---

packages/EasyTest/src/Traits/ExceptionTrait.php
packages/EasyTest/src/Traits/MessengerAssertionsTrait.php

This PR provides small BC for tests, that can be easy fixed.

[EasyTest] Improve Symfony Messenger asserts

---

composer.json
packages/EasyApiToken/composer.json
packages/EasyBankFiles/src/Parsers/Nai/Parser.php

[EasyBankFiles] Handle more than one group in single NAI file

---

packages/EasyApiToken/src/Tokens/HashedApiKeyDriver.php
packages/EasySecurity/src/Configurators/AbstractFromApiKeyConfigurator.php

[EasyApiToken] Improved encoding of hashed API keys.
[EasySecurity] Removed a useless annotation.

[EasyApiToken] Improved encoding of hashed API keys

---

.github/workflows/split_tests.yml

Use new GitHub Actions output syntax in split_tests.yml

---

monorepo/Console/Commands/LocalizePackageRepositoriesCommand.php
packages/EasyTest/composer.json

[EasyTest] Directly require all used packages in composer.json

---

packages/EasyHttpClient/composer.json

[EasyHttpClient] Add autoload for Symfony bundle

---

.github/workflows/php-ci.yml

Part of [https://eonx.atlassian.net/browse/INF-254](https://eonx.atlassian.net/browse/INF-254) 
Replace actions usage for followings:
- eonx-com/actions-checkout
- eonx-com/actions-setup-php

[DEPRECATED] Update workflow .github/workflows/php-ci.yml for deprecated actions

---

.github/workflows/php_ci.yml

[CI] Run security checker as part of coding-standards job

---

.github/workflows/php_ci.yml

Use composer audit

---

packages/EasySwoole/src/Bridge/Symfony/AppStateResetters/AbstractSymfonyServicesAppStateResetter.php
packages/EasySwoole/src/Bridge/Symfony/DependencyInjection/Compiler/SymfonyServicesResetPass.php
packages/EasySwoole/src/Bridge/Symfony/Resources/config/reset_services.php

[EasySwoole] Fixed the `SymfonyServicesResetPass` compiler pass.

---

packages/EasySwoole/src/Bridge/Symfony/Cache/SwooleTableAdapter.php
packages/EasySwoole/src/Helpers/CacheTableHelper.php
packages/EasySwoole/src/Helpers/OptionHelper.php
packages/EasySwoole/src/Runtime/EasySwooleRunner.php
phpstan.neon

[EasySwoole] Implement Symfony cache adapter using Swoole Table

---

packages/EasySwoole/src/Bridge/Symfony/Cache/SwooleTableAdapter.php

[EasySwoole] Make SwooleTableAdapter.php constructor public

---

packages/EasySwoole/src/Helpers/CacheTableHelper.php

[EasySwoole] Add output about cache tables

---

packages/EasySwoole/src/Helpers/AppRuntimeHelper.php

[EasySwoole] Implement AppRuntimeHelper to set app runtime options easily

---

packages/EasySwoole/src/Helpers/AppRuntimeHelper.php

[EasySwoole] Improve AppRuntimeHelper with explicit setters for options

---

packages/EasySwoole/src/Bridge/Symfony/Cache/SwooleTableAdapter.php
packages/EasySwoole/src/Helpers/CacheTableHelper.php

[EasySwoole] Some minor code style improvements.

---

packages/EasySwoole/src/Bridge/EasySchedule/EasyScheduleSwooleRunner.php
packages/EasySwoole/src/Enums/SwooleTableColumnType.php
packages/EasySwoole/src/Helpers/AppRuntimeHelper.php
packages/EasySwoole/src/Helpers/CacheTableHelper.php
packages/EasySwoole/src/Helpers/OptionHelper.php
packages/EasySwoole/src/Helpers/SwooleTableHelper.php
packages/EasySwoole/src/Runtime/EasySwooleRunner.php
packages/EasySwoole/src/ValueObjects/SwooleTableColumnDefinition.php
phpstan.neon

[EasySwoole] Fixed EasyScheduleSwooleRunner.

---

packages/EasySwoole/src/Helpers/AppRuntimeHelper.php
packages/EasySwoole/src/Helpers/EnvVarHelper.php
packages/EasySwoole/src/Helpers/OptionHelper.php
packages/EasySwoole/src/Helpers/SslCertificateHelper.php
packages/EasySwoole/src/Runtime/EasySwooleRuntime.php
quality/phpstan.neon

[EasySwoole] Loading SSL certificates

---

packages/EasyDoctrine/src/Bridge/AwsRds/AwsRdsConnectionParamsResolver.php
packages/EasyDoctrine/src/Bridge/AwsRds/Iam/AuthTokenProvider.php
packages/EasyDoctrine/src/Bridge/Symfony/DependencyInjection/EasyDoctrineExtension.php
packages/EasyDoctrine/src/Bridge/Symfony/Resources/config/aws_rds.php
packages/EasyDoctrine/src/Bridge/Symfony/Resources/config/aws_rds_iam.php

[EasyDoctrine] Use AWS Username as DB User if provided

---

packages/EasySwoole/src/Helpers/EnvVarHelper.php
packages/EasySwoole/src/Helpers/OptionHelper.php
packages/EasySwoole/src/Runtime/EasySwooleRuntime.php

[EasySwoole] Output env vars loaded from symfony dotenv

---

packages/EasySwoole/src/Bridge/Doctrine/Orm/DatabaseSessionHandler.php
packages/EasySwoole/tests/Bridge/Symfony/Stubs/KernelStub.php

[EasySwoole] Create DatabaseSessionHandler to reset database connection for session handling

---

packages/EasyApiPlatform/docs/config.md
packages/EasyApiPlatform/docs/install.md
packages/EasyApiPlatform/src/Bridge/BridgeConstantsInterface.php
packages/EasyApiPlatform/src/Bridge/Symfony/DependencyInjection/Configuration.php
packages/EasyApiPlatform/src/Bridge/Symfony/DependencyInjection/EasyApiPlatformExtension.php
packages/EasyApiPlatform/src/Bridge/Symfony/Resources/config/filters.php
packages/EasyApiPlatform/src/Filters/AdvancedSearchFilter.php
packages/EasyApiPlatform/tests/Filters/AdvancedSearchFilterTest.php
packages/EasyApiPlatform/tests/Fixtures/app/src/ApiResource/Dummy.php

[EasyApiPlatform] Allow filter by IRI for entityId field

---

packages/EasySwoole/src/Helpers/EnvVarHelper.php
packages/EasySwoole/src/Helpers/OptionHelper.php
packages/EasySwoole/src/Runtime/EasySwooleRuntime.php
packages/EasySwoole/tests/Helpers/EnvVarHelperTest.php
packages/EasySwoole/tests/Helpers/OptionHelperTest.php

[EasySwoole] Fix env var output enabled option

---

packages/EasySecurity/src/SecurityContext.php
packages/EasyTest/src/InvalidDataMaker/InvalidDataMaker.php
quality/rector.php

[EasySecurity] Made `SecurityContext` non-final

---

packages/EasyActivity/src/Bridge/Symfony/Serializers/SymfonyActivitySubjectDataSerializer.php

[EasyActivity] Skip API Platform serializers

---

packages/EasySwoole/src/Bridge/Symfony/AppStateResetters/SymfonyServicesAppStateResetter.php

Changes from https://github.com/eonx-com/easy-monorepo/pull/1243.

[EasySwoole] Fixed `SymfonyServicesAppStateResetter` (#1243)

---

packages/EasySwoole/composer.json
packages/EasySwoole/src/Bridge/Symfony/Resources/config/access_log.php
packages/EasySwoole/src/Runtime/EasySwooleRuntime.php

[EasySwoole] Clean up dependencies

---

quality/ecs.php
quality/rector.php

[QualityTools] Cleanup skipped files

---

packages/EasySwoole/src/Bridge/Doctrine/Coroutine/PDO/CoroutineConnectionFactory.php
packages/EasySwoole/src/Bridge/Symfony/Resources/config/doctrine_coroutine_pdo.php
packages/EasySwoole/src/Helpers/AppRuntimeHelper.php

[EasySwoole] Use PDO Coroutine client only when easy-swoole is enabled

---

packages/EasyDoctrine/src/Bridge/AwsRds/AwsRdsConnectionParamsResolver.php

[EasyDoctrine] Support RDS CA for MySQL

---

packages/EasyActivity/tests/Bridge/EasyDoctrine/EasyDoctrineEntityEventsSubscriberTest.php
packages/EasyActivity/tests/Bridge/Symfony/EasyActivitySymfonyBundleTest.php
packages/EasyActivity/tests/Stubs/ActivityLogFactoryStub.php
packages/EasyActivity/tests/Stubs/EntityManagerStub.php
packages/EasyDoctrine/src/Dispatchers/DeferredEntityEventDispatcher.php
packages/EasyDoctrine/src/Dispatchers/DeferredEntityEventDispatcherInterface.php
packages/EasyDoctrine/src/Subscribers/EntityEventSubscriber.php
packages/EasyDoctrine/tests/Fixtures/Offer.php
packages/EasyDoctrine/tests/Fixtures/Product.php
packages/EasyDoctrine/tests/Stubs/EntityManagerStub.php
packages/EasyDoctrine/tests/Subscribers/EntityEventSubscriberTest.php

[EasyDoctrine] Improve collection changes tracking

---

packages/EasySwoole/src/Bridge/Symfony/DependencyInjection/Compiler/AddDoctrineDbalConnectionNameToParamsPass.php

[EasySwoole] Support Coroutine Pool for replica connections

---

packages/EasySwoole/src/Bridge/Doctrine/Coroutine/PDO/DbalConnection.php
packages/EasySwoole/src/Bridge/Doctrine/Coroutine/PDO/PDOClient.php
packages/EasySwoole/src/Bridge/Doctrine/Orm/DatabaseSessionHandler.php
quality/phpstan.neon

[EasySwoole] Improve replica connection and session handler integration

---

packages/EasyDoctrine/src/Bridge/AwsRds/Ssl/CertificateAuthorityProvider.php
packages/EasyDoctrine/src/Bridge/Symfony/EasyDoctrineSymfonyBundle.php
packages/EasyDoctrine/src/Bridge/Symfony/Resources/config/definition.php

[EasyDoctrine] Deprecate the `aws_rds_iam` config

---

packages/EasyApiPlatform/src/Bridge/Symfony/EasyApiPlatformSymfonyBundle.php

[EasyApiPlatform] Add extension alias

---

packages/EasyUtils/src/Bridge/Symfony/Validator/Constraints/NumberValidator.php
packages/EasyUtils/src/ValueObjects/Number.php

| Fixed tickets | AVC-1886   
Added method to get raw value for validation.

[EasyUtils] Added `Number::getRawValue` useful for inner value validation

---

packages/EasySwoole/src/Bridge/Doctrine/Orm/ManagerConnectionsInitializer.php

[EasySwoole] Ensure connected to replica before each request

---

packages/EasyUtils/src/ValueObjects/Number.php
packages/EasyUtils/tests/ValueObjects/NumberTest.php

- updated number to money converting

[EasyUtils] update number to money string convert logic

---

packages/EasyUtils/src/SensitiveData/StringSanitizers/JsonStringSanitizer.php
packages/EasyUtils/tests/AbstractSensitiveDataSanitizerTestCase.php

[EasyUtils] Improved `JsonStringSanitizer`

---

quality/phpstan.neon
tests/bootstrap.php
tests/phpstan_bootstrap.php
tests/rector_bootstrap.php

[CI] Fix false phpstan error on safe static call

---

.github/workflows/php_ci.yml
Makefile
bin/run_tests.sh
composer.json
packages/EasyActivity/tests/AbstractTestCase.php
packages/EasyActivity/tests/Bridge/Symfony/EasyActivitySymfonyBundleTest.php
packages/EasyApiPlatform/tests/AbstractTestCase.php
packages/EasyDoctrine/tests/Stubs/EntityManagerStub.php
quality/phpstan.neon

[Monorepo] Add Makefile

---

readme.md

[Monorepo] Fix readme file

---

packages/EasyActivity/tests/Bridge/EasyDoctrine/EasyDoctrineEntityEventsSubscriberTest.php
packages/EasyDoctrine/src/Dispatchers/DeferredEntityEventDispatcher.php
packages/EasyDoctrine/tests/Subscribers/EntityEventSubscriberTest.php

- Fixed the `https://github.com/eonx-com/easy-monorepo/issues/887` issue.
| Fixed tickets | #887

[EasyDoctrine] Fixed an issue in DeferredEntityEventDispatcher

---

packages/EasyUtils/src/Bridge/Laravel/EasyUtilsServiceProvider.php
packages/EasyUtils/src/Bridge/Symfony/Resources/config/sensitive_data_default_object_transformers.php
packages/EasyUtils/src/SensitiveData/ObjectTransformers/ExceptionObjectTransformer.php
packages/EasyUtils/src/SensitiveData/ObjectTransformers/ThrowableObjectTransformer.php
packages/EasyUtils/tests/AbstractSensitiveDataSanitizerTestCase.php
packages/EasyUtils/tests/SensitiveData/SensitiveDataSanitizerTest.php

[EasyUtils] Exception Object Transformer

---

packages/EasyErrorHandler/src/Bridge/BridgeConstantsInterface.php
packages/EasyErrorHandler/src/Bridge/Laravel/Provider/EasyErrorHandlerServiceProvider.php
packages/EasyErrorHandler/src/Bridge/Laravel/config/easy-error-handler.php
packages/EasyErrorHandler/src/Bridge/Symfony/EasyErrorHandlerSymfonyBundle.php
packages/EasyErrorHandler/src/Bridge/Symfony/Messenger/ReportErrorEventListener.php
packages/EasyErrorHandler/src/Bridge/Symfony/Resources/config/definition.php
packages/EasyErrorHandler/src/Bridge/Symfony/Resources/config/services.php
packages/EasyErrorHandler/src/ErrorHandler.php
packages/EasyErrorHandler/src/Exceptions/RetryableException.php
packages/EasyErrorHandler/tests/ErrorHandlerTest.php

[EasyErrorHandler] Allow not to report retryable exception attempts

---

packages/EasySwoole/src/Resources/functions/dump.php

[EasySwoole] Fix swoole_dd to dump individual values and not array

---

packages/EasyRepository/src/Implementations/Doctrine/ORM/AbstractOptimizedDoctrineOrmRepository.php

[EasyRepository] Fix delete in AbstractOptimizedDoctrineOrmRepository.php

---

packages/EasyPagination/composer.json
packages/EasyPagination/src/Interfaces/LengthAwarePaginatorInterface.php
packages/EasyPagination/src/Paginators/AbstractLengthAwarePaginator.php
packages/EasyPagination/src/Traits/DoctrineCommonPaginatorTrait.php
packages/EasyPagination/src/Traits/DoctrineDbalPaginatorTrait.php
packages/EasyPagination/src/Traits/DoctrineOrmPaginatorTrait.php
packages/EasyPagination/tests/Paginators/DoctrineDbalLengthAwarePaginatorTest.php
packages/EasyPagination/tests/Paginators/DoctrineOrmLengthAwarePaginatorTest.php
quality/phpstan.neon

[EasyPagination] Implement large dataset support for Doctrine paginators

---

packages/EasyTest/src/Traits/ExceptionTrait.php

[EasyTest] Add more debug output to ExceptionTrait

---

composer.json
packages/EasyErrorHandler/composer.json
packages/EasyErrorHandler/tests/Bridge/Symfony/Provider/ApiPlatformErrorResponseBuilderProviderTest.php
packages/EasyPagination/composer.json
packages/EasyRandom/composer.json
packages/EasyRequestId/composer.json
packages/EasyWebhook/composer.json
quality/phpstan.neon

[EasyErrorHandler] Fix API Platform version

---

packages/EasySwoole/src/Bridge/Doctrine/Coroutine/PDO/CoroutineConnectionFactory.php
packages/EasySwoole/src/Bridge/Doctrine/Coroutine/PDO/DbalDriver.php
packages/EasySwoole/src/Bridge/Doctrine/Coroutine/PDO/PDOClient.php
packages/EasySwoole/src/Bridge/Doctrine/Coroutine/PDO/PDOClientConfig.php
packages/EasySwoole/src/Bridge/Symfony/Resources/config/doctrine_coroutine_pdo.php

[EasySwoole] Improve logging in Coroutine PDO implementation

---

packages/EasySwoole/composer.json
packages/EasySwoole/src/AccessLog/HttpFoundationAccessLogFormatter.php
packages/EasySwoole/src/Interfaces/RequestAttributesInterface.php
packages/EasySwoole/src/Runtime/EasySwooleRunner.php

[EasySwoole] Improve access log to include when request was received and duration

---

packages/EasyDoctrine/src/Bridge/AwsRds/Iam/AuthTokenProvider.php
packages/EasyDoctrine/src/Bridge/Symfony/Resources/config/aws_rds_iam.php

[EasyDoctrine] Added logging to AWS RDS IAM `AuthTokenProvider`

---

packages/EasyDoctrine/src/Bridge/AwsRds/Ssl/CertificateAuthorityProvider.php
packages/EasyDoctrine/src/Bridge/Symfony/Resources/config/aws_rds_ssl.php

[EasyDoctrine] Improve logging around AWS RDS SSL

---

packages/EasyDoctrine/src/Bridge/Symfony/Aws/Rds/CertificateAuthorityCacheWarmer.php
packages/EasyDoctrine/src/Bridge/Symfony/Resources/config/aws_rds_ssl.php

[EasyDoctrine] RDS CA cache warmer

---

packages/EasySwoole/src/Helpers/AppCacheWarmupHelper.php
packages/EasySwoole/src/Helpers/AppRuntimeHelper.php
packages/EasySwoole/src/Helpers/OptionHelper.php
packages/EasySwoole/src/Runtime/EasySwooleRuntime.php

[EasySwoole] Support application cache warmup

---

packages/EasyBatch/src/BatchObjectManager.php

[EasyBatch] Support empty batch dispatch

---

packages/EasySwoole/src/Bridge/EasySchedule/EasyScheduleSwooleRunner.php
packages/EasySwoole/src/Helpers/OptionHelper.php

[EasySwoole] Add sleep to EasyScheduleSwooleRunner to reduce CPU usage

---

packages/EasySwoole/src/Bridge/Doctrine/Coroutine/PDO/CoroutineConnectionFactory.php
packages/EasySwoole/src/Bridge/Doctrine/Coroutine/PDO/DbalDriver.php

[EasySwoole] Fixes the `CoroutineConnectionFactory` factory

---

packages/EasyBatch/src/BatchObjectManager.php

[EasyBatch] Fix pending approval checker

---

packages/EasySwoole/src/Bridge/Symfony/Listeners/ApplicationStateCheckListener.php

[EasySwoole] Improves logging in `ApplicationStateCheckListener`

---

packages/EasySwoole/src/Helpers/AppRuntimeHelper.php
packages/EasySwoole/src/Helpers/OptionHelper.php
packages/EasySwoole/src/Runtime/EasySwooleRunner.php

[EasySwoole] Add option for worker stop waitEvent

---

packages/EasySwoole/src/Runtime/EasySwooleRuntime.php

[EasySwoole] Improved the default Swoole's server settings

---

.github/workflows/split_packages.yml
packages/EasySwoole/composer.json
packages/EasySwoole/src/Bridge/Doctrine/Coroutine/PDO/DbalConnection.php
packages/EasySwoole/src/Bridge/Doctrine/Coroutine/PDO/PDOClientPool.php

[EasySwoole] Create our own implementation of PDOClientPool

---

composer.json
packages/EasyApiPlatform/composer.json
packages/EasyApiPlatform/tests/Normalizers/CarbonImmutableNormalizerTest.php

Reason - https://github.com/symfony/symfony/pull/50297/files#diff-3c76037573d9cfb59363e4f52b5565ed3fbe9e6b597d1ba8246fa959ade9778d

[EasyApiPlatform] Fix CarbonImmutableNormalizerTest

---

composer.json
packages/EasyLogging/src/Bridge/BridgeConstantsInterface.php
packages/EasyLogging/src/Bridge/Symfony/EasyLoggingSymfonyBundle.php
packages/EasyLogging/src/Bridge/Symfony/Resources/config/services.php
packages/EasyLogging/src/LoggerFactory.php

[Monorepo] Use DebugLoggerConfigurator

---

packages/EasyErrorHandler/composer.json
packages/EasyErrorHandler/src/Providers/ErrorCodesFromEnumProvider.php

Update `nikic/php-parser` to minimum `5.0` version

[EasyErrorHandler] Update php-parser version

---

.github/workflows/php_ci.yml
.github/workflows/split_packages.yml
.github/workflows/split_tests.yml

[Monorepo] Update github actions to v4

---

.github/workflows/php_ci.yml
.github/workflows/split_packages.yml
.github/workflows/split_tests.yml

[Monorepo] Update github actions to v4 (6.x branch)

---

packages/EasySwoole/src/Runtime/EasySwooleRunner.php
packages/EasySwoole/src/Runtime/EasySwooleRuntime.php

[EasySwoole] Add the `envVarsLoaded` event for callbacks

---

packages/EasySwoole/src/Bridge/EasySchedule/EasyScheduleSwooleRunner.php
packages/EasySwoole/src/Helpers/AppRuntimeHelper.php
packages/EasySwoole/src/Runtime/EasySwooleRunner.php
packages/EasySwoole/src/Runtime/EasySwooleRuntime.php

[EasySwoole] Added validation for the `callbacks` option

---

packages/EasyEncryption/src/AwsPkcs11Encryptor.php

[EasyEncryption] Fixes the sign method in AwsPkcs11Encryptor

---

packages/EasySwoole/src/Runtime/EasySwooleRunner.php

[EasySwoole] Fixes the server events list in EasySwooleRunner

---

composer.json
monorepo/Console/Commands/CleanUpPackagesVendorDirsCommand.php
monorepo/Console/Commands/ExportPackagesAsJsonCommand.php
monorepo/Console/Commands/LocalizePackageRepositoriesCommand.php
monorepo/Release/PackagesListInReadmeReleaseWorker.php
monorepo/Release/UpdateTagInGithubWorkflow.php

[Monorepo] Remove obsolete packages

---

composer.json
packages/EasyApiPlatform/composer.json
packages/EasyErrorHandler/composer.json
readme.md

[Monorepo] Require API platform 3.2

---

packages/EasyUtils/src/SensitiveData/SensitiveDataSanitizerInterface.php
packages/EasyUtils/tests/AbstractSensitiveDataSanitizerTestCase.php

To avoid certificates in logs let's sanitize them

[EasyUtils] Add curl cert opts to sanitizer

---

packages/EasyHttpClient/src/Implementations/Symfony/WithEventsHttpClient.php

[EasyHttpClient] Make WithEventsHttpClient resettable

---

packages/EasyUtils/src/Bridge/BridgeConstantsInterface.php
packages/EasyUtils/src/Bridge/Laravel/EasyUtilsServiceProvider.php
packages/EasyUtils/src/Bridge/Symfony/EasyUtilsSymfonyBundle.php
packages/EasyUtils/src/Bridge/Symfony/Resources/config/sensitive_data.php
packages/EasyUtils/src/SensitiveData/SensitiveDataSanitizer.php
packages/EasyUtils/src/SensitiveData/SensitiveDataSanitizerInterface.php
packages/EasyUtils/tests/AbstractSensitiveDataSanitizerTestCase.php
packages/EasyUtils/tests/Bridge/Laravel/SensitiveDataTest.php
packages/EasyUtils/tests/Bridge/Symfony/SensitiveDataTest.php
packages/EasyUtils/tests/SensitiveData/SensitiveDataSanitizerTest.php

| Bug fix?      |no
| BC breaks?    |I changed the constructor signature, but since we updated the package with the bundle, it shouldn't significantly impact      
After discussing with @akl-95 , we decided to move the configuration constants to the bundle configuration layer

[EasyUtils] Sensitive data sanitizer configuration refactoring

---

packages/EasyApiPlatform/tests/Serializers/SerializerContextBuilderTest.php
packages/EasyRepository/tests/Implementation/Illuminate/EloquentRepositoryStub.php

[EasyApiPlatform] feature/fix-phpstan-in-easy-api-platform

---

.github/workflows/php_ci.yml
.github/workflows/split_packages.yml
.github/workflows/split_tests.yml

[EasyMonorepo] Update major version of some actions

---

packages/EasyApiPlatform/tests/Serializers/SerializerContextBuilderTest.php
packages/EasyErrorHandler/src/Bridge/Symfony/Builder/ApiPlatformValidationErrorResponseBuilder.php
packages/EasyErrorHandler/src/ErrorHandler.php
packages/EasyErrorHandler/tests/Bridge/Symfony/Provider/ApiPlatformErrorResponseBuilderProviderTest.php

[EasyErrorHandler] Remove type error handling from response builder

---

composer.json
packages/EasyApiPlatform/composer.json
packages/EasyErrorHandler/composer.json
packages/EasyErrorHandler/tests/Bridge/Symfony/Provider/ApiPlatformErrorResponseBuilderProviderTest.php

[Monorepo] Disable API Platform 3.3

---

composer.json
packages/EasyApiPlatform/composer.json
packages/EasyApiPlatform/tests/Filters/AdvancedSearchFilterTest.php
packages/EasyErrorHandler/composer.json
packages/EasyErrorHandler/tests/Bridge/Symfony/Provider/ApiPlatformErrorResponseBuilderProviderTest.php

[Monorepo] Require API platform 3.3

---

packages/EasyErrorHandler/composer.json
packages/EasyErrorHandler/src/ErrorHandler.php
packages/EasyErrorHandler/tests/ErrorHandlerTest.php

[EasyErrorHandler] Use WrappedExceptionsInterface and UnrecoverableExceptionInterfaces

---

packages/EasyUtils/src/Bridge/Symfony/Validator/Constraints/Abn.php

[EasyUtils] Allow customizing Abn constraint message

---

.github/workflows/split_tests.yml

Preparation for a https://coveralls.io

[Monorepo] Setup code coverage

---

packages/EasyUtils/tests/AbstractSensitiveDataSanitizerTestCase.php
packages/EasyUtils/tests/ValueObjects/NumberTest.php

[EasyUtils] Fix PHPUnit deprecations

---

packages/EasyErrorHandler/tests/Bridge/Symfony/Provider/ApiPlatformErrorResponseBuilderProviderTest.php

[EasyErrorHandler] Fix PHPUnit deprecations

---

packages/EasyActivity/tests/ActivityLogEntryFactoryTest.php

[EasyActivity] Fix PHPUnit deprecations

---

packages/EasyUtils/src/Bridge/Symfony/Validator/Constraints/Abn.php

- added groups to abn  constraint
| New feature?  |no 

[EasyUtils] feature/add-ability-to-set-groups-to-abn-constraint

---

.github/workflows/split_packages.yml
.github/workflows/split_tests.yml
packages/EasyActivity/tests/ActivityLogEntryFactoryTest.php
packages/EasyErrorHandler/tests/Bridge/Symfony/Provider/ApiPlatformErrorResponseBuilderProviderTest.php
packages/EasyErrorHandler/tests/ErrorHandlerTest.php
packages/EasyUtils/src/Bridge/Symfony/Validator/Constraints/Abn.php
packages/EasyUtils/tests/AbstractSensitiveDataSanitizerTestCase.php
packages/EasyUtils/tests/ValueObjects/NumberTest.php

[Monorepo] Sync 6.x with master

---

quality/composer.lock

[Monorepo] Update EasyQuality

---

monorepo/Console/Commands/GlobalizePackageRepositoriesCommand.php
monorepo/Console/Commands/LocalizePackageRepositoriesCommand.php
packages/EasyApiPlatform/composer.json
packages/EasyApiToken/composer.json
packages/EasyEncryption/composer.json
packages/EasyErrorHandler/composer.json
packages/EasyRepository/composer.json
packages/EasySchedule/composer.json

[Monorepo] Create GlobalizePackageRepositoriesCommand

---

packages/EasyActivity/src/Common/Entity/ActivitySubject.php
packages/EasyActivity/tests/Fixture/app/src/Entity/ActivityLogEntity.php
packages/EasyApiToken/src/AwsCognito/Provider/AwsCognitoJwkProvider.php
packages/EasyBankFiles/src/Generation/Common/ValueObject/AbstractObject.php
packages/EasyBugsnag/src/Bridge/Symfony/Resources/config/definition.php
packages/EasyDecision/tests/Decisions/DecisionWithExpressionLanguageTest.php
packages/EasyDoctrine/tests/Fixtures/Price.php
packages/EasyEncryption/src/Providers/DefaultEncryptionKeyProvider.php
packages/EasyEventDispatcher/tests/Bridge/Laravel/EasyEventDispatcherServiceProviderTest.php
packages/EasyLogging/tests/Bridge/Laravel/EasyLoggingServiceProviderTest.php
packages/EasySwoole/src/Runtime/EasySwooleRunner.php
packages/EasyTest/src/Faker/Providers/UniqueGroupProvider.php
quality/composer.json
quality/composer.lock
quality/ecs.php
quality/phpstan.neon
quality/rector.php

| Fixed tickets | https://eonx.atlassian.net/browse/MTCE-203

[Monorepo] Update EasyQuality to v4

---

packages/EasyEncryption/bundle/config/default_key_resolvers.php
packages/EasyEncryption/bundle/config/services.php
packages/EasyHttpClient/bundle/config/http_client.php
packages/EasyLogging/bundle/CompilerPass/DefaultStreamHandlerCompilerPass.php
packages/EasyLogging/bundle/config/services.php

[Monorepo] Use param and Parameter for service configs

---

packages/EasySchedule/src/Interfaces/ScheduleInterface.php
packages/EasySchedule/src/Schedule.php

[EasySchedule] Allow passing command FQCN to a Schedule

---

bin/monorepo
config/monorepo_services.php
monorepo-builder.php
monorepo/Application/MonorepoApplication.php
monorepo/Command/CleanUpPackagesVendorDirsCommand.php
monorepo/Command/ExportPackagesAsJsonCommand.php
monorepo/Command/GlobalizePackageRepositoriesCommand.php
monorepo/Command/LocalizePackageRepositoriesCommand.php
monorepo/Helper/GitHelper.php
monorepo/Kernel/MonorepoKernel.php
monorepo/ReleaseWorker/PackagesListInReadmeReleaseWorker.php
monorepo/ReleaseWorker/PushNextDevReleaseWorker.php
monorepo/ReleaseWorker/TagVersionReleaseWorker.php
monorepo/ReleaseWorker/UpdateTagInGithubWorkflowReleaseWorker.php
monorepo/TypeExtension/SymfonyMessengerEnvelopeLastReturnType.php
monorepo/TypeExtension/SymfonyMessengerEnvelopeLastReturnTypeExtension.php
quality/phpstan.neon

| Fixed tickets | https://eonx.atlassian.net/issues/MTCE-249

Monorepo v6 refactoring: monorepo directory

---

packages/EasyLogging/src/Processor/WrappingProcessor.php
packages/EasyLogging/tests/Unit/src/Processor/WrappingProcessorTest.php

[EasyLogging] Fix WrappingProcessor naming

---

packages/EasyActivity/src/Common/Entity/ActivityLogEntry.php
packages/EasyActivity/src/Common/Resolver/DefaultActorResolver.php
packages/EasyActivity/tests/Unit/src/Common/Factory/ActivityLogEntryFactoryTest.php
packages/EasyActivity/tests/Unit/src/EasyDoctrine/Subscriber/EasyDoctrineEntityEventsSubscriberTest.php

[EasyActivity] Move DEFAULT_ACTOR_TYPE const

---

packages/EasyDoctrine/tests/Fixture/ValueObject/Price.php
packages/EasyRepository/src/Repository/AbstractPaginatedDoctrineOrmRepository.php
quality/rector.php

[Monorepo] Add ClassPropertyAssignToConstructorPromotionRector

---

packages/EasyUtils/bundle/EasyUtilsBundle.php
packages/EasyUtils/src/Math/Helper/MathHelper.php
packages/EasyUtils/src/Math/Helper/MathHelperInterface.php

[EasyUtils] Monorepo v6: modernize the code by using latest PHP features

---

packages/EasyWebhook/bundle/config/core_middleware.php
packages/EasyWebhook/laravel/EasyWebhookServiceProvider.php
packages/EasyWebhook/src/Common/Entity/AbstractWebhook.php
packages/EasyWebhook/src/Common/Entity/WebhookInterface.php
packages/EasyWebhook/src/Common/Enum/MiddlewarePriority.php
packages/EasyWebhook/src/Common/Enum/WebhookOption.php
packages/EasyWebhook/src/Common/Enum/WebhookStatus.php
packages/EasyWebhook/src/Common/Middleware/EventsMiddleware.php
packages/EasyWebhook/src/Common/Middleware/MiddlewareInterface.php
packages/EasyWebhook/src/Common/Middleware/RerunMiddleware.php
packages/EasyWebhook/src/Common/Middleware/StatusAndAttemptMiddleware.php
packages/EasyWebhook/src/Common/Store/AbstractStore.php
packages/EasyWebhook/src/Common/Store/ResultStoreInterface.php
packages/EasyWebhook/src/Common/Store/StoreInterface.php
packages/EasyWebhook/src/Doctrine/Provider/DoctrineDbalStatementProvider.php
packages/EasyWebhook/src/Doctrine/Store/DoctrineDbalResultStore.php
packages/EasyWebhook/src/Doctrine/Store/DoctrineDbalStore.php
packages/EasyWebhook/tests/Unit/src/Common/Client/WebhookClientTest.php
packages/EasyWebhook/tests/Unit/src/Common/Middleware/EventsMiddlewareTest.php
packages/EasyWebhook/tests/Unit/src/Common/Middleware/LockMiddlewareTest.php
packages/EasyWebhook/tests/Unit/src/Common/Middleware/RerunMiddlewareTest.php
packages/EasyWebhook/tests/Unit/src/Common/Middleware/SendAfterMiddlewareTest.php
packages/EasyWebhook/tests/Unit/src/Common/Middleware/SignatureHeaderMiddlewareTest.php
packages/EasyWebhook/tests/Unit/src/Common/Middleware/StatusAndAttemptMiddlewareTest.php
packages/EasyWebhook/tests/Unit/src/Doctrine/Store/AbstractDoctrineDbalStoreTestCase.php
packages/EasyWebhook/tests/Unit/src/Doctrine/Store/DoctrineDbalStoreTest.php

[EasyWebhook] Monorepo v6: modernize the code by using latest PHP features

---

packages/EasyHttpClient/src/EasyBugsnag/Listener/HttpRequestSentBreadcrumbListener.php
packages/EasyHttpClient/tests/Unit/src/EasyBugsnag/Listener/HttpRequestSentBreadcrumbListenerTest.php

[EasyHttpClient] Monorepo v6: modernize the code by using latest PHP features

---

packages/EasySecurity/bundle/EasySecurityBundle.php
packages/EasySecurity/bundle/Enum/ConfigParam.php
packages/EasySecurity/bundle/config/default_configurators.php
packages/EasySecurity/bundle/config/definition.php
packages/EasySecurity/laravel/EasySecurityServiceProvider.php
packages/EasySecurity/laravel/config/easy-security.php
packages/EasySecurity/src/Common/Configurator/SecurityContextConfiguratorInterface.php
packages/EasySecurity/tests/Unit/src/SymfonySecurity/Provider/PermissionExpressionFunctionProviderTest.php
packages/EasySecurity/tests/Unit/src/SymfonySecurity/Provider/RoleExpressionFunctionProviderTest.php

[EasySecurity] Monorepo v6: modernize the code by using latest PHP features

---

packages/EasyBatch/tests/Unit/src/Common/Transformer/BatchItemTransformerTest.php
packages/EasyEncryption/bundle/config/definition.php
packages/EasyEncryption/laravel/config/easy-encryption.php
packages/EasyEncryption/src/Common/Encryptor/AbstractEncryptor.php
packages/EasyEncryption/src/Common/Encryptor/EncryptorInterface.php
packages/EasyEncryption/src/Common/Enum/EncryptionKeyOption.php
packages/EasyEncryption/src/Common/Factory/DefaultEncryptionKeyFactory.php
packages/EasyEncryption/src/Common/Factory/EncryptionKeyFactoryInterface.php
packages/EasyEncryption/src/Common/Resolver/SimpleEncryptionKeyResolver.php
packages/EasyEncryption/tests/Unit/src/Common/Encryptor/EncryptorTest.php

[EasyEncryption] Monorepo v6: modernize the code by using latest PHP features

---

packages/EasyLogging/bundle/CompilerPass/SensitiveDataSanitizerCompilerPass.php
packages/EasyLogging/bundle/EasyLoggingBundle.php
packages/EasyLogging/bundle/config/definition.php
packages/EasyLogging/laravel/config/easy-logging.php
packages/EasyLogging/src/Enum/BugsnagSeverity.php
packages/EasyLogging/src/Factory/LoggerFactory.php
packages/EasyLogging/src/Factory/LoggerFactoryInterface.php
packages/EasyLogging/src/MonologHandler/BugsnagMonologHandler.php
packages/EasyLogging/src/Resolver/BugsnagSeverityResolver.php
packages/EasyLogging/src/Resolver/BugsnagSeverityResolverInterface.php
packages/EasyLogging/tests/Unit/laravel/EasyLoggingServiceProviderTest.php
packages/EasyLogging/tests/Unit/src/Resolver/BugsnagSeverityResolverTest.php

[EasyLogging] Monorepo v6: modernize the code by using latest PHP features

---

packages/EasyDecision/bundle/config/services.php
packages/EasyDecision/src/DataCollector/DecisionDataCollector.php
packages/EasyErrorHandler/bundle/config/services.php
packages/EasyErrorHandler/src/Common/DataCollector/ErrorHandlerDataCollector.php
packages/EasySchedule/bundle/config/services.php
packages/EasySchedule/composer.json
packages/EasySchedule/src/DataCollector/ScheduleDataCollector.php
packages/EasySecurity/bundle/config/services.php
packages/EasySecurity/composer.json
packages/EasySecurity/src/Common/DataCollector/SecurityContextDataCollector.php
packages/EasyUtils/composer.json
packages/EasyUtils/src/Common/DataCollector/AbstractDataCollector.php
packages/EasyWebhook/bundle/config/debug.php
packages/EasyWebhook/src/Common/DataCollector/WebhookDataCollector.php

[Monorepo] Refactor symfony profiler data collectors

---

packages/EasyWebhook/src/Exceptions/WebhookRequestFailedException.php
packages/EasyWebhook/src/Middleware/SendWebhookMiddleware.php

We can add this exception to ignored exceptions list for the Bugsnag then in example

[EasyWebhook] Add WebhookRequestFailedException

---

packages/EasySwoole/src/Caching/Adapter/SwooleTableAdapter.php
packages/EasySwoole/src/Caching/Enum/CacheTableColumn.php
packages/EasySwoole/src/Caching/Helper/CacheTableHelper.php
packages/EasySwoole/src/Common/Enum/SwooleRunnerEvent.php
packages/EasySwoole/src/Common/Enum/SwooleServerEvent.php
packages/EasySwoole/src/Common/Helper/AppRuntimeHelper.php
packages/EasySwoole/src/Common/Helper/ErrorResponseHelper.php
packages/EasySwoole/src/Common/Listener/SwooleDdListener.php
packages/EasySwoole/src/Common/Runner/EasySwooleRunner.php
packages/EasySwoole/src/Common/Runtime/EasySwooleRuntime.php
packages/EasySwoole/src/Common/ValueObject/SwooleTableColumnDefinition.php
packages/EasySwoole/src/EasySchedule/Runner/EasyScheduleSwooleRunner.php
packages/EasyUtils/src/Common/Enum/HttpStatusCode.php
quality/ecs.php

[EasySwoole] Modernize the code

---

Makefile
monorepo/Command/CleanUpPackagesCommand.php

[Monorepo] Improve cleanup command

---

packages/EasyErrorHandler/src/Bugsnag/Configurator/SeverityClientConfigurator.php
packages/EasyErrorHandler/src/Common/Builder/AbstractSingleKeyErrorResponseBuilder.php
packages/EasyErrorHandler/src/Common/Builder/CodeErrorResponseBuilder.php
packages/EasyErrorHandler/src/Common/Builder/ExtendedExceptionErrorResponseBuilder.php
packages/EasyErrorHandler/src/Common/Builder/SubCodeErrorResponseBuilder.php
packages/EasyErrorHandler/src/Common/Builder/TimeErrorResponseBuilder.php
packages/EasyErrorHandler/src/Common/Builder/UserMessageErrorResponseBuilder.php
packages/EasyErrorHandler/src/Common/Builder/ViolationsErrorResponseBuilder.php
packages/EasyErrorHandler/src/Common/Enum/ExceptionSeverity.php
packages/EasyErrorHandler/src/Common/Exception/BadRequestException.php
packages/EasyErrorHandler/src/Common/Exception/ConflictException.php
packages/EasyErrorHandler/src/Common/Exception/ForbiddenException.php
packages/EasyErrorHandler/src/Common/Exception/NotFoundException.php
packages/EasyErrorHandler/src/Common/Exception/SeverityAwareExceptionInterface.php
packages/EasyErrorHandler/src/Common/Exception/TranslatableExceptionInterface.php
packages/EasyErrorHandler/src/Common/Exception/TranslatableExceptionTrait.php
packages/EasyErrorHandler/src/Common/Exception/UnauthorizedException.php
packages/EasyErrorHandler/src/Common/Exception/ValidationException.php
packages/EasyErrorHandler/src/Common/Provider/DefaultErrorResponseBuilderProvider.php
packages/EasyErrorHandler/src/Common/Resolver/ErrorDetailsResolver.php
packages/EasyErrorHandler/src/Common/Resolver/ErrorDetailsResolverInterface.php

[EasyErrorHandler] Monorepo v6: modernize the code by using latest PHP features

---

packages/EasyRandom/src/Enum/Alphabet.php
packages/EasyRandom/src/Exception/InvalidAlphabetNameException.php
packages/EasyRandom/src/ValueObject/RandomString.php
packages/EasyRandom/src/ValueObject/RandomStringInterface.php
packages/EasyRandom/tests/Unit/src/Generator/RandomStringGeneratorTest.php

[EasyRandom] Monorepo v6: modernize the code by using latest PHP features

---

packages/EasyApiToken/src/AwsCognito/ValueObject/UserPoolConfig.php
packages/EasyApiToken/src/AwsCognito/ValueObject/UserPoolConfigInterface.php
packages/EasySecurity/src/Authorization/Factory/CachedAuthorizationMatrixFactory.php
packages/EasySecurity/src/SymfonySecurity/Entity/FakeUser.php
packages/EasySecurity/tests/Unit/src/SymfonySecurity/Entity/FakeUserTest.php

| Fixed tickets | https://eonx.atlassian.net/browse/MTCE-261

[Monorepo] v6: modernize the code by using latest PHP features. Final cleanup

---

packages/EasyErrorHandler/bundle/config/definition.php
packages/EasyErrorHandler/src/Bugsnag/Configurator/SeverityClientConfigurator.php
packages/EasyErrorHandler/src/Bugsnag/Provider/BugsnagErrorReporterProvider.php
packages/EasyErrorHandler/src/Bugsnag/Reporter/BugsnagErrorReporter.php
packages/EasyErrorHandler/src/Common/Exception/ErrorException.php
packages/EasyErrorHandler/src/Common/Exception/LogLevelAwareExceptionInterface.php
packages/EasyErrorHandler/src/Common/Exception/LogLevelAwareExceptionTrait.php
packages/EasyErrorHandler/src/Common/Resolver/ErrorLogLevelResolver.php
packages/EasyErrorHandler/src/Common/Resolver/ErrorLogLevelResolverInterface.php
packages/EasyErrorHandler/tests/Unit/src/Bugsnag/Reporter/BugsnagErrorReporterTest.php
packages/EasyErrorHandler/tests/Unit/src/Common/Exception/BaseExceptionTest.php
packages/EasyErrorHandler/tests/Unit/src/Common/Resolver/ErrorLogLevelResolverTest.php

[EasyErrorHandler] Fix monolog deprecations

---

packages/EasyApiToken/src/Auth0/Driver/Auth0JwtDriver.php

[EasyApiToken]  Fix depreactions

---

packages/EasyRequestId/bundle/EasyRequestIdBundle.php
packages/EasyRequestId/laravel/EasyRequestIdServiceProvider.php
packages/EasyTest/src/HttpClient/HttpClient/HttpClientStub.php
packages/EasyTest/src/InvalidData/Maker/InvalidDataMaker.php

[Monorepo] Fix todo and remove deprecations

---

packages/EasyAsync/src/Bridge/Laravel/Providers/EasyAsyncServiceProvider.php
packages/EasyAsync/src/Bridge/Laravel/config/easy-async.php
packages/EasyDoctrine/tests/Subscribers/EntityEventSubscriberTest.php

[EasyAsync] Fix service provider listeners

---

.github/CONTRIBUTING.md

[Monorepo] Update CONTRIBUTING.md

---

packages/EasyErrorHandler/src/Bridge/Symfony/Builder/ApiPlatformValidationErrorResponseBuilder.php
packages/EasyErrorHandler/src/Bridge/Symfony/Provider/ApiPlatformErrorResponseBuilderProvider.php
packages/EasyErrorHandler/src/Bridge/Symfony/Resources/config/api_platform_builders.php
packages/EasyErrorHandler/tests/Bridge/Symfony/Fixtures/app/src/ApiResource/Payment.php
packages/EasyErrorHandler/tests/Bridge/Symfony/Fixtures/app/src/DataTransferObject/PaymentInputDtoWithConstructor.php
packages/EasyErrorHandler/tests/Bridge/Symfony/Provider/ApiPlatformErrorResponseBuilderProviderTest.php

[EasyErrorHandler] Fix an issue with the field name exposed in the validation error

---

packages/EasyApiPlatform/bundle/config/easy_error_handler.php
packages/EasyApiPlatform/src/EasyErrorHandler/Builder/AbstractApiPlatformExceptionErrorResponseBuilder.php
packages/EasyApiPlatform/src/EasyErrorHandler/Builder/AbstractApiPlatformSerializerExceptionErrorResponseBuilder.php
packages/EasyApiPlatform/src/EasyErrorHandler/Builder/ApiPlatformCustomSerializerExceptionErrorResponseBuilder.php
packages/EasyApiPlatform/src/EasyErrorHandler/Builder/ApiPlatformMissingConstructorArgumentsExceptionErrorResponseBuilder.php
packages/EasyApiPlatform/tests/Application/src/EasyErrorHandler/Provider/ApiPlatformErrorResponseBuilderProviderTest.php
packages/EasyApiPlatform/tests/Fixture/app/src/EasyErrorHandler/ApiResource/Payment.php
packages/EasyApiPlatform/tests/Fixture/app/src/EasyErrorHandler/DataTransferObject/PaymentInputDtoWithConstructor.php

[EasyApiPlatform] Fix field name in the validation error

---

composer.json
packages/EasyActivity/composer.json
packages/EasyApiPlatform/composer.json
packages/EasyApiToken/composer.json
packages/EasyAsync/composer.json
packages/EasyBankFiles/composer.json
packages/EasyBatch/composer.json
packages/EasyBugsnag/composer.json
packages/EasyDecision/composer.json
packages/EasyDoctrine/composer.json
packages/EasyEncryption/composer.json
packages/EasyErrorHandler/composer.json
packages/EasyEventDispatcher/composer.json
packages/EasyHttpClient/composer.json
packages/EasyLock/composer.json
packages/EasyLogging/composer.json
packages/EasyNotification/composer.json
packages/EasyPagination/composer.json
packages/EasyPipeline/composer.json
packages/EasyRandom/composer.json
packages/EasyRepository/composer.json
packages/EasyRequestId/composer.json
packages/EasySchedule/composer.json
packages/EasySecurity/composer.json
packages/EasySwoole/composer.json
packages/EasyTemplatingBlock/composer.json
packages/EasyTest/composer.json
packages/EasyUtils/composer.json
packages/EasyWebhook/composer.json

[EasyMonorepo] Set `minimum-stability` to `dev`

---

packages/EasyDoctrine/src/Common/Type/IntegerNumberType.php
packages/EasyDoctrine/src/Common/Type/JsonbType.php

[EasyDoctrine] Get back type name consts

---

packages/EasyTest/src/Common/Trait/MessengerAssertionsTrait.php

[EastTest] Allow to use multiple transports in messenger

---

packages/EasyEncryption/docs/symfony/install.md
packages/EasyEncryption/src/Bridge/BridgeConstantsInterface.php
packages/EasyEncryption/src/Bridge/Laravel/Provider/EasyEncryptionServiceProvider.php
packages/EasyEncryption/src/Bridge/Laravel/config/easy-encryption.php
packages/EasyEncryption/src/Bridge/Symfony/EasyEncryptionSymfonyBundle.php
packages/EasyEncryption/src/Bridge/Symfony/Resources/config/aws_cloud_hsm_encryptor.php
packages/EasyEncryption/src/Bridge/Symfony/Resources/config/definition.php
packages/EasyEncryption/src/Interfaces/EncryptorInterface.php

[EasyEncryption] Fix AwsCloudHsmHashCalculator $signingKey argument value

---

packages/EasyLogging/src/Processor/SensitiveDataSanitizerProcessor.php

[EasyLogging] Sensitive data sanitizer processor fix

---

packages/EasyActivity/src/Common/Entity/ActivityLogEntry.php
packages/EasyActivity/src/Common/Factory/ActivityLogEntryFactory.php
packages/EasyActivity/src/Common/Factory/ActivityLogEntryFactoryInterface.php
packages/EasyActivity/src/Common/Logger/ActivityLoggerInterface.php
packages/EasyActivity/src/Common/Logger/AsyncActivityLogger.php
packages/EasyActivity/src/Common/Logger/SyncActivityLogger.php
packages/EasyActivity/src/Common/Resolver/ActivitySubjectDataResolverInterface.php
packages/EasyActivity/src/Common/Resolver/DefaultActivitySubjectDataResolver.php
packages/EasyActivity/src/Doctrine/Store/DoctrineDbalStore.php
packages/EasyActivity/src/EasyDoctrine/Subscriber/EasyDoctrineEntityEventsSubscriber.php
packages/EasyActivity/tests/Fixture/app/src/ActivitySubjectDataResolver/CustomActivitySubjectDataResolver.php
packages/EasyActivity/tests/Unit/src/Common/Factory/ActivityLogEntryFactoryTest.php

[EasyActivity] Do not use `ActivityAction` as a type

---

packages/EasyLock/bundle/config/services.php

[EasyLock] Add missed autowire/autoconfigure for services

---

packages/EasyUtils/src/Common/Constraint/Abn.php
packages/EasyUtils/src/Common/Constraint/AbstractConstraint.php
packages/EasyUtils/src/Common/Constraint/Alphanumeric.php
packages/EasyUtils/src/Common/Constraint/AlphanumericHyphen.php
packages/EasyUtils/src/Common/Constraint/DateInterval.php
packages/EasyUtils/src/Common/Constraint/Decimal.php
packages/EasyUtils/src/Common/Constraint/Integer.php
packages/EasyUtils/src/Math/Constraint/AbstractNumberComparison.php
packages/EasyUtils/src/Math/Constraint/NumberGreaterOrEqual.php
packages/EasyUtils/src/Math/Constraint/NumberLessOrEqual.php
packages/EasyUtils/src/Math/Constraint/NumberPositiveOrZero.php

[EasyUtils] Fix constaints validated by

---

packages/EasyLock/bundle/config/messenger_middleware.php

[EasyLock] Autoconfigure services

---

packages/EasyEncryption/bundle/CompilerPass/AwsCloudHsmCompilerPass.php
packages/EasyEncryption/bundle/config/services.php

[EasyEncryption] Fix AwsCloudHsmCompilerPass

---

packages/EasyPagination/bundle/config/services.php

[EasyPagination] Set default resolver

---

composer.json
packages/EasyDoctrine/bundle/EasyDoctrineBundle.php
packages/EasyDoctrine/composer.json
packages/EasyDoctrine/src/Migration/Factory/MigrationFactory.php
packages/EasyDoctrine/src/Migration/Migration/EnvironmentAwareMigrationInterface.php
packages/EasyDoctrine/src/Migration/Migration/EnvironmentAwareMigrationTrait.php
packages/EasyDoctrine/src/Migration/Migration/ExpectedConnectionAwareMigrationInterface.php
packages/EasyDoctrine/src/Migration/Migration/ExpectedConnectionAwareMigrationTrait.php

[EasyDoctrine] Allow to pass env and expected connection to migration

---

packages/EasyDoctrine/src/Common/Listener/FixPostgreSqlDefaultSchemaListener.php

[EasyDoctrine] Add AsDoctrineListener attribute to FixPostgreSqlDefaultSchemaListener

---

packages/EasyUtils/composer.json
packages/EasyUtils/src/Common/Normalizer/CarbonImmutableNormalizer.php

[EasyUtils] Fix CarbonImmutableNormalizer

---

packages/EasyDoctrine/bundle/CompilerPass/MigrationsFactoryCompilerPass.php
packages/EasyDoctrine/bundle/EasyDoctrineBundle.php

[EasyDoctrine] Fix migration decoration

---

packages/EasyTest/src/HttpClient/Response/AbstractTestResponse.php
packages/EasyTest/src/HttpClient/Response/StrictTestResponse.php
packages/EasyTest/src/HttpClient/Trait/HttpClientUnitTestTrait.php

[EasyTest] Improve http client query parameter

---

packages/EasySwoole/src/Caching/Adapter/SwooleTableAdapter.php

[EasySwoole] Fix SwooleTableAdapter

---

packages/EasySwoole/src/EasyLogging/Processor/SwooleWorkerIdProcessor.php

[EasySwoole] Fix SwooleWorkerIdProcessor

---

packages/EasyApiPlatform/src/EasyErrorHandler/Builder/AbstractApiPlatformSerializerExceptionErrorResponseBuilder.php
packages/EasyApiPlatform/tests/Application/src/EasyErrorHandler/Provider/ApiPlatformErrorResponseBuilderProviderTest.php
packages/EasyApiPlatform/tests/Fixture/app/src/EasyErrorHandler/ApiResource/Book.php

[EasyApiPlatform] Handle invalid date error

---

packages/EasyBatch/tests/Stub/Kernel/KernelStub.php
packages/EasyDoctrine/tests/Fixture/app/config/services.php
packages/EasyEventDispatcher/bundle/config/services.php
packages/EasyEventDispatcher/laravel/Dispatchers/EventDispatcher.php
packages/EasyEventDispatcher/readme.md
packages/EasyEventDispatcher/src/Dispatcher/EventDispatcher.php
packages/EasyEventDispatcher/src/Dispatcher/EventDispatcherInterface.php
packages/EasyEventDispatcher/tests/Stub/Kernel/KernelStub.php
packages/EasyHttpClient/tests/Application/src/Common/HttpClient/WithEventsHttpClientTest.php
packages/EasyHttpClient/tests/Fixture/app/config/services.php
packages/EasyTest/src/EasyEventDispatcher/Dispatcher/EventDispatcherStub.php
packages/EasyWebhook/tests/Stub/Kernel/KernelStub.php
packages/EasyWebhook/tests/Unit/src/Common/Middleware/EventsMiddlewareTest.php

[EasyEventDispatcher] Remove event dispatcher decoration

---

packages/EasyUtils/src/Common/DataCollector/AbstractDataCollector.php

[EasyUtils] Fix path in AbstractDataCollector

---

packages/EasySwoole/src/Common/Runner/EasySwooleRunner.php

[EasySwoole] Handle non-booted kernel in EasySwooleRunner

---

packages/EasyPagination/composer.json
packages/EasyPagination/src/Paginator/DoctrineCommonPaginatorTrait.php
packages/EasyPagination/tests/Stub/Entity/ChildItem.php
packages/EasyPagination/tests/Stub/Type/SqliteStringUuidType.php
packages/EasyPagination/tests/Unit/src/Paginator/AbstractDoctrineDbalPaginatorTestCase.php
packages/EasyPagination/tests/Unit/src/Paginator/AbstractDoctrineOrmPaginatorTestCase.php
packages/EasyPagination/tests/Unit/src/Paginator/DoctrineDbalLengthAwarePaginatorTest.php
packages/EasyPagination/tests/Unit/src/Paginator/DoctrineDbalPaginatorTest.php
packages/EasyPagination/tests/Unit/src/Paginator/DoctrineOrmLengthAwarePaginatorTest.php
packages/EasyPagination/tests/Unit/src/Paginator/DoctrineOrmPaginatorTest.php

[EasyPagination] Support UUID primary key

---

packages/EasyBatch/src/Common/Transformer/AbstractBatchObjectTransformer.php
packages/EasyBatch/src/Messenger/MessageHandler/UpdateBatchItemMessageHandler.php

[EasyBatch] Handle case when date time do not have microseconds

---

.github/workflows/split_packages.yml
composer.json
packages/EasyActivity/composer.json
packages/EasyApiPlatform/composer.json
packages/EasyApiToken/composer.json
packages/EasyAsync/composer.json
packages/EasyBankFiles/composer.json
packages/EasyBatch/composer.json
packages/EasyBugsnag/composer.json
packages/EasyDecision/composer.json
packages/EasyDoctrine/composer.json
packages/EasyEncryption/composer.json
packages/EasyErrorHandler/composer.json
packages/EasyEventDispatcher/composer.json
packages/EasyHttpClient/composer.json
packages/EasyLock/composer.json
packages/EasyLogging/composer.json
packages/EasyNotification/composer.json
packages/EasyPagination/composer.json
packages/EasyPipeline/composer.json
packages/EasyRandom/composer.json
packages/EasyRepository/composer.json
packages/EasyRequestId/composer.json
packages/EasySchedule/composer.json
packages/EasySecurity/composer.json
packages/EasySwoole/composer.json
packages/EasyTemplatingBlock/composer.json
packages/EasyTest/composer.json
packages/EasyUtils/composer.json
packages/EasyWebhook/composer.json

[Monorepo] Cleanup after 6.0.0 release

---

packages/EasyNotification/src/Config/CacheConfigFinder.php

[EasyNotification] Append provider ExternalId in CacheConfigFinder

---

packages/EasyEncryption/src/Encryptable/Serializer/EncryptableAwareMessengerSerializer.php

- Get rid of the boolean header
After switching to monorepo 6, we also switched from `async-aws/sqs 1.8.0` to `async-aws/sqs 2.1.1`. This caused the change in the request format to AWS SQS from `application/x-www-form-urlencoded` to `application/x-amz-json-1.0`.
Our custom `encrypted=true` header for fully or partially encrypted messages now cannot be handled by SQS because the boolean value is sent as is in the JSON, but marked as string type. We can get rid of this header to cure the situation.

[EasyEncryption] hotfix/update-encryptable-aware-messenger-serializer

---

packages/EasyApiToken/src/AwsCognito/Driver/AwsCognitoJwtDriver.php

[EasyApiToken] Add todo to rename parameters in AwsCognitoJwtDriver

---

packages/EasyTest/composer.json
packages/EasyTest/src/HttpClient/Response/AbstractTestResponse.php
packages/EasyTest/src/HttpClient/Response/StrictTestResponse.php
packages/EasyTest/tests/Fixture/Enum/DummyEnum.php
packages/EasyTest/tests/Unit/src/HttpClient/Response/StrictTestResponseTest.php

[EasyTest] Refactor URL check in HTTP client stub

---

packages/EasyLogging/src/Logger/LazyLogger.php
packages/EasyTest/src/Common/Trait/LoggerTrait.php

[EasyTest] Allow use lazy logers in test stub

---

packages/EasyApiPlatform/src/EasyErrorHandler/Builder/ApiPlatformUnexpectedValueExceptionErrorResponseBuilder.php
packages/EasyApiPlatform/tests/Application/src/EasyErrorHandler/Provider/ApiPlatformErrorResponseBuilderProviderTest.php
packages/EasyApiPlatform/tests/Fixture/app/src/EasyErrorHandler/StateProvider/PrintingHouseStateProvider.php

[EasyApiPlatform] Handle validation case when item not found by IRI

---

packages/EasyUtils/src/Math/Constraint/NumberPositiveOrZero.php

[EasyUtils] Number positive or zero validatedBy method missed

---

packages/EasyDoctrine/bundle/Enum/ConfigServiceId.php
packages/EasyDoctrine/bundle/Factory/ObjectCopierFactory.php
packages/EasyDoctrine/bundle/config/deferred_dispatcher.php
packages/EasyDoctrine/src/DeepCopy/Filter/DoctrineInitializedCollectionDeepCopyFilter.php
packages/EasyDoctrine/src/DeepCopy/Filter/DoctrineInitializedCollectionFilter.php
packages/EasyDoctrine/src/EntityEvent/Dispatcher/DeferredEntityEventDispatcher.php
packages/EasyDoctrine/src/EntityEvent/Dispatcher/DeferredEntityEventDispatcherInterface.php
packages/EasyDoctrine/tests/Unit/src/EntityEvent/Listener/EntityEventListenerTest.php

| Fixed tickets | https://eonx.atlassian.net/browse/MTCE-326

[EasyDoctrine] Copy only initialized Doctrine Collection

---

packages/EasyErrorHandler/bundle/EasyErrorHandlerBundle.php
packages/EasyErrorHandler/bundle/Enum/ConfigParam.php
packages/EasyErrorHandler/bundle/config/default_builders.php
packages/EasyErrorHandler/bundle/config/definition.php
packages/EasyErrorHandler/laravel/EasyErrorHandlerServiceProvider.php
packages/EasyErrorHandler/laravel/config/easy-error-handler.php
packages/EasyErrorHandler/src/Common/Builder/MessageErrorResponseBuilder.php
packages/EasyErrorHandler/src/Common/Provider/DefaultErrorResponseBuilderProvider.php
packages/EasyErrorHandler/tests/Unit/bundle/TestRenderWithDefaultBuilderDataProvider.php
packages/EasyErrorHandler/tests/Unit/laravel/ErrorHandlerTest.php

[EasyErrorHandler] Add default exception messages

---

packages/EasyErrorHandler/bundle/EasyErrorHandlerBundle.php
packages/EasyErrorHandler/bundle/Enum/ConfigParam.php
packages/EasyErrorHandler/bundle/config/default_builders.php
packages/EasyErrorHandler/bundle/config/definition.php
packages/EasyErrorHandler/laravel/EasyErrorHandlerServiceProvider.php
packages/EasyErrorHandler/laravel/config/easy-error-handler.php
packages/EasyErrorHandler/src/Common/Builder/MessageErrorResponseBuilder.php
packages/EasyErrorHandler/src/Common/Provider/DefaultErrorResponseBuilderProvider.php
packages/EasyErrorHandler/tests/Unit/laravel/ErrorHandlerTest.php

[EasyErrorHandler] Refactor exception_messages logic

---

packages/EasyDoctrine/bundle/CompilerPass/WithEventsEntityManagerCompilerPass.php
packages/EasyDoctrine/bundle/EasyDoctrineBundle.php
packages/EasyDoctrine/bundle/config/deferred_dispatcher.php
packages/EasyDoctrine/bundle/config/services.php
packages/EasyDoctrine/src/EntityEvent/EntityManager/WithEventsEntityManager.php
quality/rector.php

[EasyDoctrine] Decorate all EMs with WithEventsEntityManager

---

packages/EasyErrorHandler/bundle/EasyErrorHandlerBundle.php
packages/EasyErrorHandler/bundle/Enum/ConfigParam.php
packages/EasyErrorHandler/bundle/config/default_builders.php
packages/EasyErrorHandler/bundle/config/definition.php
packages/EasyErrorHandler/laravel/EasyErrorHandlerServiceProvider.php
packages/EasyErrorHandler/laravel/config/easy-error-handler.php
packages/EasyErrorHandler/src/Common/Builder/StatusCodeErrorResponseBuilder.php
packages/EasyErrorHandler/src/Common/Provider/DefaultErrorResponseBuilderProvider.php
packages/EasyErrorHandler/tests/Fixture/app/config/packages/easy_error_handler.php
packages/EasyErrorHandler/tests/Stub/Exception/DummyException.php
packages/EasyErrorHandler/tests/Stub/Exception/DummyExceptionInterface.php
packages/EasyErrorHandler/tests/Unit/bundle/TestRenderWithDefaultBuilderDataProvider.php
packages/EasyErrorHandler/tests/Unit/laravel/ErrorHandlerTest.php

[EasyErrorHandler] Allow configuring status codes for exceptions

---

packages/EasyApiPlatform/bundle/EasyApiPlatformBundle.php
packages/EasyApiPlatform/bundle/Enum/ConfigParam.php
packages/EasyApiPlatform/bundle/config/definition.php
packages/EasyApiPlatform/bundle/config/easy_error_handler.php
packages/EasyApiPlatform/src/EasyErrorHandler/Builder/AbstractApiPlatformExceptionErrorResponseBuilder.php
packages/EasyApiPlatform/src/EasyErrorHandler/Builder/AbstractApiPlatformSerializerExceptionErrorResponseBuilder.php
packages/EasyApiPlatform/src/EasyErrorHandler/Builder/ApiPlatformCustomSerializerExceptionErrorResponseBuilder.php
packages/EasyApiPlatform/src/EasyErrorHandler/Builder/ApiPlatformValidationExceptionErrorResponseBuilder.php
packages/EasyApiPlatform/tests/Application/src/EasyErrorHandler/Provider/ApiPlatformErrorResponseBuilderProviderTest.php
packages/EasyApiPlatform/tests/Fixture/app/config/packages/easy_api_platform.php
packages/EasyApiPlatform/tests/Fixture/app/src/EasyErrorHandler/Enum/ErrorCode.php
packages/EasyErrorHandler/bundle/EasyErrorHandlerBundle.php
packages/EasyErrorHandler/bundle/Enum/ConfigParam.php
packages/EasyErrorHandler/bundle/config/default_builders.php
packages/EasyErrorHandler/bundle/config/definition.php
packages/EasyErrorHandler/laravel/EasyErrorHandlerServiceProvider.php
packages/EasyErrorHandler/laravel/config/easy-error-handler.php
packages/EasyErrorHandler/src/Common/Builder/CodeErrorResponseBuilder.php
packages/EasyErrorHandler/src/Common/Provider/DefaultErrorResponseBuilderProvider.php
packages/EasyErrorHandler/tests/Fixture/app/config/packages/easy_error_handler.php
packages/EasyErrorHandler/tests/Unit/bundle/TestRenderWithDefaultBuilderDataProvider.php
packages/EasyErrorHandler/tests/Unit/laravel/ErrorHandlerTest.php

[EasyErrorHandler] Allow configuring error codes for exceptions

---

.github/workflows/php_ci.yml
.github/workflows/split_tests.yml
composer.json
packages/EasyActivity/composer.json
packages/EasyApiPlatform/composer.json
packages/EasyApiToken/composer.json
packages/EasyAsync/composer.json
packages/EasyBatch/composer.json
packages/EasyBugsnag/composer.json
packages/EasyDoctrine/composer.json
packages/EasyEncryption/composer.json
packages/EasyHttpClient/composer.json
packages/EasyLock/composer.json
packages/EasyNotification/composer.json
packages/EasyPagination/composer.json
packages/EasyRepository/composer.json
packages/EasyTemplatingBlock/composer.json
packages/EasyTest/src/InvalidData/Maker/InvalidDataMaker.php
packages/EasyWebhook/composer.json
quality/phpstan.neon

[Monorepo] Run CI with lowest dependencies

---

packages/EasyApiPlatform/bundle/config/easy_error_handler.php
packages/EasyAsync/bundle/EasyAsyncBundle.php
packages/EasyBatch/bundle/EasyBatchBundle.php
packages/EasyLock/bundle/EasyLockBundle.php
packages/EasyPagination/bundle/config/default_resolver.php
packages/EasyRequestId/bundle/config/services.php
packages/EasySecurity/bundle/config/services.php
packages/EasySwoole/bundle/config/services.php
packages/EasySwoole/bundle/config/static_php_files.php

[Monorepo] Add todo about priority

---

packages/EasyBatch/src/Common/Transformer/AbstractBatchObjectTransformer.php
packages/EasyBatch/tests/Unit/src/Common/Transformer/BatchItemTransformerTest.php

[EasyBatch] Support old batch object FQCN

---

packages/EasyTest/src/InvalidData/Maker/InvalidDataMaker.php

[EasyTest] Fix InvalidDataMaker

---

packages/EasyDoctrine/src/Common/Entity/TimestampableTrait.php

[EasyDoctrine] Allow setting custom updatedAt

---

packages/EasyDoctrine/src/Common/EntityManager/EntityManagerAwareTrait.php
packages/EasyErrorHandler/src/Common/ErrorHandler/ErrorHandlerAwareTrait.php
packages/EasyLock/src/Common/Locker/ProcessWithLockTrait.php
packages/EasyLogging/src/Logger/LoggerAwareTrait.php
packages/EasyUtils/src/Common/Translator/TranslatorAwareTrait.php
quality/phpstan.neon

[Monorepo] Make service trait property readonly

---

composer.json
packages/EasyPagination/src/Paginator/EloquentPaginatorTrait.php
packages/EasySecurity/composer.json
quality/phpstan.neon

[Monorepo] Fix CI for latest deps versions

---

packages/EasyApiPlatform/tests/Application/src/EasyErrorHandler/Provider/ApiPlatformErrorResponseBuilderProviderTest.php

[EasyApiPlatform] Fix cyrillic letter in date format in tests

---

packages/EasyErrorHandler/bundle/translations/EasyErrorHandlerBundle.en.php
packages/EasyErrorHandler/laravel/translations/en/exceptions.php

[EasyErrorHandler] Add todo about translations

---

packages/EasyUtils/src/Math/Constraint/AbstractNumberComparison.php

[EasyUtils] Fix abstract number comparison 

---

packages/EasyErrorHandler/src/Common/Builder/UserMessageErrorResponseBuilder.php
packages/EasyErrorHandler/src/Common/Exception/TranslatableExceptionInterface.php
packages/EasyErrorHandler/src/Common/Exception/TranslatableExceptionTrait.php
packages/EasyErrorHandler/src/Common/Resolver/ErrorDetailsResolver.php

Add the setter for `skipTranslation` to enable or disable translation skipping at exception static method level.

[EasyErrorHandler] Update TranslatableExceptionTrait 

---

packages/EasySwoole/src/Common/Listener/TrustedProxiesListener.php
packages/EasySwoole/src/Common/Resetter/SymfonyServicesAppStateResetter.php

[EasySwoole] Fix PHPStan for latest deps

---

composer.json
packages/EasyApiPlatform/composer.json
packages/EasyApiPlatform/tests/Application/src/EasyErrorHandler/Provider/ApiPlatformErrorResponseBuilderProviderTest.php
packages/EasyApiPlatform/tests/Fixture/app/src/EasyErrorHandler/ApiResource/Note.php

[EasyApiPlatform] Add test when datetime with custom format as constructor argument

---

packages/EasyTest/src/HttpClient/Response/AbstractTestResponse.php

[EasyTest] Fix data normalization in AbstractTestResponse

---

packages/EasyDoctrine/bundle/EasyDoctrineBundle.php
packages/EasyDoctrine/bundle/Enum/ConfigParam.php
packages/EasyDoctrine/bundle/Enum/ConfigServiceId.php
packages/EasyDoctrine/bundle/config/aws_rds_iam.php
packages/EasyDoctrine/bundle/config/aws_rds_ssl.php

[EasyDoctrine] FIX Logger configuration for AWS services 

---

packages/EasyUtils/src/SensitiveData/Hydrator/ObjectHydratorInterface.php
packages/EasyUtils/src/SensitiveData/Sanitizer/SensitiveDataSanitizer.php
packages/EasyUtils/src/SensitiveData/Sanitizer/SensitiveDataSanitizerInterface.php
packages/EasyUtils/tests/Unit/AbstractSensitiveDataSanitizerTestCase.php

[EasyUtils] Add generics to SensitiveDataSanitizerInterface

---

packages/EasyLock/src/Common/Locker/LockerInterface.php
packages/EasyLock/src/Common/Locker/ProcessWithLockTrait.php

[EasyLock] Add generics for `ProcessWithLockTrait` and `LockerInterface`

---

packages/EasyTest/src/Faker/Provider/AbnProvider.php

[EasyTest] Add AbnProvider test faker provider

---

composer.json
packages/EasyActivity/composer.json
packages/EasyApiPlatform/composer.json
packages/EasyBatch/composer.json
packages/EasyBugsnag/composer.json
packages/EasyDoctrine/composer.json
packages/EasyErrorHandler/composer.json
packages/EasyHttpClient/composer.json
packages/EasySchedule/composer.json
packages/EasySwoole/composer.json
packages/EasyWebhook/composer.json

[Monorepo] Fix CVE-2025-22145

---

composer.json
packages/EasyActivity/composer.json
packages/EasyApiPlatform/composer.json
packages/EasyAsync/composer.json
packages/EasyBugsnag/composer.json
packages/EasyDoctrine/composer.json
packages/EasyEncryption/composer.json
packages/EasyHttpClient/composer.json
packages/EasyLock/composer.json
packages/EasyPagination/composer.json
packages/EasyRepository/composer.json

[Monorepo] Allow doctrine/collections 2

---

packages/EasyTest/src/Common/Trait/ContainerServiceTrait.php

added methods:
getFaker
enableActivityLogging

[EasyTest] Some methods added to ContainerServiceTrait

---

packages/EasySwoole/src/Common/Resetter/SymfonyServicesAppStateResetter.php
quality/phpstan.neon

[EasySwoole] Revert SymfonyServicesAppStateResetter breaking changes

---

packages/EasyTest/src/Coverage/Command/CheckCoverageCommand.php
packages/EasyTest/src/Coverage/Resolver/CloverCoverageResolver.php
packages/EasyTest/tests/Fixture/Coverage/coverage_70.clover
packages/EasyTest/tests/Unit/src/Coverage/Command/CheckCoverageCommandTest.php

[EasyTest] Show uncovered lines

---

packages/EasyNotification/composer.json
packages/EasyNotification/src/Transport/SqsQueueTransport.php
packages/EasyNotification/tests/Unit/src/Transport/SqsQueueTransportTest.php

[EasyNotification] FIFO queue support

---

packages/EasyServerless/bundle/EasyServerlessBundle.php
packages/EasyServerless/bundle/config/monolog.php
packages/EasyServerless/composer.json
packages/EasyServerless/src/Monolog/Processor/PhpSourceProcessor.php

[EasyServerless] Add PHP source to logs in Symfony

---

packages/EasyServerless/src/Aws/Helper/LambdaContextHelper.php
packages/EasyServerless/src/Aws/Helper/SecretsHelper.php

[EasyServerless] Improve secrets loading logic to support known use-cases

---

packages/EasyServerless/bundle/EasyServerlessBundle.php
packages/EasyServerless/bundle/config/easy_admin.php
packages/EasyServerless/src/EasyAdmin/Subscriber/ResetEasyAdminStateSubscriber.php
quality/phpstan.neon

[EasyServerless] Handle EasyAdmin statefulness

---

packages/EasyServerless/src/Aws/Helper/SecretsHelper.php

Yes this PR contains BC break but nobody is using this package for real yet, so it's kinda experimental and the previous implementation was not working as expected, so let's just fix it now 😄

[EasyServerless] Fix SecretsHelper implementation

---

composer.json
packages/EasyApiPlatform/composer.json

[EasyApiPlatform] Api platform security version fix

---

packages/EasyLock/src/Common/Locker/ProcessWithLockTrait.php

[EasyLock] Remove readonly from $locker property

---

packages/EasyServerless/src/Runtime/ServerlessSymfonyRuntime.php

[EasyServerless] Create a runtime class for Symfony applications

---

packages/EasyServerless/src/Aws/Helper/SecretsHelper.php

[EasyServerless] Optimise secrets loading + add logging for debugging

---

packages/EasyUtils/src/Common/Constraint/Acn.php
packages/EasyUtils/src/Common/Validator/AcnValidator.php
packages/EasyUtils/tests/Unit/src/Common/Validator/AcnValidatorTest.php

[EasyUtils] feature/Add-AcnValidator

---

packages/EasyApiPlatform/src/EasyErrorHandler/Builder/ApiPlatformUnexpectedValueExceptionErrorResponseBuilder.php
packages/EasyApiPlatform/tests/Application/src/EasyErrorHandler/Provider/ApiPlatformErrorResponseBuilderProviderTest.php
packages/EasyApiPlatform/tests/Fixture/app/src/EasyErrorHandler/ApiResource/Invoice.php
packages/EasyApiPlatform/tests/Fixture/app/src/EasyErrorHandler/DataTransferObject/InvoiceInputDtoWithConstructor.php

[EasyApiPlatform] Handle validation error when input dto with constructor

---

composer.json
packages/EasyApiToken/composer.json
packages/EasyApiToken/docs/decoders.md
packages/EasyServerless/src/Aws/Kernel/AbstractServerlessHttpKernel.php

Support IP address change within the lifetime of a given Lambda function

[EasyServerless] Update REMOTE_ADDR on each request

---

composer.json
packages/EasyApiPlatform/composer.json
packages/EasyApiPlatform/src/EasyErrorHandler/Builder/ApiPlatformValidationExceptionErrorResponseBuilder.php
packages/EasyApiPlatform/tests/Application/src/EasyErrorHandler/Provider/ApiPlatformErrorResponseBuilderProviderTest.php
packages/EasyApiPlatform/tests/Fixture/app/src/EasyErrorHandler/ApiResource/Payment.php
packages/EasyApiPlatform/tests/Fixture/app/src/EasyErrorHandler/StateProvider/PaymentStateProvider.php

[EasyApiPlatform] Update error handling

---

packages/EasyServerless/src/Common/Resetter/SymfonyServicesAppStateResetter.php
quality/phpstan.neon

[EasyServerless] Extend ServicesResetter in SymfonyServicesAppStateResetter

---

packages/EasyUtils/src/Common/Validator/AcnValidator.php
packages/EasyUtils/tests/Unit/src/Common/Validator/AcnValidatorTest.php

Rework AcnValidator to treat 000000000 as an invalid ACN

[EasyUtils] Rework AcnValidator to treat 000000000 as an invalid ACN

---

packages/EasyServerless/bundle/CompilerPass/SymfonyServicesResetCompilerPass.php
packages/EasyServerless/bundle/EasyServerlessBundle.php
packages/EasyServerless/bundle/Enum/ConfigTag.php
packages/EasyServerless/bundle/config/definition.php
packages/EasyServerless/bundle/config/doctrine.php
packages/EasyServerless/bundle/config/state.php
packages/EasyServerless/laravel/EasyServerlessServiceProvider.php
packages/EasyServerless/laravel/Jobs/SqsQueueJob.php
packages/EasyServerless/laravel/SqsHandlers/SqsHandler.php
packages/EasyServerless/src/Aws/HttpHandler/SymfonyHttpHandler.php
packages/EasyServerless/src/Aws/Kernel/AbstractServerlessHttpKernel.php
packages/EasyServerless/src/Aws/Runtime/ServerlessSymfonyRuntime.php
packages/EasyServerless/src/Aws/Subscriber/InvocationLifecycleSubscriber.php
packages/EasyServerless/src/Doctrine/Checker/ManagersChecker.php
packages/EasyServerless/src/Runtime/ServerlessSymfonyRuntime.php
packages/EasyServerless/src/State/Checker/StateCheckerInterface.php
packages/EasyServerless/src/State/Listener/CheckStateListener.php
packages/EasyServerless/src/State/Resetter/SymfonyServicesAppStateResetter.php
packages/EasyServerless/tests/Stub/Kernel/KernelStub.php
quality/ecs.php
quality/phpstan.neon

Please pay attention to the `ServerlessSymfonyRuntime` class which has been moved within the `Aws` namespace

[EasyServerless] Introduce app state checks

---

packages/EasyServerless/bundle/config/services.php
packages/EasyServerless/bundle/config/state.php

[EasyServerless] Fix symfony services resetter depending on state check

---

composer.json
packages/EasyServerless/composer.json
packages/EasyServerless/src/Cache/Adapter/DynamoDbAdapter.php

[EasyServerless] Implement Symfony cache adapter using DynamoDB

---

packages/EasySwoole/bundle/CompilerPass/SymfonyServicesResetCompilerPass.php

[EasySwoole] Fix `SymfonyServicesResetCompilerPass`

---

packages/EasyServerless/bundle/CompilerPass/SymfonyServicesResetCompilerPass.php

[EasyServerless] Fix `SymfonyServicesResetCompilerPass`

---

packages/EasyDoctrine/src/SessionHandler/OrmSessionHandler.php

[EasyDoctrine] Implement session handler

---

packages/EasyUtils/bundle/config/services.php
packages/EasyUtils/src/Common/EnvVarProcessor/NullableEnumEnvVarProcessor.php

[EasyUtils] Implement `NullableEnumEnvVarProcessor`

---

packages/EasyUtils/src/Csv/Provider/FromFileCsvContentsProvider.php

[EasyUtils] Fix fgetcsv deprecation

---

packages/EasySecurity/src/SymfonySecurity/Authenticator/SecurityContextAuthenticator.php

- Iprove authentication exception logging
| Fixed tickets | [MTCE-510](https://eonx.atlassian.net/browse/MTCE-510)
[MTCE-510]: https://eonx.atlassian.net/browse/MTCE-510?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[EasySecurity] Improve authentication exception logging

---

packages/EasyTest/src/Common/Trait/MessengerAssertionsTrait.php

[EasyTest] Cleanup added subscribers for worker

---

packages/EasyBankFiles/src/Parsing/Ach/Parser/AchParser.php

[EasyBankFiles] Fix ACH parser for more fields lengths

---

packages/EasyRequestId/composer.json
packages/EasyRequestId/src/Common/Provider/RequestIdProvider.php

[EasyRequestId] Make RequestIdProvider resettable

---

packages/EasyDoctrine/bundle/CompilerPass/MigrationsFactoryCompilerPass.php
packages/EasyDoctrine/bundle/CompilerPass/WithEventsEntityManagerCompilerPass.php
packages/EasySchedule/src/Command/ScheduleRunCommand.php

[Monorepo] Fixed minor deprecations

---

packages/EasyBankFiles/src/Parsing/Nai/ValueObject/TransactionDetailCodesTrait.php

[EasyBankFiles] Update TransactionDetailCodesTrait

---

packages/EasyBankFiles/src/Parsing/Nai/ValueObject/TransactionDetailCodesTrait.php

[EasyBankFiles] Add all ACH codes to TransactionDetailCodesTrait

---

packages/EasyLock/bundle/EasyLockBundle.php
packages/EasyLock/bundle/config/doctrine.php
packages/EasyLock/composer.json
packages/EasyLock/src/Common/Locker/Locker.php

[EasyLock] Remove hard dependency for doctrine
